import { describe, it, expect } from '@rstest/core';
import { generateDatabaseTf } from './generate-database-tf';

describe('generateDatabaseTf', () => {
  describe('DB subnet group', () => {
    it('should create db subnet group resource', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('resource "aws_db_subnet_group" "main"');
    });

    it('should use private subnets', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('subnet_ids  = aws_subnet.private[*].id');
    });

    it('should use project name in subnet group name', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('name        = "${var.project_name}-db"');
    });
  });

  describe('master password', () => {
    it('should create random password resource', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('resource "random_password" "db_master"');
    });

    it('should generate 32 character password', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('length  = 32');
    });

    it('should not include special characters', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('special = false');
    });
  });

  describe('RDS instance', () => {
    it('should create RDS instance resource', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('resource "aws_db_instance" "main"');
    });

    it('should use postgres engine', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('engine         = "postgres"');
    });

    it('should use postgres version 15', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('engine_version = "15"');
    });

    it('should use instance class variable', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('instance_class = var.db_instance_class');
    });

    it('should use postgres as db name and username', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('db_name  = "postgres"');
      expect(result).toContain('username = "postgres"');
    });

    it('should use generated password', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('password = random_password.db_master.result');
    });

    it('should not be publicly accessible', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('publicly_accessible    = false');
    });

    it('should enable storage encryption', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('storage_encrypted     = true');
    });

    it('should use gp3 storage type', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('storage_type          = "gp3"');
    });

    it('should configure backups', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('backup_retention_period   = 7');
      expect(result).toContain('backup_window             = "03:00-04:00"');
    });

    it('should enable deletion protection by default', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('deletion_protection       = true');
    });

    it('should not skip final snapshot', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('skip_final_snapshot       = false');
    });

    it('should use RDS security group', () => {
      const result = generateDatabaseTf();
      expect(result).toContain(
        'vpc_security_group_ids = [aws_security_group.rds.id]',
      );
    });
  });

  describe('secrets manager', () => {
    it('should create secret for master password', () => {
      const result = generateDatabaseTf();
      expect(result).toContain(
        'resource "aws_secretsmanager_secret" "db_master_password"',
      );
    });

    it('should create secret version with password', () => {
      const result = generateDatabaseTf();
      expect(result).toContain(
        'resource "aws_secretsmanager_secret_version" "db_master_password"',
      );
      expect(result).toContain(
        'secret_string = random_password.db_master.result',
      );
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateDatabaseTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateDatabaseTf();
      expect(result).toMatchSnapshot();
    });
  });
});
