/**
 * Generate redis.tf with ElastiCache Redis instance
 *
 * Creates:
 * - Subnet group (uses private subnets)
 * - Parameter group (noeviction for BullMQ)
 * - Random auth token
 * - Replication group (single node, NOT cluster mode)
 *
 * Important: BullMQ requires single-node Redis for atomic operations.
 * num_cache_clusters = 1 means one node, no clustering.
 *
 * TLS is enabled (transit_encryption_enabled = true).
 */

export function generateRedisTf(): string {
  return `# ElastiCache Redis
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# Subnet Group
# =============================================================================

resource "aws_elasticache_subnet_group" "main" {
  name        = "\${var.project_name}-redis"
  description = "Redis subnet group for \${var.project_name}"
  subnet_ids  = aws_subnet.private[*].id

  tags = { Name = "\${var.project_name}-redis" }
}

# =============================================================================
# Parameter Group
# noeviction is required for BullMQ job queues
# =============================================================================

resource "aws_elasticache_parameter_group" "main" {
  family      = "redis7"
  name        = "\${var.project_name}-redis"
  description = "Redis parameters for \${var.project_name}"

  parameter {
    name  = "maxmemory-policy"
    value = "noeviction"
  }

  tags = { Name = "\${var.project_name}-redis" }
}

# =============================================================================
# Auth Token
# =============================================================================

resource "random_password" "redis_auth" {
  length  = 32
  special = false
}

# =============================================================================
# ElastiCache Replication Group
# Single node (NOT cluster mode) for BullMQ compatibility
# =============================================================================

resource "aws_elasticache_replication_group" "main" {
  replication_group_id = "\${var.project_name}-redis"
  description          = "\${var.project_name} Redis"
  node_type            = var.redis_node_type
  num_cache_clusters   = 1  # Single node, NOT cluster mode

  engine               = "redis"
  engine_version       = "7.0"
  port                 = 6379
  parameter_group_name = aws_elasticache_parameter_group.main.name
  subnet_group_name    = aws_elasticache_subnet_group.main.name
  security_group_ids   = [aws_security_group.redis.id]

  at_rest_encryption_enabled = true
  transit_encryption_enabled = true
  auth_token                 = random_password.redis_auth.result

  automatic_failover_enabled = false
  multi_az_enabled           = false

  tags = { Name = "\${var.project_name}-redis" }
}
`;
}
