import { describe, it, expect } from '@rstest/core';
import { generateLoggingTf } from './generate-logging-tf';

describe('generateLoggingTf', () => {
  const result = generateLoggingTf();

  describe('ALB access logs bucket', () => {
    it('should create ALB logs S3 bucket', () => {
      expect(result).toContain('resource "aws_s3_bucket" "alb_logs"');
    });

    it('should include account ID in bucket name for uniqueness', () => {
      expect(result).toContain(
        '${var.project_name}-${var.environment}-alb-logs-${var.aws_account_id}',
      );
    });

    it('should configure 90 day lifecycle', () => {
      expect(result).toContain(
        'resource "aws_s3_bucket_lifecycle_configuration" "alb_logs"',
      );
      expect(result).toContain('days = 90');
    });

    it('should configure bucket policy for ELB log delivery', () => {
      expect(result).toContain('resource "aws_s3_bucket_policy" "alb_logs"');
      expect(result).toContain(
        'logdelivery.elasticloadbalancing.amazonaws.com',
      );
    });
  });

  describe('CloudFront logs bucket', () => {
    it('should create CloudFront logs S3 bucket', () => {
      expect(result).toContain('resource "aws_s3_bucket" "cloudfront_logs"');
    });

    it('should enable ACL-based ownership for CloudFront logging', () => {
      expect(result).toContain(
        'resource "aws_s3_bucket_ownership_controls" "cloudfront_logs"',
      );
      expect(result).toContain('object_ownership = "BucketOwnerPreferred"');
    });

    it('should set log-delivery-write ACL', () => {
      expect(result).toContain(
        'resource "aws_s3_bucket_acl" "cloudfront_logs"',
      );
      expect(result).toContain('acl    = "log-delivery-write"');
    });

    it('should configure 90 day lifecycle', () => {
      expect(result).toContain(
        'resource "aws_s3_bucket_lifecycle_configuration" "cloudfront_logs"',
      );
    });
  });

  describe('WAF logging (CloudFront scope)', () => {
    it('should create CloudWatch log group with required prefix', () => {
      expect(result).toContain('resource "aws_cloudwatch_log_group" "waf"');
      expect(result).toContain('name              = "aws-waf-logs-');
    });

    it('should use us-east-1 provider for CloudFront WAF', () => {
      const wafLogGroup = result.slice(
        result.indexOf('resource "aws_cloudwatch_log_group" "waf"'),
        result.indexOf(
          'resource "aws_wafv2_web_acl_logging_configuration" "main"',
        ),
      );
      expect(wafLogGroup).toContain('provider = aws.us_east_1');
    });

    it('should set 90 day retention', () => {
      expect(result).toContain('retention_in_days = 90');
    });

    it('should create WAF logging configuration for main Web ACL', () => {
      expect(result).toContain(
        'resource "aws_wafv2_web_acl_logging_configuration" "main"',
      );
      expect(result).toContain(
        'resource_arn            = aws_wafv2_web_acl.main.arn',
      );
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });
});
