import { describe, it, expect } from '@rstest/core';
import { generateEcrTf } from './generate-ecr-tf';

describe('generateEcrTf', () => {
  describe('ECR repositories', () => {
    it('should create repositories using for_each', () => {
      const result = generateEcrTf();
      expect(result).toContain('resource "aws_ecr_repository" "service"');
      expect(result).toContain('for_each = var.all_deployables');
    });

    it('should use project name in repository name', () => {
      const result = generateEcrTf();
      expect(result).toContain(
        'name                 = "${var.project_name}/${each.key}"',
      );
    });

    it('should enable image scanning on push', () => {
      const result = generateEcrTf();
      expect(result).toContain('scan_on_push = true');
    });

    it('should use mutable image tags', () => {
      const result = generateEcrTf();
      expect(result).toContain('image_tag_mutability = "MUTABLE"');
    });

    it('should enable force_delete for non-empty repo cleanup', () => {
      const result = generateEcrTf();
      expect(result).toContain('force_delete         = true');
    });
  });

  describe('lifecycle policy', () => {
    it('should create lifecycle policy for cleanup', () => {
      const result = generateEcrTf();
      expect(result).toContain('resource "aws_ecr_lifecycle_policy" "cleanup"');
    });

    it('should keep only 10 images', () => {
      const result = generateEcrTf();
      expect(result).toContain('countNumber = 10');
    });

    it('should expire images when count exceeds limit', () => {
      const result = generateEcrTf();
      expect(result).toContain('countType   = "imageCountMoreThan"');
      expect(result).toContain('type = "expire"');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateEcrTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateEcrTf();
      expect(result).toMatchSnapshot();
    });
  });
});
