import { describe, it, expect } from '@rstest/core';
import { generateDbInit } from './generate-db-init';

describe('generateDbInit', () => {
  describe('return value', () => {
    it('should return object with dockerfile, packageJson, and indexJs', () => {
      const result = generateDbInit();
      expect(result).toHaveProperty('dockerfile');
      expect(result).toHaveProperty('packageJson');
      expect(result).toHaveProperty('indexJs');
    });
  });

  describe('dockerfile', () => {
    it('should use Node.js 22 alpine', () => {
      const { dockerfile } = generateDbInit();
      expect(dockerfile).toContain('FROM node:22-alpine');
    });

    it('should set WORKDIR to /app', () => {
      const { dockerfile } = generateDbInit();
      expect(dockerfile).toContain('WORKDIR /app');
    });

    it('should copy package.json first for caching', () => {
      const { dockerfile } = generateDbInit();
      expect(dockerfile).toContain('COPY package.json ./');
    });

    it('should run npm install production', () => {
      const { dockerfile } = generateDbInit();
      expect(dockerfile).toContain('RUN npm install --production');
    });

    it('should run node index.js', () => {
      const { dockerfile } = generateDbInit();
      expect(dockerfile).toContain('CMD ["node", "index.js"]');
    });
  });

  describe('packageJson', () => {
    it('should be valid JSON', () => {
      const { packageJson } = generateDbInit();
      expect(() => JSON.parse(packageJson)).not.toThrow();
    });

    it('should have name db-init', () => {
      const { packageJson } = generateDbInit();
      const pkg = JSON.parse(packageJson);
      expect(pkg.name).toBe('db-init');
    });

    it('should be private', () => {
      const { packageJson } = generateDbInit();
      const pkg = JSON.parse(packageJson);
      expect(pkg.private).toBe(true);
    });

    it('should have pg dependency', () => {
      const { packageJson } = generateDbInit();
      const pkg = JSON.parse(packageJson);
      expect(pkg.dependencies).toHaveProperty('pg');
    });

    it('should have AWS Secrets Manager SDK dependency', () => {
      const { packageJson } = generateDbInit();
      const pkg = JSON.parse(packageJson);
      expect(pkg.dependencies).toHaveProperty(
        '@aws-sdk/client-secrets-manager',
      );
    });
  });

  describe('indexJs', () => {
    it('should include generation comment', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain('Generated by: npx tsdevstack infra:generate');
    });

    it('should import pg Client', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain("const { Client } = require('pg');");
    });

    it('should import Secrets Manager client', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain('SecretsManagerClient');
      expect(indexJs).toContain('CreateSecretCommand');
      expect(indexJs).toContain('PutSecretValueCommand');
    });

    it('should read environment variables', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain('process.env.PROJECT');
      expect(indexJs).toContain('process.env.ENVIRONMENT');
      expect(indexJs).toContain('process.env.DB_HOST');
      expect(indexJs).toContain('process.env.DB_MASTER_PASSWORD');
      expect(indexJs).toContain('process.env.SERVICES');
    });

    it('should parse SERVICES JSON', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain('JSON.parse(servicesJson)');
    });

    it('should filter services with databases', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain('services.filter((s) => s.hasDatabase)');
    });

    it('should connect to RDS as postgres user', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain("user: 'postgres'");
      expect(indexJs).toContain('password: masterPassword');
    });

    it('should use SSL connection', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain('ssl: { rejectUnauthorized: false }');
    });

    it('should check if database exists', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain('SELECT 1 FROM pg_database WHERE datname = $1');
    });

    it('should check if user exists', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain('SELECT 1 FROM pg_roles WHERE rolname = $1');
    });

    it('should create database if not exists', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain('CREATE DATABASE');
    });

    it('should create user with password', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain('CREATE USER');
      expect(indexJs).toContain('WITH PASSWORD');
    });

    it('should grant privileges', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain('GRANT ALL PRIVILEGES ON DATABASE');
      expect(indexJs).toContain('GRANT ALL ON SCHEMA public TO');
    });

    it('should build DATABASE_URL', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain("'postgresql://'");
    });

    it('should generate password', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toContain('function generatePassword()');
      expect(indexJs).toContain('randomBytes(24)');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot for dockerfile', () => {
      const { dockerfile } = generateDbInit();
      expect(dockerfile).toMatchSnapshot();
    });

    it('should match snapshot for packageJson', () => {
      const { packageJson } = generateDbInit();
      expect(packageJson).toMatchSnapshot();
    });

    it('should match snapshot for indexJs', () => {
      const { indexJs } = generateDbInit();
      expect(indexJs).toMatchSnapshot();
    });
  });
});
