import { describe, it, expect } from '@rstest/core';
import { generateAppRunnerTf } from './generate-apprunner-tf';

describe('generateAppRunnerTf', () => {
  describe('IAM role for ECR access', () => {
    it('should create IAM role for ECR access', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain(
        'resource "aws_iam_role" "apprunner_ecr_access"',
      );
    });

    it('should be conditional on nextjs_services', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain(
        'count = length(var.nextjs_services) > 0 ? 1 : 0',
      );
    });

    it('should allow App Runner to assume role', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain('Service = "build.apprunner.amazonaws.com"');
    });

    it('should attach ECR access policy', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain(
        'resource "aws_iam_role_policy_attachment" "apprunner_ecr_access"',
      );
      expect(result).toContain('AWSAppRunnerServicePolicyForECRAccess');
    });
  });

  describe('auto-scaling configuration', () => {
    it('should create per-service auto-scaling configuration', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain(
        'resource "aws_apprunner_auto_scaling_configuration_version" "nextjs"',
      );
      expect(result).toContain('for_each = var.nextjs_services');
    });

    it('should clamp min_size to at least 1', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain('min_size = max(each.value.minInstances, 1)');
    });

    it('should use maxInstances from config', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain('max_size = each.value.maxInstances');
    });

    it('should include service name in scaling config name', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain(
        'auto_scaling_configuration_name = "${var.project_name}-${var.environment}-${each.key}"',
      );
    });
  });

  describe('WAF origin protection', () => {
    it('should create random secret for origin verification', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain(
        'resource "random_password" "apprunner_origin_secret"',
      );
    });

    it('should create WAF Web ACL for App Runner', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain('resource "aws_wafv2_web_acl" "apprunner"');
      expect(result).toContain('scope       = "REGIONAL"');
    });

    it('should block by default', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain('default_action {\n    block {}');
    });

    it('should allow requests with valid X-Origin-Verify header', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain('name = "x-origin-verify"');
      expect(result).toContain('positional_constraint = "EXACTLY"');
    });

    it('should create WAF association for App Runner services', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain(
        'resource "aws_wafv2_web_acl_association" "apprunner"',
      );
      expect(result).toContain('for_each = var.nextjs_service_arns');
    });
  });

  describe('outputs', () => {
    it('should output ECR access role ARN', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain('output "apprunner_ecr_access_role_arn"');
    });

    it('should output per-service auto-scaling ARNs', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain('output "apprunner_autoscaling_arns"');
    });

    it('should output origin verify secret', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain('output "apprunner_origin_verify_secret"');
      expect(result).toContain('sensitive   = true');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateAppRunnerTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateAppRunnerTf();
      expect(result).toMatchSnapshot();
    });
  });
});
