import { describe, it, expect } from '@rstest/core';
import { generateDbInitTf } from './generate-db-init-tf';

describe('generateDbInitTf', () => {
  describe('ECR repository', () => {
    it('should create ECR repository', () => {
      const result = generateDbInitTf();
      expect(result).toContain('resource "aws_ecr_repository" "db_init"');
    });

    it('should use project_name/db-init as repo name', () => {
      const result = generateDbInitTf();
      expect(result).toContain(
        'name                 = "${var.project_name}/db-init"',
      );
    });

    it('should enable scan on push', () => {
      const result = generateDbInitTf();
      expect(result).toContain('scan_on_push = true');
    });

    it('should create lifecycle policy to keep 5 images', () => {
      const result = generateDbInitTf();
      expect(result).toContain(
        'resource "aws_ecr_lifecycle_policy" "db_init_cleanup"',
      );
      expect(result).toContain('countNumber = 5');
    });
  });

  describe('CloudWatch log group', () => {
    it('should create log group', () => {
      const result = generateDbInitTf();
      expect(result).toContain('resource "aws_cloudwatch_log_group" "db_init"');
    });

    it('should use /ecs/ prefix', () => {
      const result = generateDbInitTf();
      expect(result).toContain(
        'name              = "/ecs/${var.project_name}/db-init"',
      );
    });

    it('should retain logs for 30 days', () => {
      const result = generateDbInitTf();
      expect(result).toContain('retention_in_days = 30');
    });
  });

  describe('IAM role for db-init task', () => {
    it('should create IAM role', () => {
      const result = generateDbInitTf();
      expect(result).toContain('resource "aws_iam_role" "db_init_task"');
    });

    it('should allow ECS tasks to assume role', () => {
      const result = generateDbInitTf();
      expect(result).toContain('Service = "ecs-tasks.amazonaws.com"');
    });

    it('should allow reading master password', () => {
      const result = generateDbInitTf();
      expect(result).toContain('Sid    = "ReadMasterPassword"');
      expect(result).toContain('"secretsmanager:GetSecretValue"');
    });

    it('should allow managing service secrets', () => {
      const result = generateDbInitTf();
      expect(result).toContain('Sid    = "ManageServiceSecrets"');
      expect(result).toContain('"secretsmanager:CreateSecret"');
      expect(result).toContain('"secretsmanager:PutSecretValue"');
    });
  });

  describe('ECS task definition', () => {
    it('should create task definition', () => {
      const result = generateDbInitTf();
      expect(result).toContain('resource "aws_ecs_task_definition" "db_init"');
    });

    it('should use Fargate', () => {
      const result = generateDbInitTf();
      expect(result).toContain('requires_compatibilities = ["FARGATE"]');
    });

    it('should use awsvpc network mode', () => {
      const result = generateDbInitTf();
      expect(result).toContain('network_mode             = "awsvpc"');
    });

    it('should pass DB_HOST environment variable', () => {
      const result = generateDbInitTf();
      expect(result).toContain(
        '{ name = "DB_HOST", value = aws_db_instance.main.address }',
      );
    });

    it('should inject master password from secrets', () => {
      const result = generateDbInitTf();
      expect(result).toContain('name      = "DB_MASTER_PASSWORD"');
      expect(result).toContain(
        'valueFrom = aws_secretsmanager_secret.db_master_password.arn',
      );
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateDbInitTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateDbInitTf();
      expect(result).toMatchSnapshot();
    });
  });
});
