/**
 * Generate route53.tf with DNS A records for CloudFront
 *
 * Creates:
 * - A record for api.base_domain → API CloudFront
 *
 * Note: Route 53 hosted zone is looked up in acm.tf via data source.
 * The zone must exist before deployment.
 * SPA and Next.js records are created in their respective .tf files.
 */

export function generateRoute53Tf(): string {
  return `# Route 53 DNS A Records
# Generated by: npx tsdevstack infra:generate
#
# Creates DNS A records pointing to CloudFront.
# Route 53 hosted zone lookup is in acm.tf.

# =============================================================================
# API Domain A Record (e.g., api.createdevstack.app -> API CloudFront)
# =============================================================================

resource "aws_route53_record" "api" {
  count = var.base_domain != "" ? 1 : 0

  zone_id = data.aws_route53_zone.main[0].zone_id
  name    = local.api_domain
  type    = "A"

  alias {
    name                   = aws_cloudfront_distribution.main.domain_name
    zone_id                = aws_cloudfront_distribution.main.hosted_zone_id
    evaluate_target_health = false
  }
}
`;
}
