/**
 * Generate ecs.tf with ECS cluster, task definitions, and services
 *
 * Creates:
 * - ECS Cluster with Container Insights
 * - CloudWatch Log Groups (per service/worker/nextjs)
 * - Task Definitions (per service, worker, and nextjs)
 * - ECS Services (Kong behind the ALB, backend services on Cloud Map only)
 *
 * Only Kong is registered with an ALB target group (the default route of the
 * external HTTPS listener). Next.js services use host-based routing on the same
 * listener (port 443).
 * Backend services have no load balancer: they register with Cloud Map and are
 * reached inside the VPC as {service}.{project}.local:8080, by Kong and by
 * other services.
 * Every service runs at least one task (AWS has no scale-to-zero).
 * NestJS services, Kong, workers and Next.js scale on CPU (target tracking, 70%)
 * between minInstances and maxInstances.
 * Workers are always-on (minInstances >= 1) because they poll Redis.
 */

export function generateEcsTf(): string {
  return `# ECS Cluster, Services, and Workers
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# ECS Cluster
# =============================================================================

resource "aws_ecs_cluster" "main" {
  name = "\${var.project_name}-cluster"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }

  tags = { Name = "\${var.project_name}-cluster" }
}

# =============================================================================
# CloudWatch Log Groups
# =============================================================================

resource "aws_cloudwatch_log_group" "service" {
  for_each          = var.services
  name              = "/ecs/\${var.project_name}/\${each.key}"
  retention_in_days = 30
  kms_key_id        = aws_kms_key.logs.arn

  tags = { Name = "\${var.project_name}-\${each.key}-logs" }
}

resource "aws_cloudwatch_log_group" "worker" {
  for_each          = var.workers
  name              = "/ecs/\${var.project_name}/\${each.key}"
  retention_in_days = 30
  kms_key_id        = aws_kms_key.logs.arn

  tags = { Name = "\${var.project_name}-\${each.key}-logs" }
}

# =============================================================================
# Task Definitions (Services)
# =============================================================================

resource "aws_ecs_task_definition" "service" {
  for_each = var.services

  family                   = "\${var.project_name}-\${each.key}"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = each.value.cpu
  memory                   = each.value.memory
  execution_role_arn       = aws_iam_role.ecs_execution.arn
  task_role_arn            = aws_iam_role.task[each.key].arn

  container_definitions = jsonencode([{
    name  = each.key
    image = "\${aws_ecr_repository.service[each.key].repository_url}:latest"

    portMappings = [{
      containerPort = 8080
      protocol      = "tcp"
    }]

    # Base environment variables for all services
    # Kong gets additional vars for its proxy port and DNS resolution
    environment = concat(
      [
        { name = "NODE_ENV", value = "production" },
        { name = "PORT", value = "8080" },
        { name = "SERVICE_NAME", value = each.key },
        { name = "CLOUD_PROVIDER", value = "aws" },
        { name = "SECRETS_PROVIDER", value = "aws" },
        { name = "AWS_REGION", value = var.aws_region },
        { name = "PROJECT_NAME", value = var.project_name },
        { name = "DB_POOL_MAX", value = tostring(each.value.dbPoolMax) },
      ],
      each.key == "kong" ? [
        # Kong proxy port - must match ALB target group and ECS health check (8080)
        { name = "KONG_PROXY_LISTEN", value = "0.0.0.0:8080" },
        # Use VPC DNS to resolve Cloud Map service names (auth-service.tsdevstack.local)
        # VPC DNS is at CIDR base + 2 (10.0.0.2 for 10.0.0.0/16 VPC)
        { name = "KONG_DNS_RESOLVER", value = "10.0.0.2" },
      ] : []
    )

    # Note: Secrets are injected via CLI deployment, not hard-coded here
    # The deployment process updates the task definition with secret ARNs

    logConfiguration = {
      logDriver = "awslogs"
      options = {
        "awslogs-group"         = "/ecs/\${var.project_name}/\${each.key}"
        "awslogs-region"        = var.aws_region
        "awslogs-stream-prefix" = "ecs"
      }
    }

    # Kong: readiness of its status API (/status/ready on 8100), baked into the image
    # as kong-health-check.sh; it does not wait for backends (OIDC discovery is
    # fetched on the first authenticated request). Other services: /health endpoint.
    healthCheck = {
      command     = each.key == "kong" ? ["CMD-SHELL", "/usr/local/bin/kong-health-check.sh"] : ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval    = 30
      timeout     = 5
      retries     = 3
      startPeriod = 60
    }
  }])

  tags = { Name = "\${var.project_name}-\${each.key}-task" }
}

# =============================================================================
# ECS Services
# =============================================================================

resource "aws_ecs_service" "service" {
  for_each = var.services

  name            = each.key
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.service[each.key].arn
  desired_count   = max(each.value.minInstances, 1)  # At least 1 (AWS has no scale-to-zero)
  launch_type     = "FARGATE"

  # Grace period before ALB health checks start (gives container time to start)
  # Only Kong is behind the ALB; backend services have no load balancer
  health_check_grace_period_seconds = each.key == "kong" ? 120 : null

  # Zero-downtime deployment: keep old task until new one is healthy
  deployment_minimum_healthy_percent = 100
  deployment_maximum_percent         = 200

  # Circuit breaker: automatically fail stuck deployments and rollback
  # Prevents zombie deployments from competing with new ones
  deployment_circuit_breaker {
    enable   = true
    rollback = true
  }

  network_configuration {
    subnets          = aws_subnet.private[*].id
    security_groups  = [aws_security_group.ecs.id]
    assign_public_ip = false
  }

  # Only Kong is registered with the ALB (external traffic via CloudFront)
  # Backend services are private: reachable only inside the VPC via Cloud Map
  dynamic "load_balancer" {
    for_each = each.key == "kong" ? [1] : []
    content {
      target_group_arn = aws_lb_target_group.service[each.key].arn
      container_name   = each.key
      container_port   = 8080
    }
  }

  # Backend services register with Cloud Map ({service}.{project}.local)
  # Kong calls them there; services call each other there too
  # Kong itself is not called by name inside the VPC, so it is not registered
  dynamic "service_registries" {
    for_each = each.key != "kong" ? [1] : []
    content {
      registry_arn = aws_service_discovery_service.service[each.key].arn
    }
  }

  depends_on = [aws_lb_listener.https]

  tags = { Name = "\${var.project_name}-\${each.key}-service" }

  lifecycle {
    # task_definition: CLI creates task defs with secrets, Terraform shouldn't override
    # desired_count: Auto-scaling manages this
    ignore_changes = [task_definition, desired_count]
  }
}

# =============================================================================
# Service Auto Scaling (NestJS services and Kong)
# Services scale on CPU utilization within their configured min/max range
# (minInstances >= 1: AWS has no scale-to-zero)
# =============================================================================

resource "aws_appautoscaling_target" "service" {
  for_each = var.services

  max_capacity       = each.value.maxInstances
  min_capacity       = each.value.minInstances
  resource_id        = "service/\${aws_ecs_cluster.main.name}/\${aws_ecs_service.service[each.key].name}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"

  depends_on = [aws_ecs_service.service]
}

resource "aws_appautoscaling_policy" "service_cpu" {
  for_each = var.services

  name               = "\${var.project_name}-\${each.key}-cpu"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.service[each.key].resource_id
  scalable_dimension = aws_appautoscaling_target.service[each.key].scalable_dimension
  service_namespace  = aws_appautoscaling_target.service[each.key].service_namespace

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "ECSServiceAverageCPUUtilization"
    }
    target_value       = 70.0
    scale_out_cooldown = 60
    scale_in_cooldown  = 300
  }

  depends_on = [aws_appautoscaling_target.service]
}

# =============================================================================
# Task Definitions (Workers)
# =============================================================================

resource "aws_ecs_task_definition" "worker" {
  for_each = var.workers

  family                   = "\${var.project_name}-\${each.key}"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = each.value.cpu
  memory                   = each.value.memory
  execution_role_arn       = aws_iam_role.ecs_execution.arn
  task_role_arn            = aws_iam_role.task[each.value.service].arn

  container_definitions = jsonencode([{
    name  = each.key
    image = "\${aws_ecr_repository.service[each.value.service].repository_url}:latest"

    # Override Dockerfile CMD to run worker entrypoint instead of main API server
    command = ["dumb-init", "node", "dist/worker.js"]

    environment = [
      { name = "NODE_ENV", value = "production" },
      { name = "SERVICE_NAME", value = each.value.service },
      { name = "WORKER_NAME", value = each.key },
      { name = "CLOUD_PROVIDER", value = "aws" },
      { name = "SECRETS_PROVIDER", value = "aws" },
      { name = "AWS_REGION", value = var.aws_region },
      { name = "PROJECT_NAME", value = var.project_name },
      { name = "DB_POOL_MAX", value = tostring(each.value.dbPoolMax) },
    ]

    logConfiguration = {
      logDriver = "awslogs"
      options = {
        "awslogs-group"         = "/ecs/\${var.project_name}/\${each.key}"
        "awslogs-region"        = var.aws_region
        "awslogs-stream-prefix" = "ecs"
      }
    }
  }])

  tags = { Name = "\${var.project_name}-\${each.key}-task" }
}

# =============================================================================
# ECS Services (Workers - Always Running)
# Workers poll Redis — minInstances >= 1 enforced by CLI
# =============================================================================

resource "aws_ecs_service" "worker" {
  for_each = var.workers

  name            = each.key
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.worker[each.key].arn
  desired_count   = each.value.minInstances
  launch_type     = "FARGATE"

  # Zero-downtime deployment: keep old task until new one is healthy
  deployment_minimum_healthy_percent = 100
  deployment_maximum_percent         = 200

  # Circuit breaker: automatically fail stuck deployments and rollback
  # Prevents zombie deployments from competing with new ones
  deployment_circuit_breaker {
    enable   = true
    rollback = true
  }

  network_configuration {
    subnets          = aws_subnet.private[*].id
    security_groups  = [aws_security_group.ecs.id]
    assign_public_ip = false
  }

  # Workers don't receive HTTP traffic - no load_balancer
  # Workers aren't called by name - no service_registries

  tags = { Name = "\${var.project_name}-\${each.key}-worker" }

  lifecycle {
    # task_definition: CLI creates task defs with secrets, Terraform shouldn't override
    # desired_count: Auto-scaling manages this
    ignore_changes = [task_definition, desired_count]
  }
}

# =============================================================================
# Worker Auto Scaling
# Workers scale based on CPU utilization within their configured min/max range
# =============================================================================

resource "aws_appautoscaling_target" "worker" {
  for_each = var.workers

  max_capacity       = each.value.maxInstances
  min_capacity       = each.value.minInstances
  resource_id        = "service/\${aws_ecs_cluster.main.name}/\${aws_ecs_service.worker[each.key].name}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"

  depends_on = [aws_ecs_service.worker]
}

resource "aws_appautoscaling_policy" "worker_cpu" {
  for_each = var.workers

  name               = "\${var.project_name}-\${each.key}-cpu"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.worker[each.key].resource_id
  scalable_dimension = aws_appautoscaling_target.worker[each.key].scalable_dimension
  service_namespace  = aws_appautoscaling_target.worker[each.key].service_namespace

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "ECSServiceAverageCPUUtilization"
    }
    target_value       = 70.0
    scale_out_cooldown = 60
    scale_in_cooldown  = 300
  }

  depends_on = [aws_appautoscaling_target.worker]
}

# =============================================================================
# CloudWatch Log Groups (Next.js)
# =============================================================================

resource "aws_cloudwatch_log_group" "nextjs" {
  for_each          = var.nextjs_services
  name              = "/ecs/\${var.project_name}/\${each.key}"
  retention_in_days = 30
  kms_key_id        = aws_kms_key.logs.arn

  tags = { Name = "\${var.project_name}-\${each.key}-logs" }
}

# =============================================================================
# Task Definitions (Next.js)
# Same Docker image as built by CLI, uses Dockerfile CMD (no command override)
# =============================================================================

resource "aws_ecs_task_definition" "nextjs" {
  for_each = var.nextjs_services

  family                   = "\${var.project_name}-\${each.key}"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = each.value.cpu
  memory                   = each.value.memory
  execution_role_arn       = aws_iam_role.ecs_execution.arn
  task_role_arn            = aws_iam_role.nextjs_task[each.key].arn

  container_definitions = jsonencode([{
    name  = each.key
    image = "\${aws_ecr_repository.service[each.key].repository_url}:latest"

    portMappings = [{
      containerPort = 8080
      protocol      = "tcp"
    }]

    environment = [
      { name = "NODE_ENV", value = "production" },
      { name = "PORT", value = "8080" },
      { name = "HOSTNAME", value = "0.0.0.0" },
      { name = "SERVICE_NAME", value = each.key },
      { name = "CLOUD_PROVIDER", value = "aws" },
      { name = "SECRETS_PROVIDER", value = "aws" },
      { name = "AWS_REGION", value = var.aws_region },
      { name = "PROJECT_NAME", value = var.project_name },
    ]

    logConfiguration = {
      logDriver = "awslogs"
      options = {
        "awslogs-group"         = "/ecs/\${var.project_name}/\${each.key}"
        "awslogs-region"        = var.aws_region
        "awslogs-stream-prefix" = "ecs"
      }
    }

    healthCheck = {
      command     = ["CMD-SHELL", "node -e \\"fetch('http://localhost:8080/health').then(r=>{if(!r.ok)throw r.status}).catch(()=>process.exit(1))\\""]
      interval    = 30
      timeout     = 5
      retries     = 3
      startPeriod = 60
    }
  }])

  tags = { Name = "\${var.project_name}-\${each.key}-task" }
}

# =============================================================================
# ECS Services (Next.js)
# Routed via ALB host-based rules on port 443 (not through Kong)
# =============================================================================

resource "aws_ecs_service" "nextjs" {
  for_each = var.nextjs_services

  name            = each.key
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.nextjs[each.key].arn
  desired_count   = max(each.value.minInstances, 1)
  launch_type     = "FARGATE"

  health_check_grace_period_seconds = 120

  deployment_minimum_healthy_percent = 100
  deployment_maximum_percent         = 200

  deployment_circuit_breaker {
    enable   = true
    rollback = true
  }

  network_configuration {
    subnets          = aws_subnet.private[*].id
    security_groups  = [aws_security_group.ecs.id]
    assign_public_ip = false
  }

  load_balancer {
    target_group_arn = aws_lb_target_group.nextjs[each.key].arn
    container_name   = each.key
    container_port   = 8080
  }

  depends_on = [aws_lb_listener.https]

  tags = { Name = "\${var.project_name}-\${each.key}-service" }

  lifecycle {
    ignore_changes = [task_definition, desired_count]
  }
}

# =============================================================================
# Next.js Auto Scaling
# =============================================================================

resource "aws_appautoscaling_target" "nextjs" {
  for_each = var.nextjs_services

  max_capacity       = each.value.maxInstances
  min_capacity       = max(each.value.minInstances, 1)
  resource_id        = "service/\${aws_ecs_cluster.main.name}/\${aws_ecs_service.nextjs[each.key].name}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"

  depends_on = [aws_ecs_service.nextjs]
}

resource "aws_appautoscaling_policy" "nextjs_cpu" {
  for_each = var.nextjs_services

  name               = "\${var.project_name}-\${each.key}-cpu"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.nextjs[each.key].resource_id
  scalable_dimension = aws_appautoscaling_target.nextjs[each.key].scalable_dimension
  service_namespace  = aws_appautoscaling_target.nextjs[each.key].service_namespace

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "ECSServiceAverageCPUUtilization"
    }
    target_value       = 70.0
    scale_out_cooldown = 60
    scale_in_cooldown  = 300
  }

  depends_on = [aws_appautoscaling_target.nextjs]
}
`;
}
