import { describe, it, expect } from '@rstest/core';
import { generateWakeupLambdaCode } from './generate-wakeup-lambda-code';

describe('generateWakeupLambdaCode', () => {
  describe('imports', () => {
    it('should import ECS client', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain('ECSClient');
    });

    it('should import UpdateServiceCommand', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain('UpdateServiceCommand');
    });
  });

  describe('environment variables', () => {
    it('should read ECS_CLUSTER from environment', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain('const CLUSTER = process.env.ECS_CLUSTER;');
    });

    it('should read MANAGED_SERVICES from environment', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain('const SERVICES = process.env.MANAGED_SERVICES');
    });
  });

  describe('health endpoint', () => {
    it('should respond 200 to /health', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain("if (path === '/health')");
      expect(result).toContain('statusCode: 200');
    });

    it('should return JSON with status ok', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain("{ status: 'ok', service: 'wakeup-lambda' }");
    });
  });

  describe('wake-up logic', () => {
    it('should scale services to 1', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain('desiredCount: 1');
    });

    it('should be fire-and-forget (no wait loop)', () => {
      const result = generateWakeupLambdaCode();
      // Should NOT contain wait logic
      expect(result).not.toContain('maxWait');
      expect(result).not.toContain('DescribeServicesCommand');
      expect(result).not.toContain('while (Date.now()');
    });

    it('should log scale commands sent', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain('Scale commands sent for services');
    });
  });

  describe('response', () => {
    it('should return 202 Accepted', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain('statusCode: 202');
    });

    it('should return JSON with wake-up message', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain("message: 'Wake-up triggered'");
      expect(result).toContain('services: SERVICES');
    });

    it('should include Content-Type header', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain("'Content-Type': 'application/json'");
    });
  });

  describe('error handling', () => {
    it('should handle no services configured', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain('No services configured');
      expect(result).toContain('statusCode: 500');
    });

    it('should catch and log errors', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain('catch (error)');
      expect(result).toContain("console.error('Wake-up failed:', error)");
    });
  });

  describe('authentication', () => {
    it('should read WAKEUP_SECRET from environment', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain(
        'const WAKEUP_SECRET = process.env.WAKEUP_SECRET;',
      );
    });

    it('should validate X-Wake-Secret header', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain("headers['x-wake-secret']");
      expect(result).toContain("headers['X-Wake-Secret']");
    });

    it('should return 403 for invalid secret', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain('statusCode: 403');
      expect(result).toContain("error: 'Forbidden'");
    });

    it('should skip auth for health endpoint', () => {
      const result = generateWakeupLambdaCode();
      // Health check should come before secret validation
      const healthIndex = result.indexOf("if (path === '/health')");
      const secretIndex = result.indexOf('providedSecret !== WAKEUP_SECRET');
      expect(healthIndex).toBeLessThan(secretIndex);
    });

    it('should log unauthorized attempts', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain('Unauthorized wake-up attempt');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateWakeupLambdaCode();
      expect(result).toMatchSnapshot();
    });
  });
});
