/**
 * Generate scale-down.tf with CloudWatch alarms for scale-to-zero
 *
 * Creates:
 * - Application Auto Scaling targets (allows ECS to scale to 0)
 * - CloudWatch alarms that trigger when service is idle (CPU < 5% for 15 min)
 * - Step scaling policies that set desired_count to 0
 *
 * Uses ECS CPU metrics for idle detection since services use CloudMap
 * (only Kong has an ALB target group).
 *
 * Services with minInstances >= 1 are excluded (e.g., Kong for wake-up failover).
 */

export function generateScaleDownTf(): string {
  return `# Scale-to-Zero Configuration
# Generated by: npx tsdevstack infra:generate
#
# Enables ECS services to scale to zero when idle.
# Services with minInstances >= 1 are excluded (won't scale to zero).

# =============================================================================
# Application Auto Scaling Targets
# Required for scaling policies - allows min_capacity = 0
# =============================================================================

resource "aws_appautoscaling_target" "service" {
  # Exclude kong - it must stay running for wake-up mechanism
  for_each = { for name, cfg in var.services : name => cfg if cfg.minInstances == 0 }

  max_capacity       = each.value.maxInstances
  min_capacity       = 0  # Allow scale to zero
  resource_id        = "service/\${aws_ecs_cluster.main.name}/\${aws_ecs_service.service[each.key].name}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"

  depends_on = [aws_ecs_service.service]
}

# =============================================================================
# CloudWatch Alarms: Idle Detection
# Triggers when CPU is below 5% for 15 minutes (3 x 5-minute periods)
# Uses ECS metrics since services use CloudMap, not ALB target groups
# =============================================================================

resource "aws_cloudwatch_metric_alarm" "service_idle" {
  for_each = { for name, cfg in var.services : name => cfg if cfg.minInstances == 0 }

  alarm_name          = "\${var.project_name}-\${var.environment}-\${each.key}-idle"
  comparison_operator = "LessThanThreshold"
  evaluation_periods  = 3        # 3 consecutive periods
  metric_name         = "CPUUtilization"
  namespace           = "AWS/ECS"
  period              = 300      # 5 minutes (3 x 5 = 15 minutes total)
  statistic           = "Average"
  threshold           = 5        # Below 5% CPU = idle

  dimensions = {
    ClusterName = aws_ecs_cluster.main.name
    ServiceName = each.key
  }

  alarm_actions = [aws_appautoscaling_policy.scale_to_zero[each.key].arn]

  # Don't alarm when there's no data (service already at zero)
  treat_missing_data = "notBreaching"

  tags = { Name = "\${var.project_name}-\${each.key}-idle-alarm" }
}

# =============================================================================
# Scale-to-Zero Policies
# Sets desired_count to exactly 0 when alarm triggers
# =============================================================================

resource "aws_appautoscaling_policy" "scale_to_zero" {
  for_each = { for name, cfg in var.services : name => cfg if cfg.minInstances == 0 }

  name               = "\${each.key}-scale-to-zero"
  policy_type        = "StepScaling"
  resource_id        = aws_appautoscaling_target.service[each.key].resource_id
  scalable_dimension = aws_appautoscaling_target.service[each.key].scalable_dimension
  service_namespace  = aws_appautoscaling_target.service[each.key].service_namespace

  step_scaling_policy_configuration {
    adjustment_type         = "ExactCapacity"
    cooldown                = 900  # 15 min - prevents rapid re-scaling after wake-up
    metric_aggregation_type = "Average"

    step_adjustment {
      scaling_adjustment          = 0  # Set to exactly 0
      metric_interval_upper_bound = 0
    }
  }

  depends_on = [aws_appautoscaling_target.service]
}

# =============================================================================
# Scale-Up Policies (CPU-based)
# Handles normal scaling when traffic increases
# =============================================================================

resource "aws_appautoscaling_policy" "scale_up" {
  for_each = { for name, cfg in var.services : name => cfg if cfg.minInstances == 0 }

  name               = "\${each.key}-scale-up"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.service[each.key].resource_id
  scalable_dimension = aws_appautoscaling_target.service[each.key].scalable_dimension
  service_namespace  = aws_appautoscaling_target.service[each.key].service_namespace

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "ECSServiceAverageCPUUtilization"
    }
    target_value       = 70.0
    scale_out_cooldown = 60
    disable_scale_in   = true  # Scale-in handled by step-scaling idle alarm (15-min cooldown)
  }

  depends_on = [aws_appautoscaling_target.service]
}
`;
}
