import { describe, it, expect } from '@rstest/core';
import { generateScaleDownTf } from './generate-scale-down-tf';

describe('generateScaleDownTf', () => {
  describe('Application Auto Scaling targets', () => {
    it('should create auto scaling target', () => {
      const result = generateScaleDownTf();
      expect(result).toContain(
        'resource "aws_appautoscaling_target" "service"',
      );
    });

    it('should only target services with minInstances == 0', () => {
      const result = generateScaleDownTf();
      expect(result).toContain(
        'for_each = { for name, cfg in var.services : name => cfg if cfg.minInstances == 0 }',
      );
    });

    it('should allow min_capacity of 0', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('min_capacity       = 0');
    });

    it('should use ECS scalable dimension', () => {
      const result = generateScaleDownTf();
      expect(result).toContain(
        'scalable_dimension = "ecs:service:DesiredCount"',
      );
      expect(result).toContain('service_namespace  = "ecs"');
    });
  });

  describe('CloudWatch idle detection alarm', () => {
    it('should create metric alarm for idle detection', () => {
      const result = generateScaleDownTf();
      expect(result).toContain(
        'resource "aws_cloudwatch_metric_alarm" "service_idle"',
      );
    });

    it('should use CPU utilization metric', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('metric_name         = "CPUUtilization"');
      expect(result).toContain('namespace           = "AWS/ECS"');
    });

    it('should use LessThanThreshold comparison', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('comparison_operator = "LessThanThreshold"');
    });

    it('should evaluate 3 periods of 5 minutes', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('evaluation_periods  = 3');
      expect(result).toContain('period              = 300');
    });

    it('should trigger below 5% CPU threshold', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('threshold           = 5');
    });

    it('should treat missing data as not breaching', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('treat_missing_data = "notBreaching"');
    });
  });

  describe('scale-to-zero policies', () => {
    it('should create scale-to-zero policy', () => {
      const result = generateScaleDownTf();
      expect(result).toContain(
        'resource "aws_appautoscaling_policy" "scale_to_zero"',
      );
    });

    it('should use StepScaling policy type', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('policy_type        = "StepScaling"');
    });

    it('should use ExactCapacity adjustment type', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('adjustment_type         = "ExactCapacity"');
    });

    it('should set scaling adjustment to 0', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('scaling_adjustment          = 0');
    });
  });

  describe('scale-up policies', () => {
    it('should create scale-up policy', () => {
      const result = generateScaleDownTf();
      expect(result).toContain(
        'resource "aws_appautoscaling_policy" "scale_up"',
      );
    });

    it('should use TargetTrackingScaling policy type', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('policy_type        = "TargetTrackingScaling"');
    });

    it('should target 70% CPU utilization', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('target_value       = 70.0');
    });

    it('should use ECS CPU metric', () => {
      const result = generateScaleDownTf();
      expect(result).toContain(
        'predefined_metric_type = "ECSServiceAverageCPUUtilization"',
      );
    });

    it('should have scale-out cooldown', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('scale_out_cooldown = 60');
    });

    it('should disable scale-in (handled by step-scaling idle alarm)', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('disable_scale_in   = true');
      expect(result).not.toContain('scale_in_cooldown');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateScaleDownTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateScaleDownTf();
      expect(result).toMatchSnapshot();
    });
  });
});
