/**
 * Generate db-init.tf with ECS task definition for database initialization
 *
 * Creates:
 * - ECR repository for db-init image
 * - ECS task definition for db-init
 * - IAM role for db-init task (secrets management)
 * - CloudWatch log group
 *
 * The db-init task creates per-service databases and users in RDS,
 * then writes DATABASE_URL secrets to Secrets Manager.
 */

export function generateDbInitTf(): string {
  return `# DB-Init Task
# Generated by: npx tsdevstack infra:generate
# Creates per-service databases and users in RDS PostgreSQL

# =============================================================================
# ECR Repository
# Separate repo for db-init image (not part of for_each deployables)
# =============================================================================

resource "aws_ecr_repository" "db_init" {
  name                 = "\${var.project_name}/db-init"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  tags = { Name = "\${var.project_name}-db-init" }
}

resource "aws_ecr_lifecycle_policy" "db_init_cleanup" {
  repository = aws_ecr_repository.db_init.name

  policy = jsonencode({
    rules = [{
      rulePriority = 1
      description  = "Keep only last 5 images"
      selection = {
        tagStatus   = "any"
        countType   = "imageCountMoreThan"
        countNumber = 5
      }
      action = { type = "expire" }
    }]
  })
}

# =============================================================================
# CloudWatch Log Group
# =============================================================================

resource "aws_cloudwatch_log_group" "db_init" {
  name              = "/ecs/\${var.project_name}/db-init"
  retention_in_days = 30
  kms_key_id        = aws_kms_key.logs.arn

  tags = { Name = "\${var.project_name}-db-init-logs" }
}

# =============================================================================
# IAM Role for db-init Task
# Needs: read master password, create/write per-service DATABASE_URL secrets
# =============================================================================

resource "aws_iam_role" "db_init_task" {
  name = "\${var.project_name}-\${var.environment}-db-init-task"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
    }]
  })

  tags = { Name = "\${var.project_name}-db-init-task" }
}

resource "aws_iam_role_policy" "db_init_secrets" {
  name = "secrets-access"
  role = aws_iam_role.db_init_task.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "ReadMasterPassword"
        Effect = "Allow"
        Action = ["secretsmanager:GetSecretValue"]
        Resource = [aws_secretsmanager_secret.db_master_password.arn]
      },
      {
        Sid    = "ManageServiceSecrets"
        Effect = "Allow"
        Action = [
          "secretsmanager:CreateSecret",
          "secretsmanager:PutSecretValue",
          "secretsmanager:UpdateSecret",
          "secretsmanager:DescribeSecret",
          "secretsmanager:GetSecretValue",
          "secretsmanager:TagResource"
        ]
        Resource = [
          "arn:aws:secretsmanager:\${var.aws_region}:\${var.aws_account_id}:secret:\${var.project_name}-*-DATABASE_URL*"
        ]
      }
    ]
  })
}

# =============================================================================
# ECS Task Definition
# =============================================================================

resource "aws_ecs_task_definition" "db_init" {
  family                   = "\${var.project_name}-db-init"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = 256
  memory                   = 512
  execution_role_arn       = aws_iam_role.ecs_execution.arn
  task_role_arn            = aws_iam_role.db_init_task.arn

  container_definitions = jsonencode([
    {
      name      = "db-init"
      image     = "\${aws_ecr_repository.db_init.repository_url}:latest"
      essential = true

      command = ["node", "index.js"]

      environment = [
        { name = "PROJECT", value = var.project_name },
        { name = "ENVIRONMENT", value = var.environment },
        { name = "DB_HOST", value = aws_db_instance.main.address },
        { name = "DB_PORT", value = tostring(aws_db_instance.main.port) },
        { name = "AWS_REGION", value = var.aws_region }
        # SERVICES env var is passed at runtime via container overrides
      ]

      secrets = [
        {
          name      = "DB_MASTER_PASSWORD"
          valueFrom = aws_secretsmanager_secret.db_master_password.arn
        }
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          "awslogs-group"         = aws_cloudwatch_log_group.db_init.name
          "awslogs-region"        = var.aws_region
          "awslogs-stream-prefix" = "db-init"
        }
      }
    }
  ])

  tags = { Name = "\${var.project_name}-db-init" }
}
`;
}
