/**
 * Generate logging.tf with shared logging infrastructure
 *
 * Creates:
 * - S3 bucket for ALB access logs (with ELB service principal policy)
 * - S3 bucket for CloudFront standard logs (with ACL for log delivery)
 * - CloudWatch Log Group for WAF (CloudFront scope)
 * - CloudWatch Log Group for WAF (App Runner scope)
 * - WAF logging configurations for both Web ACLs
 *
 * All CloudFront distributions share one S3 logging bucket with prefixes.
 * WAF logs go to CloudWatch for queryable real-time access.
 */

export function generateLoggingTf(): string {
  return `# Logging Infrastructure
# Generated by: npx tsdevstack infra:generate
#
# Shared logging resources for ALB, CloudFront, and WAF.

# =============================================================================
# ALB Access Logs (S3)
# =============================================================================

resource "aws_s3_bucket" "alb_logs" {
  bucket = "\${var.project_name}-\${var.environment}-alb-logs-\${var.aws_account_id}"

  tags = { Name = "\${var.project_name}-alb-logs" }
}

resource "aws_s3_bucket_lifecycle_configuration" "alb_logs" {
  bucket = aws_s3_bucket.alb_logs.id

  rule {
    id     = "expire-logs"
    status = "Enabled"

    filter {}

    expiration {
      days = 90
    }
  }
}

resource "aws_s3_bucket_policy" "alb_logs" {
  bucket = aws_s3_bucket.alb_logs.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AllowELBLogDelivery"
        Effect = "Allow"
        Principal = {
          Service = "logdelivery.elasticloadbalancing.amazonaws.com"
        }
        Action   = "s3:PutObject"
        Resource = "\${aws_s3_bucket.alb_logs.arn}/*"
      }
    ]
  })
}

# =============================================================================
# CloudFront Standard Logs (S3)
# =============================================================================
# CloudFront standard logging requires ACLs (legacy mechanism).
# All distributions share this bucket with different prefixes.

resource "aws_s3_bucket" "cloudfront_logs" {
  bucket = "\${var.project_name}-\${var.environment}-cf-logs-\${var.aws_account_id}"

  tags = { Name = "\${var.project_name}-cloudfront-logs" }
}

resource "aws_s3_bucket_ownership_controls" "cloudfront_logs" {
  bucket = aws_s3_bucket.cloudfront_logs.id

  rule {
    object_ownership = "BucketOwnerPreferred"
  }
}

resource "aws_s3_bucket_acl" "cloudfront_logs" {
  depends_on = [aws_s3_bucket_ownership_controls.cloudfront_logs]

  bucket = aws_s3_bucket.cloudfront_logs.id
  acl    = "log-delivery-write"
}

resource "aws_s3_bucket_lifecycle_configuration" "cloudfront_logs" {
  bucket = aws_s3_bucket.cloudfront_logs.id

  rule {
    id     = "expire-logs"
    status = "Enabled"

    filter {}

    expiration {
      days = 90
    }
  }
}

# =============================================================================
# WAF Logging (CloudWatch) - CloudFront scope
# =============================================================================
# WAF log group name MUST start with "aws-waf-logs-" (AWS requirement).

resource "aws_cloudwatch_log_group" "waf" {
  provider = aws.us_east_1

  name              = "aws-waf-logs-\${var.project_name}-\${var.environment}"
  retention_in_days = 90

  tags = { Name = "\${var.project_name}-waf-logs" }
}

resource "aws_wafv2_web_acl_logging_configuration" "main" {
  provider = aws.us_east_1

  log_destination_configs = [aws_cloudwatch_log_group.waf.arn]
  resource_arn            = aws_wafv2_web_acl.main.arn
}


`;
}
