/**
 * Generate db-delete directory files
 *
 * Generates:
 * - Dockerfile - Node.js alpine image for running db-delete
 * - package.json - Dependencies (pg)
 * - index.js - Main script that drops databases and users
 *
 * These files are generated into infrastructure/terraform/{env}/db-delete/
 * and built into a Docker image at deploy time.
 */

export interface DbDeleteFiles {
  dockerfile: string;
  packageJson: string;
  indexJs: string;
}

export function generateDbDelete(): DbDeleteFiles {
  return {
    dockerfile: generateDockerfile(),
    packageJson: generatePackageJson(),
    indexJs: generateIndexJs(),
  };
}

function generateDockerfile(): string {
  return `FROM node:22-alpine
WORKDIR /app
COPY package.json ./
RUN npm install --production
COPY index.js ./
CMD ["node", "index.js"]
`;
}

function generatePackageJson(): string {
  return `{
  "name": "db-delete",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "pg": "^8.11.0"
  }
}
`;
}

function generateIndexJs(): string {
  return `// DB-Delete Script
// Generated by: npx tsdevstack infra:generate
// Drops per-service databases and users from RDS PostgreSQL

const { Client } = require('pg');

// =============================================================================
// MAIN
// =============================================================================

async function main() {
  console.log('db-delete starting...');

  // Read environment
  const dbHost = process.env.DB_HOST;
  const dbPort = process.env.DB_PORT || '5432';
  const masterPassword = process.env.DB_MASTER_PASSWORD;
  const servicesJson = process.env.SERVICES;

  // Validate required env vars
  if (!dbHost || !masterPassword || !servicesJson) {
    console.error('Missing required environment variables:');
    console.error('  DB_HOST: ' + (dbHost ? 'set' : 'MISSING'));
    console.error('  DB_MASTER_PASSWORD: ' + (masterPassword ? 'set' : 'MISSING'));
    console.error('  SERVICES: ' + (servicesJson ? 'set' : 'MISSING'));
    process.exit(1);
  }

  // Parse services
  let services;
  try {
    services = JSON.parse(servicesJson);
  } catch (e) {
    console.error('Failed to parse SERVICES JSON:', e);
    process.exit(1);
  }

  if (!Array.isArray(services) || services.length === 0) {
    console.error('SERVICES must be a non-empty array');
    process.exit(1);
  }

  console.log('Services to delete: ' + services.join(', '));

  // Connect to RDS as master user
  const masterClient = new Client({
    host: dbHost,
    port: parseInt(dbPort),
    user: 'postgres',
    password: masterPassword,
    database: 'postgres',
    ssl: { rejectUnauthorized: false },
  });

  try {
    await masterClient.connect();
    console.log('Connected to RDS at ' + dbHost + ':' + dbPort + ' as postgres');
  } catch (e) {
    console.error('Failed to connect to RDS:', e);
    process.exit(1);
  }

  // Process each service
  for (const serviceName of services) {
    console.log('');
    console.log('============================================================');
    console.log('Processing: ' + serviceName);
    console.log('============================================================');

    const dbName = serviceName;
    const dbUser = serviceName;

    // Check if database exists
    const dbExistsResult = await masterClient.query(
      'SELECT 1 FROM pg_database WHERE datname = $1',
      [dbName]
    );
    const dbExists = (dbExistsResult.rowCount || 0) > 0;

    if (dbExists) {
      console.log('  -> Terminating active connections to database: ' + dbName);

      // Terminate all connections to the database (except this connection)
      await masterClient.query(
        "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()",
        [dbName]
      );
      console.log('  [OK] Active connections terminated');

      console.log('  -> Dropping database: ' + dbName);
      await masterClient.query('DROP DATABASE IF EXISTS "' + dbName + '"');
      console.log('  [OK] Database dropped');
    } else {
      console.log('  [SKIP] Database does not exist: ' + dbName);
    }

    // Check if user exists
    const userExistsResult = await masterClient.query(
      'SELECT 1 FROM pg_roles WHERE rolname = $1',
      [dbUser]
    );
    const userExists = (userExistsResult.rowCount || 0) > 0;

    if (userExists) {
      console.log('  -> Dropping user: ' + dbUser);
      await masterClient.query('DROP USER IF EXISTS "' + dbUser + '"');
      console.log('  [OK] User dropped');
    } else {
      console.log('  [SKIP] User does not exist: ' + dbUser);
    }
  }

  await masterClient.end();
  console.log('');
  console.log('============================================================');
  console.log('db-delete completed successfully');
  console.log('============================================================');
}

main().catch((e) => {
  console.error('db-delete failed with error:', e);
  process.exit(1);
});
`;
}
