/**
 * Generate ecr.tf with ECR repositories for container images
 *
 * Creates one repository per deployable (services + workers + kong).
 * Includes lifecycle policy to keep only 10 images per repo.
 */

export function generateEcrTf(): string {
  return `# ECR Container Registry
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# ECR Repositories
# One per deployable (services, workers, kong)
# =============================================================================

resource "aws_ecr_repository" "service" {
  for_each = var.all_deployables

  name                 = "\${var.project_name}/\${each.key}"
  image_tag_mutability = "MUTABLE"
  force_delete         = true

  image_scanning_configuration {
    scan_on_push = true
  }

  tags = { Name = "\${var.project_name}-\${each.key}" }
}

# =============================================================================
# Lifecycle Policy
# Keep only last 10 images to minimize storage costs
# =============================================================================

resource "aws_ecr_lifecycle_policy" "cleanup" {
  for_each   = var.all_deployables
  repository = aws_ecr_repository.service[each.key].name

  policy = jsonencode({
    rules = [{
      rulePriority = 1
      description  = "Keep only last 10 images"
      selection = {
        tagStatus   = "any"
        countType   = "imageCountMoreThan"
        countNumber = 10
      }
      action = { type = "expire" }
    }]
  })
}
`;
}
