/**
 * Generate kms.tf with KMS key for CloudWatch Logs encryption
 *
 * Creates:
 * - KMS key for encrypting all CloudWatch log groups
 * - KMS alias for readable reference
 * - Key policy allowing CloudWatch Logs service to use the key
 *
 * The key is shared by all log groups (ECS services, Lambda, VPC Flow Logs).
 */

export function generateKmsTf(): string {
  return `# KMS Key for CloudWatch Logs Encryption
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# KMS Key for CloudWatch Logs
# =============================================================================

resource "aws_kms_key" "logs" {
  description             = "\${var.project_name} CloudWatch Logs encryption key"
  deletion_window_in_days = 7
  enable_key_rotation     = true

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "EnableIAMUserPermissions"
        Effect = "Allow"
        Principal = {
          AWS = "arn:aws:iam::\${data.aws_caller_identity.current.account_id}:root"
        }
        Action   = "kms:*"
        Resource = "*"
      },
      {
        Sid    = "AllowCloudWatchLogs"
        Effect = "Allow"
        Principal = {
          Service = "logs.\${var.aws_region}.amazonaws.com"
        }
        Action = [
          "kms:Encrypt*",
          "kms:Decrypt*",
          "kms:ReEncrypt*",
          "kms:GenerateDataKey*",
          "kms:Describe*"
        ]
        Resource = "*"
        Condition = {
          ArnLike = {
            "kms:EncryptionContext:aws:logs:arn" = "arn:aws:logs:\${var.aws_region}:\${data.aws_caller_identity.current.account_id}:*"
          }
        }
      }
    ]
  })

  tags = { Name = "\${var.project_name}-logs-kms" }
}

resource "aws_kms_alias" "logs" {
  name          = "alias/\${var.project_name}-logs"
  target_key_id = aws_kms_key.logs.key_id
}

# =============================================================================
# Outputs
# =============================================================================

output "logs_kms_key_arn" {
  description = "ARN of the KMS key for CloudWatch Logs encryption"
  value       = aws_kms_key.logs.arn
}

output "logs_kms_key_id" {
  description = "ID of the KMS key for CloudWatch Logs encryption"
  value       = aws_kms_key.logs.key_id
}
`;
}
