import { describe, it, expect } from '@rstest/core';
import { generateIamTf } from './generate-iam-tf';

describe('generateIamTf', () => {
  describe('ECS task execution role', () => {
    it('should create execution role', () => {
      const result = generateIamTf();
      expect(result).toContain('resource "aws_iam_role" "ecs_execution"');
    });

    it('should allow ecs-tasks to assume role', () => {
      const result = generateIamTf();
      expect(result).toContain('Service = "ecs-tasks.amazonaws.com"');
      expect(result).toContain('Action = "sts:AssumeRole"');
    });

    it('should attach ECS task execution policy', () => {
      const result = generateIamTf();
      expect(result).toContain(
        'resource "aws_iam_role_policy_attachment" "ecs_execution"',
      );
      expect(result).toContain(
        'policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"',
      );
    });

    it('should allow secrets manager access', () => {
      const result = generateIamTf();
      expect(result).toContain(
        'resource "aws_iam_role_policy" "ecs_execution_secrets"',
      );
      expect(result).toContain('secretsmanager:GetSecretValue');
    });

    it('should restrict secrets to project namespace', () => {
      const result = generateIamTf();
      expect(result).toContain(
        'arn:aws:secretsmanager:${var.aws_region}:${var.aws_account_id}:secret:${var.project_name}-*',
      );
    });
  });

  describe('ECS task roles', () => {
    it('should create task roles per service using for_each', () => {
      const result = generateIamTf();
      expect(result).toContain('resource "aws_iam_role" "task"');
      expect(result).toContain('for_each = var.services');
    });

    it('should name roles with project and service name', () => {
      const result = generateIamTf();
      expect(result).toContain('name = "${var.project_name}-${each.key}-task"');
    });

    it('should allow ecs-tasks to assume task role', () => {
      const result = generateIamTf();
      // Find the task role assume_role_policy
      expect(result).toContain(
        'Principal = { Service = "ecs-tasks.amazonaws.com" }',
      );
    });

    it('should create secrets policy per service', () => {
      const result = generateIamTf();
      expect(result).toContain('resource "aws_iam_role_policy" "task_secrets"');
      expect(result).toContain('for_each = var.services');
    });

    it('should allow access to shared secrets', () => {
      const result = generateIamTf();
      expect(result).toContain('${var.project_name}-shared-*');
    });

    it('should allow access to service-specific secrets', () => {
      const result = generateIamTf();
      expect(result).toContain('${var.project_name}-${each.key}-*');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateIamTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateIamTf();
      expect(result).toMatchSnapshot();
    });
  });
});
