/**
 * Generate network.tf with VPC, subnets, NAT Gateway, security groups, Cloud Map
 *
 * AWS requires 2 AZs minimum for RDS/ElastiCache subnet groups.
 * Single NAT Gateway used to minimize cost (~$32/month).
 * Gateway endpoints for S3/DynamoDB are free.
 *
 * Cloud Map provides DNS-based service discovery for service-to-service calls.
 * Kong uses ALB for external routing (with wake-up failover).
 * See: docs/in-dev/phase-21-aws-service-discovery-fix.md
 */

export function generateNetworkTf(): string {
  return `# Network Infrastructure
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# VPC
# =============================================================================

resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = { Name = "\${var.project_name}-vpc" }
}

# =============================================================================
# Availability Zones
# =============================================================================

data "aws_availability_zones" "available" {
  state = "available"
}

# =============================================================================
# Subnets
# =============================================================================

# Public subnets (ALB)
resource "aws_subnet" "public" {
  count                   = 2
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.0.\${count.index + 1}.0/24"
  availability_zone       = data.aws_availability_zones.available.names[count.index]
  map_public_ip_on_launch = true

  tags = { Name = "\${var.project_name}-public-\${count.index + 1}" }
}

# Private subnets (ECS, RDS, Redis)
resource "aws_subnet" "private" {
  count             = 2
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.\${count.index + 10}.0/24"
  availability_zone = data.aws_availability_zones.available.names[count.index]

  tags = { Name = "\${var.project_name}-private-\${count.index + 1}" }
}

# =============================================================================
# Internet Gateway
# =============================================================================

resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id

  tags = { Name = "\${var.project_name}-igw" }
}

# =============================================================================
# NAT Gateway (single, cost optimization)
# =============================================================================

resource "aws_eip" "nat" {
  domain = "vpc"

  tags = { Name = "\${var.project_name}-nat-eip" }
}

resource "aws_nat_gateway" "main" {
  allocation_id = aws_eip.nat.id
  subnet_id     = aws_subnet.public[0].id

  tags = { Name = "\${var.project_name}-nat" }

  depends_on = [aws_internet_gateway.main]
}

# =============================================================================
# Route Tables
# =============================================================================

resource "aws_route_table" "public" {
  vpc_id = aws_vpc.main.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.main.id
  }

  tags = { Name = "\${var.project_name}-public-rt" }
}

resource "aws_route_table" "private" {
  vpc_id = aws_vpc.main.id

  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.main.id
  }

  tags = { Name = "\${var.project_name}-private-rt" }
}

resource "aws_route_table_association" "public" {
  count          = 2
  subnet_id      = aws_subnet.public[count.index].id
  route_table_id = aws_route_table.public.id
}

resource "aws_route_table_association" "private" {
  count          = 2
  subnet_id      = aws_subnet.private[count.index].id
  route_table_id = aws_route_table.private.id
}

# =============================================================================
# Security Groups
# =============================================================================

# ALB Security Group
# External traffic (port 443) protected by X-Origin-Verify header validation
# at ALB listener level - requests without valid header get 403.
# Internal ports (8443, 8080) for Kong upstream routing.
resource "aws_security_group" "alb" {
  name        = "\${var.project_name}-alb"
  description = "Security group for Application Load Balancer"
  vpc_id      = aws_vpc.main.id

  # External HTTPS traffic
  # Security: ALB listener validates X-Origin-Verify header from CloudFront
  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    description = "HTTPS (protected by origin header validation)"
  }

  # HTTP for redirect to HTTPS
  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    description = "HTTP redirect to HTTPS"
  }

  # Kong upstream routing via internal HTTPS listener (port 8443)
  # Open to 0.0.0.0/0 because ECS->ALB traffic routes through NAT Gateway,
  # which translates source IP to NAT's public EIP (outside VPC CIDR).
  # Security: Port 8443 only has host-header routing rules - no default action.
  ingress {
    from_port   = 8443
    to_port     = 8443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Internal HTTPS routing (Kong upstreams via NAT)"
  }

  # Kong OIDC discovery via internal HTTP listener (port 8080)
  # HTTP (not HTTPS) so ALB sets X-Forwarded-Proto: http, X-Forwarded-Port: 8080
  # Auth-service uses these headers to return jwks_uri that Kong can reach.
  # Open to 0.0.0.0/0 for same NAT Gateway routing reason as port 8443.
  # Security: Port 8080 only has path-based rule for /auth/.well-known/*.
  ingress {
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Internal HTTP routing (Kong OIDC discovery via NAT)"
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "\${var.project_name}-alb" }
}

# ECS Security Group
resource "aws_security_group" "ecs" {
  name        = "\${var.project_name}-ecs"
  description = "Security group for ECS tasks"
  vpc_id      = aws_vpc.main.id

  # Allow traffic from ALB
  ingress {
    from_port       = 8080
    to_port         = 8080
    protocol        = "tcp"
    security_groups = [aws_security_group.alb.id]
    description     = "Traffic from ALB"
  }

  # Allow service-to-service traffic
  ingress {
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    self        = true
    description = "Service-to-service"
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "\${var.project_name}-ecs" }
}

# RDS Security Group
resource "aws_security_group" "rds" {
  name        = "\${var.project_name}-rds"
  description = "Security group for RDS PostgreSQL"
  vpc_id      = aws_vpc.main.id

  ingress {
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = [aws_security_group.ecs.id]
    description     = "PostgreSQL from ECS"
  }

  tags = { Name = "\${var.project_name}-rds" }
}

# Redis Security Group
resource "aws_security_group" "redis" {
  name        = "\${var.project_name}-redis"
  description = "Security group for ElastiCache Redis"
  vpc_id      = aws_vpc.main.id

  ingress {
    from_port       = 6379
    to_port         = 6379
    protocol        = "tcp"
    security_groups = [aws_security_group.ecs.id]
    description     = "Redis from ECS"
  }

  tags = { Name = "\${var.project_name}-redis" }
}

# =============================================================================
# VPC Endpoints (Gateway - Free)
# =============================================================================

# S3 Gateway Endpoint (for Terraform state, ECR layers)
resource "aws_vpc_endpoint" "s3" {
  vpc_id            = aws_vpc.main.id
  service_name      = "com.amazonaws.\${var.aws_region}.s3"
  vpc_endpoint_type = "Gateway"
  route_table_ids   = [aws_route_table.private.id]

  tags = { Name = "\${var.project_name}-s3-endpoint" }
}

# DynamoDB Gateway Endpoint (for Terraform locks)
resource "aws_vpc_endpoint" "dynamodb" {
  vpc_id            = aws_vpc.main.id
  service_name      = "com.amazonaws.\${var.aws_region}.dynamodb"
  vpc_endpoint_type = "Gateway"
  route_table_ids   = [aws_route_table.private.id]

  tags = { Name = "\${var.project_name}-dynamodb-endpoint" }
}

# =============================================================================
# Cloud Map (Service Discovery)
# =============================================================================
# Provides DNS-based service discovery for service-to-service calls.
# Services register as {service-name}.{project-name}.local
# Kong uses ALB for external routing; Cloud Map is for direct internal calls.

resource "aws_service_discovery_private_dns_namespace" "main" {
  name        = "\${var.project_name}.local"
  description = "Service discovery namespace for \${var.project_name}"
  vpc         = aws_vpc.main.id

  tags = {
    Name        = "\${var.project_name}-namespace"
    Environment = var.environment
    ManagedBy   = "tsdevstack"
  }
}

resource "aws_service_discovery_service" "service" {
  for_each = { for name, cfg in var.services : name => cfg if name != "kong" }

  name = each.key

  dns_config {
    namespace_id = aws_service_discovery_private_dns_namespace.main.id

    dns_records {
      ttl  = 10
      type = "A"
    }

    routing_policy = "MULTIVALUE"
  }

  health_check_custom_config {
    failure_threshold = 1
  }

  tags = {
    Name        = "\${var.project_name}-\${each.key}-discovery"
    Environment = var.environment
    ManagedBy   = "tsdevstack"
  }
}
`;
}
