/**
 * Generate Job Invoker Lambda code
 *
 * Creates a Node.js Lambda function that:
 * 1. Wakes ECS services if needed (scale to 1)
 * 2. Retrieves job auth secret from Secrets Manager
 * 3. Calls the target service endpoint via CloudMap DNS
 *
 * This Lambda runs in VPC to resolve CloudMap DNS names.
 * EventBridge Scheduler triggers it with { serviceName, path } payload.
 */

export function generateJobInvokerLambdaCode(): string {
  return `// Job Invoker Lambda for scheduled jobs
// Generated by: npx tsdevstack infra:generate

const { ECSClient, UpdateServiceCommand, DescribeServicesCommand } = require('@aws-sdk/client-ecs');
const { SecretsManagerClient, GetSecretValueCommand } = require('@aws-sdk/client-secrets-manager');

const ecs = new ECSClient({});
const secrets = new SecretsManagerClient({});

const CLUSTER = process.env.ECS_CLUSTER;
const SERVICES = process.env.SERVICE_NAMES ? process.env.SERVICE_NAMES.split(',') : [];
const NAMESPACE = process.env.CLOUDMAP_NAMESPACE;
const JOB_SECRET_ARN = process.env.JOB_SECRET_ARN;

exports.handler = async (event) => {
  console.log('Job invocation received:', JSON.stringify(event, null, 2));

  const { serviceName, path } = event;

  if (!serviceName || !path) {
    console.error('Missing serviceName or path in event');
    return {
      statusCode: 400,
      body: JSON.stringify({ error: 'Missing serviceName or path' }),
    };
  }

  try {
    // Ensure services are running
    await ensureServicesRunning();

    // Get job auth secret
    const { SecretString } = await secrets.send(
      new GetSecretValueCommand({ SecretId: JOB_SECRET_ARN })
    );

    if (!SecretString) {
      throw new Error('Failed to retrieve job auth secret');
    }

    // Build URL using CloudMap DNS
    const url = \`http://\${serviceName}.\${NAMESPACE}:8080\${path}\`;
    console.log('Calling:', url);

    // Make HTTP request to service
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Job-Secret': SecretString,
      },
      // 5 minute timeout for long-running jobs
      signal: AbortSignal.timeout(300000),
    });

    const responseText = await response.text();
    console.log('Response status:', response.status);
    console.log('Response body:', responseText.substring(0, 1000));

    if (!response.ok) {
      throw new Error(\`Job failed with status \${response.status}: \${responseText}\`);
    }

    return {
      statusCode: response.status,
      body: responseText,
    };
  } catch (error) {
    console.error('Job invocation failed:', error);
    throw error; // Rethrow to trigger retry policy
  }
};

async function ensureServicesRunning() {
  if (SERVICES.length === 0) {
    console.log('No services to wake');
    return;
  }

  // Check current state
  const { services: ecsServices } = await ecs.send(
    new DescribeServicesCommand({
      cluster: CLUSTER,
      services: SERVICES,
    })
  );

  const needsWakeup = ecsServices?.some((s) => s.runningCount === 0);

  if (!needsWakeup) {
    console.log('All services already running');
    return;
  }

  console.log('Waking up services...');

  // Scale all services to 1
  await Promise.all(
    SERVICES.map((service) =>
      ecs.send(
        new UpdateServiceCommand({
          cluster: CLUSTER,
          service,
          desiredCount: 1,
        })
      )
    )
  );

  // Wait for services to become healthy (max 90 seconds)
  const start = Date.now();
  const maxWait = 90000;

  while (Date.now() - start < maxWait) {
    const { services: updated } = await ecs.send(
      new DescribeServicesCommand({
        cluster: CLUSTER,
        services: SERVICES,
      })
    );

    const allHealthy = updated?.every(
      (s) => s.runningCount > 0 && s.runningCount >= s.desiredCount
    );

    if (allHealthy) {
      console.log('All services healthy');
      return;
    }

    const status = updated?.map((s) => \`\${s.serviceName}: \${s.runningCount}/\${s.desiredCount}\`);
    console.log('Waiting for services:', status?.join(', '));

    await new Promise((r) => setTimeout(r, 2000));
  }

  console.warn('Timeout waiting for services, proceeding anyway...');
}
`;
}
