/**
 * Generate main.tf with Terraform configuration, AWS provider, and S3 backend
 */

import type { AWSInfraConfig } from '../../types/config.ts';

export function generateMainTf(config: AWSInfraConfig): string {
  const { stateBucket, lockTable, environment, region } = config;

  return `# Terraform configuration
# Generated by: npx tsdevstack infra:generate

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }

  backend "s3" {
    bucket         = "${stateBucket}"
    key            = "${environment}/terraform.tfstate"
    region         = "${region}"
    dynamodb_table = "${lockTable}"
    encrypt        = true
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = var.project_name
      Environment = var.environment
      ManagedBy   = "terraform"
    }
  }
}

# Required for CloudFront resources (WAF, ACM)
# CloudFront is global and requires us-east-1 for WAF and certificates
provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"

  default_tags {
    tags = {
      Project     = var.project_name
      Environment = var.environment
      ManagedBy   = "terraform"
    }
  }
}

# =============================================================================
# Data Sources
# =============================================================================

# Current AWS account ID (used for KMS key policies)
data "aws_caller_identity" "current" {}
`;
}
