/**
 * Generate storage.tf with S3 buckets for object storage
 *
 * Creates:
 * - S3 buckets with for_each over configured bucket names
 * - Public access block (all blocked — presigned URLs are the security boundary)
 * - CORS configuration (allow all origins — presigned URLs control access)
 * - Versioning enabled
 * - Lifecycle configuration (expire non-current versions after 7 days)
 * - IAM policy on all ECS task roles for S3 access
 *
 * force_destroy = true allows Terraform to delete non-empty buckets.
 * WARNING: This is permanent — all objects and versions are deleted, NOT recoverable.
 */

import type { AWSInfraConfig } from '../../types/config.ts';

export function generateS3StorageTf(config: AWSInfraConfig): string {
  if (config.storageBuckets.length === 0) {
    return '';
  }

  const bucketMap = config.storageBuckets
    .map(
      (b) =>
        `    "${b}" = "${config.projectName}-${b}-${config.environment}-${config.accountId}"`,
    )
    .join('\n');

  return `# S3 Object Storage Buckets
# Generated by: npx tsdevstack infra:generate

locals {
  storage_buckets = {
${bucketMap}
  }
}

# =============================================================================
# S3 Buckets
# =============================================================================

resource "aws_s3_bucket" "storage" {
  for_each = local.storage_buckets

  bucket        = each.value
  force_destroy = true

  tags = { Name = each.value }
}

# =============================================================================
# Public Access Block (all blocked)
# Presigned URLs are the security boundary, not public access settings
# =============================================================================

resource "aws_s3_bucket_public_access_block" "storage" {
  for_each = local.storage_buckets

  bucket = aws_s3_bucket.storage[each.key].id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# =============================================================================
# CORS Configuration
# Allow all origins — presigned URLs control access, not CORS
# =============================================================================

resource "aws_s3_bucket_cors_configuration" "storage" {
  for_each = local.storage_buckets

  bucket = aws_s3_bucket.storage[each.key].id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "PUT", "POST", "DELETE", "HEAD"]
    allowed_origins = ["*"]
    expose_headers  = ["ETag", "Content-Length", "Content-Type"]
    max_age_seconds = 3600
  }
}

# =============================================================================
# Versioning
# =============================================================================

resource "aws_s3_bucket_versioning" "storage" {
  for_each = local.storage_buckets

  bucket = aws_s3_bucket.storage[each.key].id

  versioning_configuration {
    status = "Enabled"
  }
}

# =============================================================================
# Lifecycle — expire non-current versions after 7 days
# =============================================================================

resource "aws_s3_bucket_lifecycle_configuration" "storage" {
  for_each = local.storage_buckets

  bucket = aws_s3_bucket.storage[each.key].id

  rule {
    id     = "expire-noncurrent"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = 7
    }
  }

  depends_on = [aws_s3_bucket_versioning.storage]
}

# =============================================================================
# IAM — grant S3 access to all ECS task roles
# =============================================================================

resource "aws_iam_role_policy" "task_s3_storage" {
  for_each = var.services

  name = "s3-storage-access"
  role = aws_iam_role.task[each.key].id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:ListBucket"
      ]
      Resource = flatten([
        for bucket in aws_s3_bucket.storage : [
          bucket.arn,
          "\${bucket.arn}/*"
        ]
      ])
    }]
  })
}

# =============================================================================
# Output
# =============================================================================

output "storage_buckets" {
  description = "Storage bucket names and metadata"
  value = {
    for key, bucket in aws_s3_bucket.storage :
    key => {
      name   = bucket.id
      arn    = bucket.arn
      region = bucket.region
    }
  }
}
`;
}
