import { describe, it, expect } from '@rstest/core';
import { generateCloudfrontTf } from './generate-cloudfront-tf';

describe('generateCloudfrontTf', () => {
  describe('CloudFront distribution', () => {
    it('should create CloudFront distribution', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('resource "aws_cloudfront_distribution" "main"');
    });

    it('should be enabled', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('enabled      = true');
    });

    it('should attach WAF Web ACL', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('web_acl_id   = aws_wafv2_web_acl.main.arn');
    });

    it('should use PriceClass_100 for cost optimization', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('price_class  = "PriceClass_100"');
    });

    it('should support HTTP/2 and HTTP/3', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('http_version = "http2and3"');
    });
  });

  describe('ALB origin', () => {
    it('should use ALB as origin', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('domain_name = aws_lb.main.dns_name');
      expect(result).toContain('origin_id   = "alb"');
    });

    it('should use HTTPS only protocol policy', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('origin_protocol_policy = "https-only"');
    });

    it('should use TLS 1.2', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('origin_ssl_protocols   = ["TLSv1.2"]');
    });

    it('should send X-Origin-Verify header for ALB protection', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('custom_header {');
      expect(result).toContain('name  = "X-Origin-Verify"');
      expect(result).toContain('random_password.origin_verify_secret.result');
    });
  });

  describe('default cache behavior', () => {
    it('should redirect HTTP to HTTPS', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('viewer_protocol_policy = "redirect-to-https"');
    });

    it('should allow all HTTP methods', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain(
        'allowed_methods        = ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]',
      );
    });

    it('should use CachingDisabled policy for API', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('4135ea2d-6df8-44a3-9df3-4b5a84be39ad');
    });

    it('should use AllViewer origin request policy', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('216adef6-5c7f-47e4-b989-5492eafa07d3');
    });
  });

  describe('viewer certificate', () => {
    it('should use ACM certificate when base_domain is set', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain(
        'acm_certificate_arn      = local.cloudfront_certificate_arn',
      );
      expect(result).toContain('ssl_support_method       = "sni-only"');
    });

    it('should use CloudFront default cert when no domain', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('cloudfront_default_certificate = true');
    });

    it('should use TLS 1.2 minimum protocol', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('minimum_protocol_version = "TLSv1.2_2021"');
    });
  });

  describe('geo restrictions', () => {
    it('should have no geo restrictions', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('restriction_type = "none"');
    });
  });

  describe('aliases', () => {
    it('should use api_domain as alias when base_domain is set', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain(
        'aliases      = var.base_domain != "" ? [local.api_domain] : []',
      );
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateCloudfrontTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateCloudfrontTf();
      expect(result).toMatchSnapshot();
    });
  });
});
