/**
 * Generate cloudtrail.tf for AWS CloudTrail audit logging
 *
 * Creates:
 * - S3 bucket for CloudTrail log storage (encrypted, versioned)
 * - KMS key for CloudTrail encryption
 * - CloudTrail trail with all management events
 *
 * CloudTrail provides API-level audit trail required for:
 * - SOC 2 CC7.1: Detect and respond to anomalies
 * - GDPR Art. 32: Accountability audit trail
 * - ISO 27001 A.12.4.1: Event logging
 */

export function generateCloudtrailTf(): string {
  return `# CloudTrail Audit Logging
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# KMS Key for CloudTrail Encryption
# =============================================================================

resource "aws_kms_key" "cloudtrail" {
  description             = "\${var.project_name} CloudTrail encryption key"
  deletion_window_in_days = 7
  enable_key_rotation     = true

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "EnableIAMUserPermissions"
        Effect = "Allow"
        Principal = {
          AWS = "arn:aws:iam::\${data.aws_caller_identity.current.account_id}:root"
        }
        Action   = "kms:*"
        Resource = "*"
      },
      {
        Sid    = "AllowCloudTrailEncrypt"
        Effect = "Allow"
        Principal = {
          Service = "cloudtrail.amazonaws.com"
        }
        Action = [
          "kms:GenerateDataKey*",
          "kms:DescribeKey"
        ]
        Resource = "*"
        Condition = {
          StringLike = {
            "kms:EncryptionContext:aws:cloudtrail:arn" = "arn:aws:cloudtrail:*:\${data.aws_caller_identity.current.account_id}:trail/*"
          }
        }
      },
      {
        Sid    = "AllowCloudTrailDecrypt"
        Effect = "Allow"
        Principal = {
          AWS = "arn:aws:iam::\${data.aws_caller_identity.current.account_id}:root"
        }
        Action = "kms:Decrypt"
        Resource = "*"
        Condition = {
          "Null" = {
            "kms:EncryptionContext:aws:cloudtrail:arn" = "false"
          }
        }
      }
    ]
  })

  tags = { Name = "\${var.project_name}-cloudtrail-kms" }
}

resource "aws_kms_alias" "cloudtrail" {
  name          = "alias/\${var.project_name}-cloudtrail"
  target_key_id = aws_kms_key.cloudtrail.key_id
}

# =============================================================================
# S3 Bucket for CloudTrail Logs
# =============================================================================

resource "aws_s3_bucket" "cloudtrail" {
  bucket = "\${var.project_name}-cloudtrail-\${data.aws_caller_identity.current.account_id}"

  tags = { Name = "\${var.project_name}-cloudtrail-logs" }
}

resource "aws_s3_bucket_versioning" "cloudtrail" {
  bucket = aws_s3_bucket.cloudtrail.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "cloudtrail" {
  bucket = aws_s3_bucket.cloudtrail.id

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.cloudtrail.arn
      sse_algorithm     = "aws:kms"
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_public_access_block" "cloudtrail" {
  bucket = aws_s3_bucket.cloudtrail.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_lifecycle_configuration" "cloudtrail" {
  bucket = aws_s3_bucket.cloudtrail.id

  rule {
    id     = "expire-old-logs"
    status = "Enabled"

    filter {}  # Apply to all objects

    expiration {
      days = 90
    }

    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }
}

resource "aws_s3_bucket_policy" "cloudtrail" {
  bucket = aws_s3_bucket.cloudtrail.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AWSCloudTrailAclCheck"
        Effect = "Allow"
        Principal = {
          Service = "cloudtrail.amazonaws.com"
        }
        Action   = "s3:GetBucketAcl"
        Resource = aws_s3_bucket.cloudtrail.arn
        Condition = {
          StringEquals = {
            "AWS:SourceArn" = "arn:aws:cloudtrail:\${var.aws_region}:\${data.aws_caller_identity.current.account_id}:trail/\${var.project_name}-trail"
          }
        }
      },
      {
        Sid    = "AWSCloudTrailWrite"
        Effect = "Allow"
        Principal = {
          Service = "cloudtrail.amazonaws.com"
        }
        Action   = "s3:PutObject"
        Resource = "\${aws_s3_bucket.cloudtrail.arn}/AWSLogs/\${data.aws_caller_identity.current.account_id}/*"
        Condition = {
          StringEquals = {
            "s3:x-amz-acl"  = "bucket-owner-full-control"
            "AWS:SourceArn" = "arn:aws:cloudtrail:\${var.aws_region}:\${data.aws_caller_identity.current.account_id}:trail/\${var.project_name}-trail"
          }
        }
      }
    ]
  })
}

# =============================================================================
# CloudTrail
# =============================================================================

resource "aws_cloudtrail" "main" {
  name                          = "\${var.project_name}-trail"
  s3_bucket_name                = aws_s3_bucket.cloudtrail.id
  kms_key_id                    = aws_kms_key.cloudtrail.arn
  include_global_service_events = true
  is_multi_region_trail         = false
  enable_log_file_validation    = true

  # Log all management events (API calls)
  event_selector {
    read_write_type           = "All"
    include_management_events = true
  }

  tags = { Name = "\${var.project_name}-cloudtrail" }

  depends_on = [aws_s3_bucket_policy.cloudtrail]
}

# =============================================================================
# Outputs
# =============================================================================

output "cloudtrail_arn" {
  description = "ARN of the CloudTrail trail"
  value       = aws_cloudtrail.main.arn
}

output "cloudtrail_s3_bucket" {
  description = "S3 bucket for CloudTrail logs"
  value       = aws_s3_bucket.cloudtrail.id
}

output "cloudtrail_kms_key_arn" {
  description = "ARN of the KMS key for CloudTrail encryption"
  value       = aws_kms_key.cloudtrail.arn
}
`;
}
