import { describe, it, expect } from '@rstest/core';
import { generateVpcFlowLogsTf } from './generate-vpc-flow-logs-tf';

describe('generateVpcFlowLogsTf', () => {
  describe('IAM role', () => {
    it('should create an IAM role for VPC Flow Logs', () => {
      const result = generateVpcFlowLogsTf();
      expect(result).toContain('resource "aws_iam_role" "vpc_flow_logs"');
    });

    it('should allow vpc-flow-logs service to assume role', () => {
      const result = generateVpcFlowLogsTf();
      expect(result).toContain('vpc-flow-logs.amazonaws.com');
    });

    it('should grant CloudWatch Logs write permissions', () => {
      const result = generateVpcFlowLogsTf();
      expect(result).toContain('logs:CreateLogStream');
      expect(result).toContain('logs:PutLogEvents');
    });
  });

  describe('CloudWatch Log Group', () => {
    it('should create a log group for flow logs', () => {
      const result = generateVpcFlowLogsTf();
      expect(result).toContain(
        'resource "aws_cloudwatch_log_group" "vpc_flow_logs"',
      );
    });

    it('should set 30-day retention', () => {
      const result = generateVpcFlowLogsTf();
      expect(result).toContain('retention_in_days = 30');
    });

    it('should encrypt with KMS', () => {
      const result = generateVpcFlowLogsTf();
      expect(result).toContain('kms_key_id        = aws_kms_key.logs.arn');
    });
  });

  describe('VPC Flow Log resource', () => {
    it('should create a flow log for the VPC', () => {
      const result = generateVpcFlowLogsTf();
      expect(result).toContain('resource "aws_flow_log" "main"');
    });

    it('should capture all traffic', () => {
      const result = generateVpcFlowLogsTf();
      expect(result).toContain('traffic_type             = "ALL"');
    });

    it('should send logs to CloudWatch', () => {
      const result = generateVpcFlowLogsTf();
      expect(result).toContain('log_destination_type     = "cloud-watch-logs"');
    });

    it('should aggregate at 60-second intervals', () => {
      const result = generateVpcFlowLogsTf();
      expect(result).toContain('max_aggregation_interval = 60');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateVpcFlowLogsTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateVpcFlowLogsTf();
      expect(result).toMatchSnapshot();
    });
  });
});
