import { describe, it, expect } from '@rstest/core';
import { generateJobInvokerLambdaCode } from './generate-job-invoker-lambda-code';

describe('generateJobInvokerLambdaCode', () => {
  describe('imports', () => {
    it('should not import the ECS client (no wake-up step)', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).not.toContain('@aws-sdk/client-ecs');
      expect(result).not.toContain('ECSClient');
      expect(result).not.toContain('UpdateServiceCommand');
      expect(result).not.toContain('DescribeServicesCommand');
    });

    it('should import Secrets Manager client', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain('SecretsManagerClient');
      expect(result).toContain('GetSecretValueCommand');
    });
  });

  describe('environment variables', () => {
    it('should not read ECS_CLUSTER or SERVICE_NAMES', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).not.toContain('ECS_CLUSTER');
      expect(result).not.toContain('SERVICE_NAMES');
    });

    it('should read CLOUDMAP_NAMESPACE from environment', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain(
        'const NAMESPACE = process.env.CLOUDMAP_NAMESPACE;',
      );
    });

    it('should read JOB_SECRET_ARN from environment', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain(
        'const JOB_SECRET_ARN = process.env.JOB_SECRET_ARN;',
      );
    });
  });

  describe('handler', () => {
    it('should extract serviceName and path from event', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain('const { serviceName, path } = event;');
    });

    it('should validate required parameters', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain('if (!serviceName || !path)');
      expect(result).toContain('Missing serviceName or path');
    });
  });

  describe('no service wake-up (AWS has no scale-to-zero)', () => {
    it('should not wake or scale services before invoking', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).not.toContain('ensureServicesRunning');
      expect(result).not.toContain('desiredCount');
      expect(result).not.toContain('maxWait');
    });
  });

  describe('job invocation', () => {
    it('should build URL using CloudMap DNS', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain(
        '`http://${serviceName}.${NAMESPACE}:8080${path}`',
      );
    });

    it('should use POST method', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain("method: 'POST'");
    });

    it('should include X-Job-Secret header', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain("'X-Job-Secret': SecretString");
    });

    it('should have 5 minute timeout', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain('signal: AbortSignal.timeout(300000)');
    });
  });

  describe('secrets management', () => {
    it('should retrieve job auth secret', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain(
        'GetSecretValueCommand({ SecretId: JOB_SECRET_ARN })',
      );
    });

    it('should throw error if secret not found', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain('Failed to retrieve job auth secret');
    });
  });

  describe('error handling', () => {
    it('should check response ok status', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain('if (!response.ok)');
    });

    it('should rethrow errors for retry', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain(
        'throw error; // Rethrow to trigger retry policy',
      );
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateJobInvokerLambdaCode();
      expect(result).toMatchSnapshot();
    });
  });
});
