/**
 * Generate outputs.tf with stack outputs for AWS
 */

import { toTerraformId } from '../../utils/terraform/to-terraform-id.ts';

export interface OutputsConfig {
  /** SPA services to generate bucket outputs for */
  spaServices?: Array<{ name: string }>;
}

export function generateOutputsTf(config: OutputsConfig = {}): string {
  const { spaServices = [] } = config;

  const spaBucketOutputs = spaServices
    .map(
      (s) => `
output "${toTerraformId(s.name)}_spa_bucket" {
  description = "S3 bucket for ${s.name} SPA deployment"
  value       = aws_s3_bucket.spa["${s.name}"].id
}

output "${toTerraformId(s.name)}_cloudfront_id" {
  description = "CloudFront distribution ID for ${s.name} SPA"
  value       = aws_cloudfront_distribution.spa["${s.name}"].id
}`,
    )
    .join('');

  return `# Stack outputs
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# Core Info
# =============================================================================

output "aws_region" {
  description = "AWS region"
  value       = var.aws_region
}

output "aws_account_id" {
  description = "AWS account ID"
  value       = var.aws_account_id
}

output "project_name" {
  description = "Project name"
  value       = var.project_name
}

output "environment" {
  description = "Environment name"
  value       = var.environment
}

# =============================================================================
# ECR (for CLI deployments)
# =============================================================================

output "ecr_repository_url" {
  description = "Base ECR repository URL (used by CLI for image pushes)"
  value       = "\${var.aws_account_id}.dkr.ecr.\${var.aws_region}.amazonaws.com/\${var.project_name}"
}

# =============================================================================
# ECS (for CLI deployments)
# =============================================================================

output "ecs_cluster_name" {
  description = "ECS cluster name (used by CLI for service updates)"
  value       = aws_ecs_cluster.main.name
}

# =============================================================================
# Wake-up Lambda
# =============================================================================

output "wakeup_lambda_url" {
  description = "Lambda Function URL for wake-up (used by Kong post-function plugin)"
  value       = aws_lambda_function_url.wakeup.function_url
}

output "wakeup_secret" {
  description = "Secret for X-Wake-Secret header validation (used by Kong post-function plugin)"
  value       = random_password.wakeup_secret.result
  sensitive   = true
}

# =============================================================================
# Redis (ElastiCache)
# =============================================================================

output "redis_host" {
  description = "Redis primary endpoint address"
  value       = aws_elasticache_replication_group.main.primary_endpoint_address
}

output "redis_port" {
  description = "Redis port"
  value       = aws_elasticache_replication_group.main.port
}

output "redis_auth_token" {
  description = "Redis auth token (synced to REDIS_PASSWORD secret)"
  value       = random_password.redis_auth.result
  sensitive   = true
}

# =============================================================================
# Database (RDS)
# =============================================================================

output "database_host" {
  description = "RDS PostgreSQL endpoint address (for DATABASE_URL)"
  value       = aws_db_instance.main.address
}

output "database_port" {
  description = "RDS PostgreSQL port"
  value       = aws_db_instance.main.port
}

# =============================================================================
# DB-Init (database initialization task)
# =============================================================================

output "db_init_task_arn" {
  description = "ARN of the db-init ECS task definition"
  value       = aws_ecs_task_definition.db_init.arn
}

output "db_init_ecr_url" {
  description = "ECR repository URL for db-init image"
  value       = aws_ecr_repository.db_init.repository_url
}

# =============================================================================
# DB-Delete (database deletion task)
# =============================================================================

output "db_delete_ecr_url" {
  description = "ECR repository URL for db-delete image"
  value       = aws_ecr_repository.db_delete.repository_url
}

# =============================================================================
# VPC/Network (for CLI task execution)
# =============================================================================

output "vpc_id" {
  description = "VPC ID"
  value       = aws_vpc.main.id
}

output "private_subnet_ids" {
  description = "Private subnet IDs (for ECS tasks)"
  value       = jsonencode(aws_subnet.private[*].id)
}

output "ecs_security_group_id" {
  description = "ECS security group ID"
  value       = aws_security_group.ecs.id
}

# =============================================================================
# IAM Roles (for CLI task execution)
# =============================================================================

output "ecs_execution_role_arn" {
  description = "ECS task execution role ARN"
  value       = aws_iam_role.ecs_execution.arn
}

output "ecs_task_role_arns" {
  description = "ECS task role ARNs per service"
  value       = jsonencode({ for k, v in aws_iam_role.task : k => v.arn })
}

# =============================================================================
# API URL (for SPA builds and Next.js)
# =============================================================================

output "api_url" {
  description = "API URL (custom domain if set, otherwise ALB DNS)"
  value       = var.base_domain != "" ? "https://\${local.api_domain}" : "https://\${aws_lb.main.dns_name}"
}

# =============================================================================
# ALB Internal DNS (for Kong upstream failover)
# =============================================================================

output "alb_internal_dns" {
  description = "ALB DNS name for Kong internal routing (used in Kong upstreams)"
  value       = aws_lb.main.dns_name
}

# =============================================================================
# Cloud Map (service discovery for service-to-service calls)
# =============================================================================

output "cloudmap_namespace" {
  description = "Cloud Map namespace for service discovery (e.g., auth-service.tsdevstack.local)"
  value       = aws_service_discovery_private_dns_namespace.main.name
}
${spaBucketOutputs}`;
}
