import { describe, it, expect } from '@rstest/core';
import { generateKmsTf } from './generate-kms-tf';

describe('generateKmsTf', () => {
  describe('KMS key', () => {
    it('should create a KMS key for CloudWatch Logs', () => {
      const result = generateKmsTf();
      expect(result).toContain('resource "aws_kms_key" "logs"');
    });

    it('should enable key rotation', () => {
      const result = generateKmsTf();
      expect(result).toContain('enable_key_rotation     = true');
    });

    it('should set 7-day deletion window', () => {
      const result = generateKmsTf();
      expect(result).toContain('deletion_window_in_days = 7');
    });

    it('should allow CloudWatch Logs service to use the key', () => {
      const result = generateKmsTf();
      expect(result).toContain('AllowCloudWatchLogs');
      expect(result).toContain('logs.${var.aws_region}.amazonaws.com');
    });

    it('should allow root account full KMS access', () => {
      const result = generateKmsTf();
      expect(result).toContain('EnableIAMUserPermissions');
      expect(result).toContain('"kms:*"');
    });
  });

  describe('KMS alias', () => {
    it('should create a readable alias', () => {
      const result = generateKmsTf();
      expect(result).toContain('resource "aws_kms_alias" "logs"');
      expect(result).toContain('alias/${var.project_name}-logs');
    });
  });

  describe('outputs', () => {
    it('should output KMS key ARN', () => {
      const result = generateKmsTf();
      expect(result).toContain('output "logs_kms_key_arn"');
    });

    it('should output KMS key ID', () => {
      const result = generateKmsTf();
      expect(result).toContain('output "logs_kms_key_id"');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateKmsTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateKmsTf();
      expect(result).toMatchSnapshot();
    });
  });
});
