/**
 * Generate cloudfront.tf with CloudFront distribution for API
 *
 * CloudFront provides CDN for the API with WAF protection at edge.
 * WAF is CLOUDFRONT scope in us-east-1, attached to all CloudFront distributions.
 *
 * NOTE: Scale-to-zero wake-up is handled by Kong upstream failover,
 * NOT CloudFront origin groups. CloudFront origin groups don't support
 * POST/PUT/DELETE failover - only GET/HEAD/OPTIONS.
 */

export function generateCloudfrontTf(): string {
  return `# CloudFront Distribution (API)
# Generated by: npx tsdevstack infra:generate
#
# CDN with WAF protection at edge (CLOUDFRONT scope, us-east-1).
# Scale-to-zero wake-up is handled by Kong upstream failover.
# CloudFront origin groups don't support POST/PUT/DELETE failover.

# =============================================================================
# CloudFront Distribution
# =============================================================================

resource "aws_cloudfront_distribution" "main" {
  enabled      = true
  web_acl_id   = aws_wafv2_web_acl.main.arn
  # API domain derived from base_domain (e.g., api.example.com)
  # Wildcard cert covers *.example.com including api.example.com
  aliases      = var.base_domain != "" ? [local.api_domain] : []
  price_class  = "PriceClass_100"
  http_version = "http2and3"

  # Origin: ALB (Kong handles all routing and failover)
  origin {
    domain_name = aws_lb.main.dns_name
    origin_id   = "alb"

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }

    # Origin verification header - ALB validates this to prevent direct access
    # Requests without this header get 403 at ALB level
    custom_header {
      name  = "X-Origin-Verify"
      value = random_password.origin_verify_secret.result
    }
  }

  default_cache_behavior {
    target_origin_id       = "alb"
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]
    cached_methods         = ["GET", "HEAD"]

    # No caching for API - all requests go to origin
    cache_policy_id            = "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"  # CachingDisabled
    origin_request_policy_id   = "216adef6-5c7f-47e4-b989-5492eafa07d3"  # AllViewer
    response_headers_policy_id = aws_cloudfront_response_headers_policy.security_headers.id
  }

  # Use ACM cert if base_domain is set, otherwise CloudFront default cert
  dynamic "viewer_certificate" {
    for_each = var.base_domain != "" ? [1] : []
    content {
      acm_certificate_arn      = local.cloudfront_certificate_arn
      ssl_support_method       = "sni-only"
      minimum_protocol_version = "TLSv1.2_2021"
    }
  }

  dynamic "viewer_certificate" {
    for_each = var.base_domain == "" ? [1] : []
    content {
      cloudfront_default_certificate = true
    }
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  tags = { Name = "\${var.project_name}-cloudfront" }
}
`;
}
