/**
 * Generate iam.tf with IAM roles and policies for ECS
 *
 * Roles created:
 * - ECS Task Execution Role (shared): Pull images, fetch secrets at startup
 * - ECS Task Roles (per service): Runtime permissions for running containers
 *
 * Note: Lambda roles are defined in their respective terraform files
 * (wakeup-lambda.tf, eventbridge.tf) to keep them colocated with their functions.
 */

export function generateIamTf(): string {
  return `# IAM Roles and Policies
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# ECS Task Execution Role (Shared)
# Used at container startup to pull images and fetch secrets
# =============================================================================

resource "aws_iam_role" "ecs_execution" {
  name = "\${var.project_name}-ecs-execution"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
    }]
  })

  tags = { Name = "\${var.project_name}-ecs-execution" }
}

resource "aws_iam_role_policy_attachment" "ecs_execution" {
  role       = aws_iam_role.ecs_execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

resource "aws_iam_role_policy" "ecs_execution_secrets" {
  name = "secrets-access"
  role = aws_iam_role.ecs_execution.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["secretsmanager:GetSecretValue"]
      Resource = "arn:aws:secretsmanager:\${var.aws_region}:\${var.aws_account_id}:secret:\${var.project_name}-*"
    }]
  })
}

# =============================================================================
# ECS Task Roles (Per Service)
# Runtime permissions for what the running container can do
# =============================================================================

resource "aws_iam_role" "task" {
  for_each = var.services

  name = "\${var.project_name}-\${each.key}-task"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
    }]
  })

  tags = { Name = "\${var.project_name}-\${each.key}-task" }
}

resource "aws_iam_role_policy" "task_secrets" {
  for_each = var.services

  name = "secrets-access"
  role = aws_iam_role.task[each.key].id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = ["secretsmanager:GetSecretValue"]
      Resource = [
        "arn:aws:secretsmanager:\${var.aws_region}:\${var.aws_account_id}:secret:\${var.project_name}-shared-*",
        "arn:aws:secretsmanager:\${var.aws_region}:\${var.aws_account_id}:secret:\${var.project_name}-\${each.key}-*"
      ]
    }]
  })
}
`;
}
