import { describe, it, expect } from '@rstest/core';
import { generateRedisTf } from './generate-redis-tf';

describe('generateRedisTf', () => {
  describe('subnet group', () => {
    it('should create elasticache subnet group', () => {
      const result = generateRedisTf();
      expect(result).toContain(
        'resource "aws_elasticache_subnet_group" "main"',
      );
    });

    it('should use private subnets', () => {
      const result = generateRedisTf();
      expect(result).toContain('subnet_ids  = aws_subnet.private[*].id');
    });

    it('should use project name in subnet group name', () => {
      const result = generateRedisTf();
      expect(result).toContain('name        = "${var.project_name}-redis"');
    });
  });

  describe('parameter group', () => {
    it('should create parameter group', () => {
      const result = generateRedisTf();
      expect(result).toContain(
        'resource "aws_elasticache_parameter_group" "main"',
      );
    });

    it('should use redis7 family', () => {
      const result = generateRedisTf();
      expect(result).toContain('family      = "redis7"');
    });

    it('should set noeviction policy for BullMQ', () => {
      const result = generateRedisTf();
      expect(result).toContain('name  = "maxmemory-policy"');
      expect(result).toContain('value = "noeviction"');
    });
  });

  describe('auth token', () => {
    it('should create random auth token', () => {
      const result = generateRedisTf();
      expect(result).toContain('resource "random_password" "redis_auth"');
    });

    it('should generate 32 character password', () => {
      const result = generateRedisTf();
      expect(result).toContain('length  = 32');
    });

    it('should not use special characters', () => {
      const result = generateRedisTf();
      expect(result).toContain('special = false');
    });
  });

  describe('replication group', () => {
    it('should create replication group', () => {
      const result = generateRedisTf();
      expect(result).toContain(
        'resource "aws_elasticache_replication_group" "main"',
      );
    });

    it('should use single node for BullMQ compatibility', () => {
      const result = generateRedisTf();
      expect(result).toContain('num_cache_clusters   = 1');
    });

    it('should use redis engine', () => {
      const result = generateRedisTf();
      expect(result).toContain('engine               = "redis"');
    });

    it('should use redis version 7.0', () => {
      const result = generateRedisTf();
      expect(result).toContain('engine_version       = "7.0"');
    });

    it('should use port 6379', () => {
      const result = generateRedisTf();
      expect(result).toContain('port                 = 6379');
    });

    it('should use node type variable', () => {
      const result = generateRedisTf();
      expect(result).toContain('node_type            = var.redis_node_type');
    });

    it('should enable at-rest encryption', () => {
      const result = generateRedisTf();
      expect(result).toContain('at_rest_encryption_enabled = true');
    });

    it('should enable transit encryption (TLS)', () => {
      const result = generateRedisTf();
      expect(result).toContain('transit_encryption_enabled = true');
    });

    it('should use auth token', () => {
      const result = generateRedisTf();
      expect(result).toContain(
        'auth_token                 = random_password.redis_auth.result',
      );
    });

    it('should disable automatic failover for single node', () => {
      const result = generateRedisTf();
      expect(result).toContain('automatic_failover_enabled = false');
    });

    it('should disable multi-az for single node', () => {
      const result = generateRedisTf();
      expect(result).toContain('multi_az_enabled           = false');
    });

    it('should use redis security group', () => {
      const result = generateRedisTf();
      expect(result).toContain(
        'security_group_ids   = [aws_security_group.redis.id]',
      );
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateRedisTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateRedisTf();
      expect(result).toMatchSnapshot();
    });
  });
});
