/**
 * Generate cloudfront-nextjs.tf for Next.js services
 *
 * CloudFront distributions for Next.js services behind the ALB.
 * Origin is the ALB (same as API CloudFront), with host-based routing
 * differentiating Next.js from Kong traffic.
 * WAF provides edge protection (CLOUDFRONT scope, us-east-1).
 *
 * Single-phase deploy: ALB is a Terraform resource, so its DNS name
 * is known at plan time. No origin detection needed.
 */

export function generateNextjsCloudfrontTf(): string {
  return `# CloudFront for Next.js Services
# Generated by: npx tsdevstack infra:generate
#
# Origin: ALB with host-based routing (Next.js domains → Next.js target groups)
# Uses shared origin_verify_secret (same as API CloudFront)

# =============================================================================
# Cache Policies (always created when nextjs_services configured)
# =============================================================================

# Dynamic content - respect origin headers, forward cookies for auth
resource "aws_cloudfront_cache_policy" "nextjs_dynamic" {
  count = length(var.nextjs_services) > 0 ? 1 : 0

  name        = "\${var.project_name}-\${var.environment}-nextjs-dynamic"
  comment     = "Next.js dynamic content - respect origin cache headers"
  default_ttl = 0
  max_ttl     = 31536000
  min_ttl     = 0

  parameters_in_cache_key_and_forwarded_to_origin {
    headers_config {
      header_behavior = "whitelist"
      headers {
        items = ["Authorization"]
      }
    }
    cookies_config {
      cookie_behavior = "none"
    }
    query_strings_config {
      query_string_behavior = "all"
    }
  }
}

# Image optimization - cache with query params (w, q, etc.)
resource "aws_cloudfront_cache_policy" "nextjs_images" {
  count = length(var.nextjs_services) > 0 ? 1 : 0

  name        = "\${var.project_name}-\${var.environment}-nextjs-images"
  comment     = "Next.js image optimization"
  default_ttl = 86400
  max_ttl     = 31536000
  min_ttl     = 0

  parameters_in_cache_key_and_forwarded_to_origin {
    headers_config {
      header_behavior = "none"
    }
    cookies_config {
      cookie_behavior = "none"
    }
    query_strings_config {
      query_string_behavior = "all"
    }
  }
}

# =============================================================================
# Origin Request Policy
# =============================================================================

# Forward cookies to Next.js for auth
resource "aws_cloudfront_origin_request_policy" "nextjs_forward_cookies" {
  count = length(var.nextjs_services) > 0 ? 1 : 0

  name    = "\${var.project_name}-\${var.environment}-nextjs-cookies"
  comment = "Forward auth cookies to Next.js"

  headers_config {
    header_behavior = "whitelist"
    headers {
      items = ["Host", "Origin", "Access-Control-Request-Method", "Access-Control-Request-Headers"]
    }
  }

  cookies_config {
    cookie_behavior = "all"
  }

  query_strings_config {
    query_string_behavior = "all"
  }
}

# =============================================================================
# CloudFront Distributions
# =============================================================================

resource "aws_cloudfront_distribution" "nextjs" {
  for_each = var.nextjs_services

  enabled         = true
  web_acl_id      = aws_wafv2_web_acl.main.arn
  is_ipv6_enabled = true
  comment         = "\${var.project_name}-\${var.environment}-\${each.key}-cdn"
  aliases         = var.base_domain != "" ? [each.value.domain] : []

  origin {
    domain_name = aws_lb.main.dns_name
    origin_id   = "alb"

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }

    # Origin verification header - ALB listener rule validates this
    custom_header {
      name  = "X-Origin-Verify"
      value = random_password.origin_verify_secret.result
    }
  }

  # Default behavior - dynamic content (HTML pages, API routes)
  default_cache_behavior {
    target_origin_id       = "alb"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    allowed_methods = ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]
    cached_methods  = ["GET", "HEAD"]

    cache_policy_id            = aws_cloudfront_cache_policy.nextjs_dynamic[0].id
    origin_request_policy_id   = aws_cloudfront_origin_request_policy.nextjs_forward_cookies[0].id
    response_headers_policy_id = aws_cloudfront_response_headers_policy.security_headers.id
  }

  # Static assets - immutable, cache forever
  ordered_cache_behavior {
    path_pattern           = "/_next/static/*"
    target_origin_id       = "alb"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    allowed_methods = ["GET", "HEAD"]
    cached_methods  = ["GET", "HEAD"]

    # CachingOptimized - 1 year TTL (AWS managed policy)
    cache_policy_id = "658327ea-f89d-4fab-a63d-7e88639e58f6"
  }

  # Image optimization
  ordered_cache_behavior {
    path_pattern           = "/_next/image/*"
    target_origin_id       = "alb"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    allowed_methods = ["GET", "HEAD"]
    cached_methods  = ["GET", "HEAD"]

    cache_policy_id          = aws_cloudfront_cache_policy.nextjs_images[0].id
    origin_request_policy_id = aws_cloudfront_origin_request_policy.nextjs_forward_cookies[0].id
  }

  # Data fetching (ISR/SSG JSON)
  ordered_cache_behavior {
    path_pattern           = "/_next/data/*"
    target_origin_id       = "alb"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    allowed_methods = ["GET", "HEAD"]
    cached_methods  = ["GET", "HEAD"]

    cache_policy_id          = aws_cloudfront_cache_policy.nextjs_dynamic[0].id
    origin_request_policy_id = aws_cloudfront_origin_request_policy.nextjs_forward_cookies[0].id
  }

  logging_config {
    bucket          = aws_s3_bucket.cloudfront_logs.bucket_domain_name
    prefix          = "nextjs/\${each.key}/"
    include_cookies = false
  }

  # SSL Certificate (us-east-1 CloudFront certificate)
  viewer_certificate {
    acm_certificate_arn            = var.base_domain != "" ? local.cloudfront_certificate_arn : null
    ssl_support_method             = var.base_domain != "" ? "sni-only" : null
    minimum_protocol_version       = "TLSv1.2_2021"
    cloudfront_default_certificate = var.base_domain == ""
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  tags = {
    Name        = "\${var.project_name}-\${var.environment}-\${each.key}-cdn"
    Environment = var.environment
    ManagedBy   = "tsdevstack"
  }
}

# =============================================================================
# Route 53 A Records for Next.js
# =============================================================================

resource "aws_route53_record" "nextjs" {
  for_each = var.base_domain != "" ? var.nextjs_services : {}

  zone_id = data.aws_route53_zone.main[0].zone_id
  name    = each.value.domain
  type    = "A"

  alias {
    name                   = aws_cloudfront_distribution.nextjs[each.key].domain_name
    zone_id                = aws_cloudfront_distribution.nextjs[each.key].hosted_zone_id
    evaluate_target_health = false
  }
}

# =============================================================================
# Outputs
# =============================================================================

output "nextjs_cloudfront_domains" {
  description = "CloudFront distribution domains for Next.js"
  value = {
    for k, v in aws_cloudfront_distribution.nextjs : k => v.domain_name
  }
}

output "nextjs_cloudfront_distribution_ids" {
  description = "CloudFront distribution IDs (for cache invalidation)"
  value = {
    for k, v in aws_cloudfront_distribution.nextjs : k => v.id
  }
}
`;
}
