/**
 * Generate wakeup-lambda.tf with wake-up Lambda and Function URL
 *
 * Creates:
 * - Lambda function to wake up ECS services
 * - Lambda Function URL (simpler/cheaper than API Gateway)
 * - IAM role with ECS permissions
 *
 * Kong's post-function plugin calls this Lambda when ALB returns 502/503.
 * The Lambda wakes all services and returns success.
 *
 * Note: Scale-down alarms and auto scaling are in scale-down.tf
 *
 * See: docs/in-dev/phase-21-aws-service-discovery-fix.md (Phase 21.11d)
 */

export function generateWakeupLambdaTf(): string {
  return `# Wake-up Lambda with Function URL
# Generated by: npx tsdevstack infra:generate
#
# Lambda wakes ECS services when Kong post-function plugin detects 502/503.
# Called via Lambda Function URL (simpler than API Gateway).
# Protected by X-Wake-Secret header validation.

# =============================================================================
# Wake-up Secret (for header validation)
# =============================================================================

resource "random_password" "wakeup_secret" {
  length  = 32
  special = false
}

# =============================================================================
# Lambda Code Archive
# =============================================================================

data "archive_file" "wakeup_lambda" {
  type        = "zip"
  source_dir  = "\${path.module}/lambda/wakeup"
  output_path = "\${path.module}/lambda/wakeup.zip"
}

# =============================================================================
# Wake-up Lambda Function
# =============================================================================

resource "aws_lambda_function" "wakeup" {
  function_name = "\${var.project_name}-\${var.environment}-wakeup"
  runtime       = "nodejs22.x"
  handler       = "index.handler"
  timeout       = 10  # Fast - just triggers wake-up
  memory_size   = 256
  role          = aws_iam_role.wakeup_lambda.arn

  filename         = data.archive_file.wakeup_lambda.output_path
  source_code_hash = data.archive_file.wakeup_lambda.output_base64sha256

  environment {
    variables = {
      ECS_CLUSTER = aws_ecs_cluster.main.name
      # Only include services that can scale to zero (minInstances == 0)
      MANAGED_SERVICES = join(",", [
        for name, cfg in var.services : name if cfg.minInstances == 0
      ])
      # Secret for X-Wake-Secret header validation
      WAKEUP_SECRET = random_password.wakeup_secret.result
    }
  }

  tags = { Name = "\${var.project_name}-wakeup-lambda" }
}

# =============================================================================
# Lambda Function URL (simpler/cheaper than API Gateway)
# =============================================================================

resource "aws_lambda_function_url" "wakeup" {
  function_name      = aws_lambda_function.wakeup.function_name
  authorization_type = "NONE"  # Called from Kong within VPC via NAT

  cors {
    allow_origins = ["*"]
    allow_methods = ["POST", "GET"]
    allow_headers = ["*"]
  }
}

# Permission to allow public access to Lambda Function URL
# AWS requires BOTH lambda:InvokeFunctionUrl AND lambda:InvokeFunction for Function URLs
resource "aws_lambda_permission" "wakeup_url_public" {
  statement_id           = "FunctionURLAllowPublicAccess"
  action                 = "lambda:InvokeFunctionUrl"
  function_name          = aws_lambda_function.wakeup.function_name
  principal              = "*"
  function_url_auth_type = "NONE"

  # Must be created AFTER the Function URL exists
  depends_on = [aws_lambda_function_url.wakeup]
}

resource "aws_lambda_permission" "wakeup_invoke_public" {
  statement_id  = "FunctionURLAllowPublicInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.wakeup.function_name
  principal     = "*"

  depends_on = [aws_lambda_function_url.wakeup]
}

# =============================================================================
# IAM Role for Lambda
# =============================================================================

resource "aws_iam_role" "wakeup_lambda" {
  name = "\${var.project_name}-\${var.environment}-wakeup-lambda"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "lambda.amazonaws.com"
      }
    }]
  })

  tags = { Name = "\${var.project_name}-wakeup-lambda-role" }
}

resource "aws_iam_role_policy" "wakeup_lambda_ecs" {
  name = "ecs-access"
  role = aws_iam_role.wakeup_lambda.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "ecs:DescribeServices",
          "ecs:UpdateService"
        ]
        Resource = "*"
        Condition = {
          ArnEquals = {
            "ecs:cluster" = aws_ecs_cluster.main.arn
          }
        }
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "wakeup_lambda_logs" {
  role       = aws_iam_role.wakeup_lambda.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# =============================================================================
# CloudWatch Log Group (explicit for retention control)
# =============================================================================

resource "aws_cloudwatch_log_group" "wakeup_lambda" {
  name              = "/aws/lambda/\${aws_lambda_function.wakeup.function_name}"
  retention_in_days = 14
  kms_key_id        = aws_kms_key.logs.arn

  tags = { Name = "\${var.project_name}-wakeup-lambda-logs" }
}
`;
}
