import { describe, it, expect } from '@rstest/core';
import { generateAcmTf } from './generate-acm-tf';

describe('generateAcmTf', () => {
  describe('domain locals', () => {
    it('should define api_domain derived from base_domain', () => {
      const result = generateAcmTf();
      expect(result).toContain(
        'api_domain = var.base_domain != "" ? "api.${var.base_domain}" : ""',
      );
    });

    it('should define certificate ARN locals', () => {
      const result = generateAcmTf();
      expect(result).toContain('cloudfront_certificate_arn =');
      expect(result).toContain('regional_certificate_arn   =');
    });
  });

  describe('Route 53 hosted zone', () => {
    it('should lookup hosted zone by domain name', () => {
      const result = generateAcmTf();
      expect(result).toContain('data "aws_route53_zone" "main"');
      expect(result).toContain('name  = var.base_domain');
    });

    it('should be conditional on base_domain', () => {
      const result = generateAcmTf();
      expect(result).toContain('count = var.base_domain != "" ? 1 : 0');
    });
  });

  describe('DNS validation records', () => {
    it('should create validation records', () => {
      const result = generateAcmTf();
      expect(result).toContain(
        'resource "aws_route53_record" "cert_validation"',
      );
    });

    it('should use allow_overwrite for shared validation', () => {
      const result = generateAcmTf();
      expect(result).toContain('allow_overwrite = true');
    });

    it('should iterate over domain validation options', () => {
      const result = generateAcmTf();
      expect(result).toContain(
        'aws_acm_certificate.cloudfront[0].domain_validation_options',
      );
    });
  });

  describe('CloudFront certificate', () => {
    it('should create CloudFront certificate in us-east-1', () => {
      const result = generateAcmTf();
      expect(result).toContain('resource "aws_acm_certificate" "cloudfront"');
      expect(result).toContain('provider = aws.us_east_1');
    });

    it('should include base domain and wildcard', () => {
      const result = generateAcmTf();
      expect(result).toContain('domain_name               = var.base_domain');
      expect(result).toContain(
        'subject_alternative_names = ["*.${var.base_domain}"]',
      );
    });

    it('should use DNS validation method', () => {
      const result = generateAcmTf();
      expect(result).toContain('validation_method         = "DNS"');
    });

    it('should create CloudFront certificate validation', () => {
      const result = generateAcmTf();
      expect(result).toContain(
        'resource "aws_acm_certificate_validation" "cloudfront"',
      );
    });
  });

  describe('regional certificate', () => {
    it('should create regional certificate', () => {
      const result = generateAcmTf();
      expect(result).toContain('resource "aws_acm_certificate" "regional"');
    });

    it('should create regional certificate validation', () => {
      const result = generateAcmTf();
      expect(result).toContain(
        'resource "aws_acm_certificate_validation" "regional"',
      );
    });

    it('should share DNS records with CloudFront cert', () => {
      const result = generateAcmTf();
      // Both validations reference the same cert_validation records
      const matches = result.match(
        /validation_record_fqdns = \[for record in aws_route53_record\.cert_validation/g,
      );
      expect(matches).toHaveLength(2);
    });
  });

  describe('certificate lifecycle', () => {
    it('should use create_before_destroy', () => {
      const result = generateAcmTf();
      expect(result).toContain('create_before_destroy = true');
    });
  });

  describe('outputs', () => {
    it('should output CloudFront certificate ARN', () => {
      const result = generateAcmTf();
      expect(result).toContain('output "cloudfront_certificate_arn"');
    });

    it('should output regional certificate ARN', () => {
      const result = generateAcmTf();
      expect(result).toContain('output "regional_certificate_arn"');
    });

    it('should output Route 53 zone ID', () => {
      const result = generateAcmTf();
      expect(result).toContain('output "route53_zone_id"');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateAcmTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateAcmTf();
      expect(result).toMatchSnapshot();
    });
  });
});
