/**
 * Generate response-headers-policy.tf for CloudFront
 *
 * Creates a shared CloudFront response headers policy with:
 * - Security headers (HSTS, X-Content-Type-Options, X-Frame-Options, etc.)
 * - Optional X-Robots-Tag: noindex, nofollow (when noIndex is true)
 *
 * This policy is attached to all CloudFront distributions (API, SPA, Next.js).
 */

export interface ResponseHeadersPolicyConfig {
  /** Add X-Robots-Tag: noindex, nofollow header */
  noIndex?: boolean;
}

/**
 * Generate the response headers policy Terraform configuration
 */
export function generateResponseHeadersPolicyTf(
  config: ResponseHeadersPolicyConfig,
): string {
  const { noIndex = false } = config;

  const customHeadersBlock = noIndex
    ? `

  custom_headers_config {
    items {
      header   = "X-Robots-Tag"
      value    = "noindex, nofollow"
      override = true
    }
  }`
    : '';

  return `# CloudFront Response Headers Policy
# Generated by: npx tsdevstack infra:generate
#
# Shared security headers policy attached to all CloudFront distributions.
# Includes standard security headers and optional X-Robots-Tag for noIndex.

resource "aws_cloudfront_response_headers_policy" "security_headers" {
  name    = "\${var.project_name}-\${var.environment}-security-headers"
  comment = "Security headers for all CloudFront distributions"

  security_headers_config {
    strict_transport_security {
      access_control_max_age_sec = 63072000
      include_subdomains         = true
      preload                    = true
      override                   = true
    }

    content_type_options {
      override = true
    }

    frame_options {
      frame_option = "DENY"
      override     = true
    }

    referrer_policy {
      referrer_policy = "strict-origin-when-cross-origin"
      override        = true
    }
  }${customHeadersBlock}
}
`;
}
