/**
 * Generate eventbridge.tf with EventBridge schedules and Job Invoker Lambda
 *
 * Creates:
 * - Job Invoker Lambda (in VPC for CloudMap DNS resolution)
 * - Job auth secret
 * - EventBridge Scheduler role
 * - EventBridge schedules (per scheduled job)
 *
 * Architecture:
 * EventBridge Schedule → Job Invoker Lambda → HTTP call to service
 *                              ↓
 *                    (wakes services first if needed)
 *
 * Job authentication uses X-Job-Secret header (vs OIDC token on GCP).
 */

export function generateEventbridgeTf(): string {
  return `# EventBridge Scheduled Jobs
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# Job Auth Secret
# =============================================================================

resource "random_password" "job_auth" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "job_auth" {
  name        = "\${var.project_name}-job-auth-secret"
  description = "Secret for authenticating scheduled job invocations"

  tags = { Name = "\${var.project_name}-job-auth" }
}

resource "aws_secretsmanager_secret_version" "job_auth" {
  secret_id     = aws_secretsmanager_secret.job_auth.id
  secret_string = random_password.job_auth.result
}

# =============================================================================
# Job Invoker Lambda Code Archive
# =============================================================================

data "archive_file" "job_invoker_lambda" {
  type        = "zip"
  source_dir  = "\${path.module}/lambda/job-invoker"
  output_path = "\${path.module}/lambda/job-invoker.zip"
}

# =============================================================================
# Job Invoker Lambda Function
# Must be in VPC to resolve CloudMap DNS
# =============================================================================

# CloudWatch Log Group (must exist before Lambda to use KMS)
resource "aws_cloudwatch_log_group" "job_invoker" {
  name              = "/aws/lambda/\${var.project_name}-job-invoker"
  retention_in_days = 14
  kms_key_id        = aws_kms_key.logs.arn

  tags = { Name = "\${var.project_name}-job-invoker-logs" }
}

resource "aws_lambda_function" "job_invoker" {
  function_name = "\${var.project_name}-job-invoker"
  runtime       = "nodejs22.x"
  handler       = "index.handler"
  timeout       = 300
  memory_size   = 256
  role          = aws_iam_role.job_invoker_lambda.arn

  depends_on = [aws_cloudwatch_log_group.job_invoker]

  filename         = data.archive_file.job_invoker_lambda.output_path
  source_code_hash = data.archive_file.job_invoker_lambda.output_base64sha256

  vpc_config {
    subnet_ids         = aws_subnet.private[*].id
    security_group_ids = [aws_security_group.ecs.id]
  }

  environment {
    variables = {
      ECS_CLUSTER        = aws_ecs_cluster.main.name
      SERVICE_NAMES      = join(",", keys(var.services))
      CLOUDMAP_NAMESPACE = "\${var.project_name}.local"
      JOB_SECRET_ARN     = aws_secretsmanager_secret.job_auth.arn
    }
  }

  tags = { Name = "\${var.project_name}-job-invoker" }
}

# =============================================================================
# Job Invoker Lambda IAM Role
# =============================================================================

resource "aws_iam_role" "job_invoker_lambda" {
  name = "\${var.project_name}-job-invoker-lambda"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
    }]
  })

  tags = { Name = "\${var.project_name}-job-invoker-lambda" }
}

resource "aws_iam_role_policy" "job_invoker_lambda" {
  name = "job-invoker-permissions"
  role = aws_iam_role.job_invoker_lambda.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "ecs:UpdateService",
          "ecs:DescribeServices"
        ]
        Resource = "*"
      },
      {
        Effect   = "Allow"
        Action   = ["secretsmanager:GetSecretValue"]
        Resource = aws_secretsmanager_secret.job_auth.arn
      },
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Resource = "arn:aws:logs:*:*:*"
      },
      {
        Effect = "Allow"
        Action = [
          "ec2:CreateNetworkInterface",
          "ec2:DescribeNetworkInterfaces",
          "ec2:DeleteNetworkInterface"
        ]
        Resource = "*"
      }
    ]
  })
}

# =============================================================================
# EventBridge Scheduler IAM Role
# =============================================================================

resource "aws_iam_role" "eventbridge_scheduler" {
  name = "\${var.project_name}-eventbridge-scheduler"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "scheduler.amazonaws.com" }
    }]
  })

  tags = { Name = "\${var.project_name}-eventbridge-scheduler" }
}

resource "aws_iam_role_policy" "eventbridge_scheduler" {
  name = "invoke-lambda"
  role = aws_iam_role.eventbridge_scheduler.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = "lambda:InvokeFunction"
      Resource = aws_lambda_function.job_invoker.arn
    }]
  })
}

# =============================================================================
# EventBridge Schedules (per scheduled job)
# =============================================================================

resource "aws_scheduler_schedule" "job" {
  for_each = var.scheduled_jobs

  name       = "\${var.project_name}-\${each.key}"
  group_name = "default"

  schedule_expression = each.value.schedule

  flexible_time_window {
    mode = "OFF"
  }

  target {
    arn      = aws_lambda_function.job_invoker.arn
    role_arn = aws_iam_role.eventbridge_scheduler.arn

    input = jsonencode({
      serviceName = each.value.serviceName
      path        = each.value.path
    })

    retry_policy {
      maximum_event_age_in_seconds = 86400
      maximum_retry_attempts       = 3
    }
  }
}
`;
}
