/**
 * Generate db-delete.tf with ECS task definition for database deletion
 *
 * Creates:
 * - ECR repository for db-delete image
 * - ECS task definition for db-delete
 * - IAM role for db-delete task (read master password only)
 * - CloudWatch log group
 *
 * The db-delete task drops per-service databases and users from RDS.
 * Executed by CLI during infra:remove-service.
 */

export function generateDbDeleteTf(): string {
  return `# DB-Delete Task
# Generated by: npx tsdevstack infra:generate
# Drops per-service databases and users from RDS PostgreSQL

# =============================================================================
# ECR Repository
# Separate repo for db-delete image (not part of for_each deployables)
# =============================================================================

resource "aws_ecr_repository" "db_delete" {
  name                 = "\${var.project_name}/db-delete"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  tags = { Name = "\${var.project_name}-db-delete" }
}

resource "aws_ecr_lifecycle_policy" "db_delete_cleanup" {
  repository = aws_ecr_repository.db_delete.name

  policy = jsonencode({
    rules = [{
      rulePriority = 1
      description  = "Keep only last 5 images"
      selection = {
        tagStatus   = "any"
        countType   = "imageCountMoreThan"
        countNumber = 5
      }
      action = { type = "expire" }
    }]
  })
}

# =============================================================================
# CloudWatch Log Group
# =============================================================================

resource "aws_cloudwatch_log_group" "db_delete" {
  name              = "/ecs/\${var.project_name}/db-delete"
  retention_in_days = 30
  kms_key_id        = aws_kms_key.logs.arn

  tags = { Name = "\${var.project_name}-db-delete-logs" }
}

# =============================================================================
# IAM Role for db-delete Task
# Needs: read master password only (no secrets creation)
# =============================================================================

resource "aws_iam_role" "db_delete_task" {
  name = "\${var.project_name}-\${var.environment}-db-delete-task"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
    }]
  })

  tags = { Name = "\${var.project_name}-db-delete-task" }
}

resource "aws_iam_role_policy" "db_delete_secrets" {
  name = "secrets-access"
  role = aws_iam_role.db_delete_task.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "ReadMasterPassword"
        Effect = "Allow"
        Action = ["secretsmanager:GetSecretValue"]
        Resource = [aws_secretsmanager_secret.db_master_password.arn]
      }
    ]
  })
}

# =============================================================================
# ECS Task Definition
# =============================================================================

resource "aws_ecs_task_definition" "db_delete" {
  family                   = "\${var.project_name}-db-delete"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = 256
  memory                   = 512
  execution_role_arn       = aws_iam_role.ecs_execution.arn
  task_role_arn            = aws_iam_role.db_delete_task.arn

  container_definitions = jsonencode([
    {
      name      = "db-delete"
      image     = "\${aws_ecr_repository.db_delete.repository_url}:latest"
      essential = true

      command = ["node", "index.js"]

      environment = [
        { name = "DB_HOST", value = aws_db_instance.main.address },
        { name = "DB_PORT", value = tostring(aws_db_instance.main.port) }
        # SERVICES env var is passed at runtime via container overrides
      ]

      secrets = [
        {
          name      = "DB_MASTER_PASSWORD"
          valueFrom = aws_secretsmanager_secret.db_master_password.arn
        }
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          "awslogs-group"         = aws_cloudwatch_log_group.db_delete.name
          "awslogs-region"        = var.aws_region
          "awslogs-stream-prefix" = "db-delete"
        }
      }
    }
  ])

  tags = { Name = "\${var.project_name}-db-delete" }
}
`;
}
