import { describe, it, expect } from '@rstest/core';
import { generateMainTf } from './generate-main-tf';
import type { AWSInfraConfig } from '../../types/config.ts';

describe('generateMainTf', () => {
  const baseConfig: AWSInfraConfig = {
    provider: 'aws',
    projectName: 'my-app',
    environment: 'dev',
    accountId: '123456789012',
    region: 'us-east-1',
    stateBucket: 'my-app-terraform-state-123456789012',
    lockTable: 'my-app-terraform-locks',
    database: {
      tier: 'db.t3.micro',
      storageSizeGb: 20,
      deletionProtection: false,
      backup: false,
    },
    redis: { tier: 'cache.t3.micro', highAvailability: false },
    servicesWithDatabase: [],
    baseDomain: 'example.com',
    services: {},
    workers: {},
    allDeployables: {},
    spas: {},
    frontends: {},
    scheduledJobs: {},
    storageBuckets: [],
  };

  describe('terraform block', () => {
    it('should include required terraform version', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('required_version = ">= 1.0"');
    });

    it('should include aws provider source', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('source  = "hashicorp/aws"');
    });

    it('should include aws provider version', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('version = "~> 5.0"');
    });

    it('should include random provider for password generation', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('source  = "hashicorp/random"');
    });
  });

  describe('backend configuration', () => {
    it('should configure S3 backend with state bucket', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('backend "s3"');
      expect(result).toContain(
        'bucket         = "my-app-terraform-state-123456789012"',
      );
    });

    it('should configure DynamoDB lock table', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('dynamodb_table = "my-app-terraform-locks"');
    });

    it('should use environment in state key path', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('key            = "dev/terraform.tfstate"');
    });

    it('should use different key for different environments', () => {
      const prodConfig = { ...baseConfig, environment: 'prod' };
      const result = generateMainTf(prodConfig);
      expect(result).toContain('key            = "prod/terraform.tfstate"');
    });

    it('should enable encryption', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('encrypt        = true');
    });
  });

  describe('provider configuration', () => {
    it('should configure aws provider with region variable', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('provider "aws"');
      expect(result).toContain('region = var.aws_region');
    });

    it('should include default tags', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('default_tags');
      expect(result).toContain('Project     = var.project_name');
      expect(result).toContain('Environment = var.environment');
      expect(result).toContain('ManagedBy   = "terraform"');
    });

    it('should include us-east-1 provider alias for CloudFront resources', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('alias  = "us_east_1"');
      expect(result).toContain('region = "us-east-1"');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot for dev environment', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toMatchSnapshot();
    });

    it('should match snapshot for prod environment', () => {
      const prodConfig: AWSInfraConfig = {
        ...baseConfig,
        environment: 'prod',
        stateBucket: 'production-app-terraform-state-123456789012',
      };
      const result = generateMainTf(prodConfig);
      expect(result).toMatchSnapshot();
    });
  });
});
