/**
 * Generate db-init directory files
 *
 * Generates:
 * - Dockerfile - Node.js alpine image for running db-init
 * - package.json - Dependencies (pg, @aws-sdk/client-secrets-manager)
 * - index.js - Main script that creates databases/users and writes secrets
 *
 * These files are generated into infrastructure/terraform/{env}/db-init/
 * and built into a Docker image at deploy time.
 */

export interface DbInitFiles {
  dockerfile: string;
  packageJson: string;
  indexJs: string;
}

export function generateDbInit(): DbInitFiles {
  return {
    dockerfile: generateDockerfile(),
    packageJson: generatePackageJson(),
    indexJs: generateIndexJs(),
  };
}

function generateDockerfile(): string {
  return `FROM node:20-alpine
WORKDIR /app
COPY package.json ./
RUN npm install --production
COPY index.js ./
CMD ["node", "index.js"]
`;
}

function generatePackageJson(): string {
  return `{
  "name": "db-init",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "pg": "^8.11.0",
    "@aws-sdk/client-secrets-manager": "^3.700.0"
  }
}
`;
}

function generateIndexJs(): string {
  return `// DB-Init Script
// Generated by: npx tsdevstack infra:generate
// Creates per-service databases and users in RDS PostgreSQL

const { Client } = require('pg');
const {
  SecretsManagerClient,
  CreateSecretCommand,
  PutSecretValueCommand,
  DescribeSecretCommand,
} = require('@aws-sdk/client-secrets-manager');
const { randomBytes } = require('crypto');

// =============================================================================
// SECRETS MANAGER HELPERS
// =============================================================================

const secretsClient = new SecretsManagerClient({
  region: process.env.AWS_REGION,
});

async function checkSecretExists(secretName) {
  try {
    await secretsClient.send(new DescribeSecretCommand({ SecretId: secretName }));
    return true;
  } catch (e) {
    if (e.name === 'ResourceNotFoundException') return false;
    throw e;
  }
}

async function writeSecret(secretName, value, project, environment) {
  const tags = [
    { Key: 'managed-by', Value: 'tsdevstack' },
    { Key: 'project', Value: project },
    { Key: 'environment', Value: environment },
    { Key: 'secret-type', Value: 'database-url' },
  ];

  try {
    await secretsClient.send(
      new CreateSecretCommand({
        Name: secretName,
        SecretString: value,
        Tags: tags,
      })
    );
  } catch (e) {
    if (e.name === 'ResourceExistsException') {
      await secretsClient.send(
        new PutSecretValueCommand({
          SecretId: secretName,
          SecretString: value,
        })
      );
    } else {
      throw e;
    }
  }
}

// =============================================================================
// PASSWORD GENERATION
// =============================================================================

function generatePassword() {
  // 32 chars, alphanumeric only (no special chars that need URL encoding)
  return randomBytes(24).toString('base64').replace(/[+/=]/g, 'x');
}

// =============================================================================
// MAIN
// =============================================================================

async function main() {
  console.log('db-init starting...');

  // Read environment
  const project = process.env.PROJECT;
  const environment = process.env.ENVIRONMENT;
  const dbHost = process.env.DB_HOST;
  const dbPort = process.env.DB_PORT || '5432';
  const masterPassword = process.env.DB_MASTER_PASSWORD;
  const servicesJson = process.env.SERVICES;

  // Validate required env vars
  if (!project || !environment || !dbHost || !masterPassword || !servicesJson) {
    console.error('Missing required environment variables:');
    console.error('  PROJECT: ' + (project ? 'set' : 'MISSING'));
    console.error('  ENVIRONMENT: ' + (environment ? 'set' : 'MISSING'));
    console.error('  DB_HOST: ' + (dbHost ? 'set' : 'MISSING'));
    console.error('  DB_MASTER_PASSWORD: ' + (masterPassword ? 'set' : 'MISSING'));
    console.error('  SERVICES: ' + (servicesJson ? 'set' : 'MISSING'));
    process.exit(1);
  }

  // Parse services
  let services;
  try {
    services = JSON.parse(servicesJson);
  } catch (e) {
    console.error('Failed to parse SERVICES JSON:', e);
    process.exit(1);
  }

  const servicesWithDb = services.filter((s) => s.hasDatabase);

  if (servicesWithDb.length === 0) {
    console.log('No services with databases configured. Exiting.');
    return;
  }

  console.log('Services with databases: ' + servicesWithDb.map((s) => s.name).join(', '));

  // Connect to RDS as master user
  const masterClient = new Client({
    host: dbHost,
    port: parseInt(dbPort),
    user: 'postgres',
    password: masterPassword,
    database: 'postgres',
    ssl: { rejectUnauthorized: false },
  });

  try {
    await masterClient.connect();
    console.log('Connected to RDS at ' + dbHost + ':' + dbPort + ' as postgres');
  } catch (e) {
    console.error('Failed to connect to RDS:', e);
    process.exit(1);
  }

  // Process each service
  for (const service of servicesWithDb) {
    console.log('');
    console.log('============================================================');
    console.log('Processing: ' + service.name);
    console.log('============================================================');

    // Naming convention (matches GCP):
    // service.name = "auth-service" -> dbName = "auth-service", dbUser = "auth-service"
    const dbName = service.name;
    const dbUser = service.name;
    // Use hyphen format to match deploy-ecs-service-with-secrets.ts expectation
    const secretName = project + '-' + service.name + '-DATABASE_URL';

    console.log('  Database: ' + dbName);
    console.log('  User: ' + dbUser);
    console.log('  Secret: ' + secretName);

    // Check if database exists
    const dbExistsResult = await masterClient.query(
      'SELECT 1 FROM pg_database WHERE datname = $1',
      [dbName]
    );
    const dbExists = (dbExistsResult.rowCount || 0) > 0;

    if (!dbExists) {
      console.log('  -> Creating database: ' + dbName);
      await masterClient.query('CREATE DATABASE "' + dbName + '"');
      console.log('  [OK] Database created');
    } else {
      console.log('  [OK] Database already exists');
    }

    // Check if user exists
    const userExistsResult = await masterClient.query(
      'SELECT 1 FROM pg_roles WHERE rolname = $1',
      [dbUser]
    );
    const userExists = (userExistsResult.rowCount || 0) > 0;

    // Check if secret exists
    const secretExists = await checkSecretExists(secretName);

    if (!userExists) {
      // Create user with new password
      const password = generatePassword();
      console.log('  -> Creating user: ' + dbUser);

      await masterClient.query('CREATE USER "' + dbUser + '" WITH PASSWORD \\'' + password + '\\'');
      console.log('  [OK] User created');

      // Grant privileges on database
      await masterClient.query('GRANT ALL PRIVILEGES ON DATABASE "' + dbName + '" TO "' + dbUser + '"');
      console.log('  [OK] Database privileges granted');

      // Connect to the service database to grant schema privileges
      const serviceClient = new Client({
        host: dbHost,
        port: parseInt(dbPort),
        user: 'postgres',
        password: masterPassword,
        database: dbName,
        ssl: { rejectUnauthorized: false },
      });

      await serviceClient.connect();

      await serviceClient.query('GRANT ALL ON SCHEMA public TO "' + dbUser + '"');
      await serviceClient.query(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "' + dbUser + '"'
      );
      await serviceClient.query(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "' + dbUser + '"'
      );
      console.log('  [OK] Schema privileges granted');

      await serviceClient.end();

      // Build and store DATABASE_URL
      // Note: SSL is handled by the application via CLOUD_PROVIDER env var, not URL params
      const databaseUrl = 'postgresql://' + dbUser + ':' + encodeURIComponent(password) + '@' + dbHost + ':' + dbPort + '/' + dbName;
      await writeSecret(secretName, databaseUrl, project, environment);
      console.log('  [OK] Secret created: ' + secretName);

    } else if (!secretExists) {
      // User exists but secret doesn't - reset password and create secret
      console.log('  -> User exists but secret missing, resetting password...');
      const password = generatePassword();

      await masterClient.query('ALTER USER "' + dbUser + '" WITH PASSWORD \\'' + password + '\\'');
      console.log('  [OK] Password reset');

      // Build and store DATABASE_URL
      const databaseUrl = 'postgresql://' + dbUser + ':' + encodeURIComponent(password) + '@' + dbHost + ':' + dbPort + '/' + dbName;
      await writeSecret(secretName, databaseUrl, project, environment);
      console.log('  [OK] Secret created: ' + secretName);

    } else {
      console.log('  [OK] User already exists');
      console.log('  [OK] Secret already exists');
    }
  }

  await masterClient.end();
  console.log('');
  console.log('============================================================');
  console.log('db-init completed successfully');
  console.log('============================================================');
}

main().catch((e) => {
  console.error('db-init failed with error:', e);
  process.exit(1);
});
`;
}
