import { describe, it, expect } from '@rstest/core';
import { generateRoute53Tf } from './generate-route53-tf';

describe('generateRoute53Tf', () => {
  describe('API domain A record', () => {
    it('should create API A record', () => {
      const result = generateRoute53Tf();
      expect(result).toContain('resource "aws_route53_record" "api"');
    });

    it('should be conditional on base_domain', () => {
      const result = generateRoute53Tf();
      expect(result).toContain('count = var.base_domain != "" ? 1 : 0');
    });

    it('should use hosted zone from data source', () => {
      const result = generateRoute53Tf();
      expect(result).toContain(
        'zone_id = data.aws_route53_zone.main[0].zone_id',
      );
    });

    it('should use local.api_domain as name', () => {
      const result = generateRoute53Tf();
      expect(result).toContain('name    = local.api_domain');
    });

    it('should be A record type', () => {
      const result = generateRoute53Tf();
      expect(result).toContain('type    = "A"');
    });
  });

  describe('CloudFront alias', () => {
    it('should alias to main CloudFront distribution', () => {
      const result = generateRoute53Tf();
      expect(result).toContain(
        'name                   = aws_cloudfront_distribution.main.domain_name',
      );
      expect(result).toContain(
        'zone_id                = aws_cloudfront_distribution.main.hosted_zone_id',
      );
    });

    it('should not evaluate target health', () => {
      const result = generateRoute53Tf();
      expect(result).toContain('evaluate_target_health = false');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateRoute53Tf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateRoute53Tf();
      expect(result).toMatchSnapshot();
    });
  });
});
