/**
 * Generate database.tf with RDS PostgreSQL instance
 *
 * Creates:
 * - DB subnet group (uses private subnets)
 * - Random master password
 * - RDS PostgreSQL 15 instance
 *
 * Note: Individual databases and users are created at deploy time via init job,
 * not in Terraform, matching the GCP pattern.
 */

export function generateDatabaseTf(): string {
  return `# RDS PostgreSQL Database
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# DB Subnet Group
# =============================================================================

resource "aws_db_subnet_group" "main" {
  name        = "\${var.project_name}-db"
  description = "Database subnet group for \${var.project_name}"
  subnet_ids  = aws_subnet.private[*].id

  tags = { Name = "\${var.project_name}-db" }
}

# =============================================================================
# Master Password
# =============================================================================

resource "random_password" "db_master" {
  length  = 32
  special = false
}

# =============================================================================
# RDS PostgreSQL Instance
# =============================================================================

resource "aws_db_instance" "main" {
  identifier     = "\${var.project_name}-db"
  engine         = "postgres"
  engine_version = "15"
  instance_class = var.db_instance_class

  db_name  = "postgres"
  username = "postgres"
  password = random_password.db_master.result

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.rds.id]
  publicly_accessible    = false

  allocated_storage     = 20
  max_allocated_storage = 100
  storage_type          = "gp3"
  storage_encrypted     = true

  backup_retention_period   = 7
  backup_window             = "03:00-04:00"
  maintenance_window        = "Mon:04:00-Mon:05:00"
  deletion_protection       = var.database_deletion_protection
  skip_final_snapshot       = false
  final_snapshot_identifier = "\${var.project_name}-db-final"

  performance_insights_enabled = false

  tags = { Name = "\${var.project_name}-db" }
}

# =============================================================================
# Store Master Password in Secrets Manager
# =============================================================================

resource "aws_secretsmanager_secret" "db_master_password" {
  name        = "\${var.project_name}-db-master-password"
  description = "RDS master password for \${var.project_name}"

  tags = { Name = "\${var.project_name}-db-master-password" }
}

resource "aws_secretsmanager_secret_version" "db_master_password" {
  secret_id     = aws_secretsmanager_secret.db_master_password.id
  secret_string = random_password.db_master.result
}
`;
}
