import { describe, it, expect } from '@rstest/core';
import { generateCloudtrailTf } from './generate-cloudtrail-tf';

describe('generateCloudtrailTf', () => {
  const result = generateCloudtrailTf();

  describe('KMS key', () => {
    it('should create KMS key for CloudTrail encryption', () => {
      expect(result).toContain('resource "aws_kms_key" "cloudtrail"');
    });

    it('should enable key rotation', () => {
      expect(result).toContain('enable_key_rotation     = true');
    });

    it('should allow CloudTrail service to encrypt', () => {
      expect(result).toContain('cloudtrail.amazonaws.com');
      expect(result).toContain('kms:GenerateDataKey');
    });

    it('should create KMS alias', () => {
      expect(result).toContain('resource "aws_kms_alias" "cloudtrail"');
      expect(result).toContain('alias/${var.project_name}-cloudtrail');
    });
  });

  describe('S3 bucket', () => {
    it('should create S3 bucket for CloudTrail logs', () => {
      expect(result).toContain('resource "aws_s3_bucket" "cloudtrail"');
    });

    it('should enable versioning', () => {
      expect(result).toContain(
        'resource "aws_s3_bucket_versioning" "cloudtrail"',
      );
      expect(result).toContain('status = "Enabled"');
    });

    it('should enable server-side encryption with KMS', () => {
      expect(result).toContain(
        'resource "aws_s3_bucket_server_side_encryption_configuration" "cloudtrail"',
      );
      expect(result).toContain('sse_algorithm     = "aws:kms"');
    });

    it('should block public access', () => {
      expect(result).toContain(
        'resource "aws_s3_bucket_public_access_block" "cloudtrail"',
      );
      expect(result).toContain('block_public_acls       = true');
      expect(result).toContain('block_public_policy     = true');
      expect(result).toContain('restrict_public_buckets = true');
    });

    it('should have lifecycle policy for log retention', () => {
      expect(result).toContain(
        'resource "aws_s3_bucket_lifecycle_configuration" "cloudtrail"',
      );
      expect(result).toContain('days = 90');
    });

    it('should have empty filter block for lifecycle rule (required by AWS provider)', () => {
      expect(result).toContain('filter {}');
    });

    it('should have bucket policy allowing CloudTrail service', () => {
      expect(result).toContain('resource "aws_s3_bucket_policy" "cloudtrail"');
      expect(result).toContain('AWSCloudTrailAclCheck');
      expect(result).toContain('AWSCloudTrailWrite');
    });
  });

  describe('CloudTrail resource', () => {
    it('should create CloudTrail trail', () => {
      expect(result).toContain('resource "aws_cloudtrail" "main"');
    });

    it('should use S3 bucket for storage', () => {
      expect(result).toContain(
        's3_bucket_name                = aws_s3_bucket.cloudtrail.id',
      );
    });

    it('should use KMS key for encryption', () => {
      expect(result).toContain(
        'kms_key_id                    = aws_kms_key.cloudtrail.arn',
      );
    });

    it('should include global service events (IAM, CloudFront, etc.)', () => {
      expect(result).toContain('include_global_service_events = true');
    });

    it('should enable log file validation for tamper detection', () => {
      expect(result).toContain('enable_log_file_validation    = true');
    });

    it('should log all management events', () => {
      expect(result).toContain('event_selector');
      expect(result).toContain('read_write_type           = "All"');
      expect(result).toContain('include_management_events = true');
    });

    it('should depend on S3 bucket policy', () => {
      expect(result).toContain(
        'depends_on = [aws_s3_bucket_policy.cloudtrail]',
      );
    });
  });

  describe('outputs', () => {
    it('should output CloudTrail ARN', () => {
      expect(result).toContain('output "cloudtrail_arn"');
      expect(result).toContain('aws_cloudtrail.main.arn');
    });

    it('should output S3 bucket name', () => {
      expect(result).toContain('output "cloudtrail_s3_bucket"');
      expect(result).toContain('aws_s3_bucket.cloudtrail.id');
    });

    it('should output KMS key ARN', () => {
      expect(result).toContain('output "cloudtrail_kms_key_arn"');
      expect(result).toContain('aws_kms_key.cloudtrail.arn');
    });
  });

  describe('compliance requirements', () => {
    it('should include generator comment', () => {
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });

    it('should document compliance purpose in header', () => {
      expect(result).toContain('CloudTrail Audit Logging');
    });
  });
});
