/**
 * Generate vpc-flow-logs.tf with VPC Flow Logs configuration
 *
 * Creates:
 * - IAM role for VPC Flow Logs service
 * - CloudWatch Log Group for VPC Flow Logs (KMS encrypted)
 * - VPC Flow Logs resource capturing all traffic
 *
 * Flow Logs capture network traffic metadata for security monitoring
 * and troubleshooting. Logs are sent to CloudWatch and encrypted with KMS.
 */

export function generateVpcFlowLogsTf(): string {
  return `# VPC Flow Logs
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# IAM Role for VPC Flow Logs
# =============================================================================

resource "aws_iam_role" "vpc_flow_logs" {
  name = "\${var.project_name}-vpc-flow-logs"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "vpc-flow-logs.amazonaws.com"
      }
    }]
  })

  tags = { Name = "\${var.project_name}-vpc-flow-logs-role" }
}

resource "aws_iam_role_policy" "vpc_flow_logs" {
  name = "vpc-flow-logs-policy"
  role = aws_iam_role.vpc_flow_logs.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:DescribeLogGroups",
        "logs:DescribeLogStreams"
      ]
      Effect   = "Allow"
      Resource = "*"
    }]
  })
}

# =============================================================================
# CloudWatch Log Group for VPC Flow Logs
# =============================================================================

resource "aws_cloudwatch_log_group" "vpc_flow_logs" {
  name              = "/aws/vpc/flowlogs/\${var.project_name}"
  retention_in_days = 30
  kms_key_id        = aws_kms_key.logs.arn

  tags = { Name = "\${var.project_name}-vpc-flow-logs" }
}

# =============================================================================
# VPC Flow Logs
# =============================================================================

resource "aws_flow_log" "main" {
  vpc_id                   = aws_vpc.main.id
  traffic_type             = "ALL"
  log_destination_type     = "cloud-watch-logs"
  log_destination          = aws_cloudwatch_log_group.vpc_flow_logs.arn
  iam_role_arn             = aws_iam_role.vpc_flow_logs.arn
  max_aggregation_interval = 60

  tags = { Name = "\${var.project_name}-vpc-flow-logs" }
}
`;
}
