/**
 * Generate terraform.tfvars with actual values for AWS
 */

import type { AWSInfraConfig } from '../../types/config.ts';

export function generateTfvars(config: AWSInfraConfig): string {
  const {
    projectName,
    environment,
    accountId,
    region,
    database,
    redis,
    baseDomain,
    services,
    workers,
    allDeployables,
    spas,
    frontends,
    scheduledJobs,
  } = config;

  // Format services map
  const servicesHcl = formatServicesMap(services);

  // Format workers map
  const workersHcl = formatWorkersMap(workers);

  // Format all_deployables map
  const allDeployablesHcl = formatSimpleMap(allDeployables);

  // Format spa_services map
  const spaServicesHcl = formatSpaServicesMap(spas);

  // Format nextjs_services map
  const nextjsServicesHcl = formatNextjsServicesMap(frontends);

  // Format scheduled_jobs map
  const scheduledJobsHcl = formatScheduledJobsMap(scheduledJobs);

  return `# Variable values
# Generated by: npx tsdevstack infra:generate

project_name   = "${projectName}"
environment    = "${environment}"
aws_region     = "${region}"
aws_account_id = "${accountId}"

# Base domain (Route 53 hosted zone looked up via data source)
# Subdomains (api., app., etc.) are derived in Terraform
base_domain = "${baseDomain}"

# Services (ECS)
services = ${servicesHcl}

workers = ${workersHcl}

all_deployables = ${allDeployablesHcl}

# SPA Services
spa_services = ${spaServicesHcl}

# Next.js Services (App Runner + CloudFront)
nextjs_services = ${nextjsServicesHcl}

# Scheduled Jobs
scheduled_jobs = ${scheduledJobsHcl}

# Database (RDS PostgreSQL)
db_instance_class            = "${database.tier}"
database_storage_size        = ${database.storageSizeGb}
database_deletion_protection = ${database.deletionProtection}
database_backup              = ${database.backup}

# Redis (ElastiCache)
redis_node_type         = "${redis.tier}"
redis_high_availability = ${redis.highAvailability ?? false}
`;
}

function formatServicesMap(services: AWSInfraConfig['services']): string {
  const entries = Object.entries(services);
  if (entries.length === 0) return '{}';

  const lines = entries.map(
    ([name, cfg]) =>
      `  "${name}" = {
    cpu          = ${cfg.cpu}
    memory       = ${parseInt(cfg.memory, 10)}
    minInstances = ${cfg.minInstances}
    maxInstances = ${cfg.maxInstances}
    dbPoolMax    = ${cfg.dbPoolMax ?? 5}
  }`,
  );

  return `{
${lines.join('\n')}
}`;
}

function formatWorkersMap(workers: AWSInfraConfig['workers']): string {
  const entries = Object.entries(workers);
  if (entries.length === 0) return '{}';

  const lines = entries.map(
    ([name, cfg]) =>
      `  "${name}" = {
    cpu          = ${cfg.cpu}
    memory       = ${parseInt(cfg.memory, 10)}
    minInstances = ${cfg.minInstances}
    maxInstances = ${cfg.maxInstances}
    service      = "${cfg.service}"
    dbPoolMax    = ${cfg.dbPoolMax ?? 5}
  }`,
  );

  return `{
${lines.join('\n')}
}`;
}

function formatSimpleMap(map: Record<string, string>): string {
  const entries = Object.entries(map);
  if (entries.length === 0) return '{}';

  const lines = entries.map(([key, value]) => `  "${key}" = "${value}"`);

  return `{
${lines.join('\n')}
}`;
}

function formatSpaServicesMap(spas: AWSInfraConfig['spas']): string {
  const entries = Object.entries(spas);
  if (entries.length === 0) return '{}';

  const lines = entries.map(
    ([name, cfg]) =>
      `  "${name}" = {
    domain = "${cfg.domain}"
  }`,
  );

  return `{
${lines.join('\n')}
}`;
}

function formatScheduledJobsMap(
  scheduledJobs: AWSInfraConfig['scheduledJobs'],
): string {
  const entries = Object.entries(scheduledJobs);
  if (entries.length === 0) return '{}';

  const lines = entries.map(
    ([name, cfg]) =>
      `  "${name}" = {
    schedule    = "${cfg.schedule}"
    serviceName = "${cfg.targetService}"
    path        = "${cfg.endpoint}"
  }`,
  );

  return `{
${lines.join('\n')}
}`;
}

function formatNextjsServicesMap(
  frontends: AWSInfraConfig['frontends'],
): string {
  const entries = Object.entries(frontends);
  if (entries.length === 0) return '{}';

  const lines = entries.map(
    ([name, cfg]) =>
      `  "${name}" = {
    domain       = "${cfg.domain}"
    cpu          = ${cfg.cpu}
    memory       = ${parseInt(cfg.memory, 10)}
    minInstances = ${cfg.minInstances}
    maxInstances = ${cfg.maxInstances}
  }`,
  );

  return `{
${lines.join('\n')}
}`;
}
