import { describe, it, expect } from '@rstest/core';
import { generateSpaBucketsTf } from './generate-spa-buckets-tf';

describe('generateSpaBucketsTf', () => {
  describe('no SPA services', () => {
    it('should return comment for empty array', () => {
      const result = generateSpaBucketsTf([]);
      expect(result).toContain('No SPA services configured');
      expect(result).toContain('Generated by');
    });
  });

  describe('single SPA service', () => {
    it('should generate bucket for single service', () => {
      const result = generateSpaBucketsTf([{ name: 'frontend' }]);
      expect(result).toContain('google_storage_bucket');
      expect(result).toContain('frontend');
    });

    it('should configure website settings for SPA', () => {
      const result = generateSpaBucketsTf([{ name: 'app' }]);
      expect(result).toContain('website');
      expect(result).toContain('main_page_suffix = "index.html"');
      expect(result).toContain('not_found_page   = "index.html"');
    });

    it('should configure public access', () => {
      const result = generateSpaBucketsTf([{ name: 'app' }]);
      expect(result).toContain('google_storage_bucket_iam_member');
      expect(result).toContain('roles/storage.objectViewer');
      expect(result).toContain('allUsers');
    });

    it('should use uniform bucket level access', () => {
      const result = generateSpaBucketsTf([{ name: 'app' }]);
      expect(result).toContain('uniform_bucket_level_access = true');
    });

    it('should convert service name to terraform-safe ID', () => {
      const result = generateSpaBucketsTf([{ name: 'react-app' }]);
      expect(result).toContain('"react_app_spa"');
      expect(result).toContain('react_app_spa_public');
    });
  });

  describe('multiple SPA services', () => {
    it('should generate buckets for all services', () => {
      const result = generateSpaBucketsTf([
        { name: 'frontend' },
        { name: 'admin-panel' },
      ]);
      expect(result).toContain('frontend_spa');
      expect(result).toContain('admin_panel_spa');
    });

    it('should generate IAM bindings for all services', () => {
      const result = generateSpaBucketsTf([{ name: 'app' }, { name: 'docs' }]);
      expect(result).toContain('app_spa_public');
      expect(result).toContain('docs_spa_public');
    });
  });

  describe('bucket naming', () => {
    it('should use project_name variable in bucket name', () => {
      const result = generateSpaBucketsTf([{ name: 'frontend' }]);
      expect(result).toContain(
        '${var.project_name}-frontend-spa-${var.gcp_project_id}',
      );
    });
  });

  describe('generator comment', () => {
    it('should include header comments', () => {
      const result = generateSpaBucketsTf([{ name: 'app' }]);
      expect(result).toContain('SPA Cloud Storage Buckets');
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });
});
