/**
 * Generate Terraform for SPA Cloud Storage buckets
 *
 * Creates Cloud Storage buckets for SPA services as part of base infrastructure.
 * The backend bucket (CDN) and routing are configured in loadbalancer.tf
 */

import { toTerraformId } from '../../utils/terraform/to-terraform-id.ts';

/**
 * SPA service configuration
 */
export interface SpaServiceConfig {
  /** Service name (e.g., "react-app") */
  name: string;
  /** Domain for CORS (optional - can be added later via loadbalancer) */
  domain?: string;
}

/**
 * Generate spa-buckets.tf with Cloud Storage buckets for SPA services
 */
export function generateSpaBucketsTf(services: SpaServiceConfig[]): string {
  if (services.length === 0) {
    return `# No SPA services configured
# Generated by: npx tsdevstack infra:generate
`;
  }

  const buckets = services
    .map(
      (service) => `
# Cloud Storage bucket for ${service.name} SPA
resource "google_storage_bucket" "${toTerraformId(service.name)}_spa" {
  name          = "\${var.project_name}-${service.name}-spa-\${var.gcp_project_id}"
  location      = "US"
  force_destroy = true

  uniform_bucket_level_access = true

  website {
    main_page_suffix = "index.html"
    not_found_page   = "index.html"  # SPA routing - all paths serve index.html
  }
}

# Make bucket publicly readable
resource "google_storage_bucket_iam_member" "${toTerraformId(service.name)}_spa_public" {
  bucket = google_storage_bucket.${toTerraformId(service.name)}_spa.name
  role   = "roles/storage.objectViewer"
  member = "allUsers"
}`,
    )
    .join('\n');

  return `# SPA Cloud Storage Buckets
# Generated by: npx tsdevstack infra:generate
#
# Creates Cloud Storage buckets for SPA services with website config.
# CDN and load balancer routing are configured separately in loadbalancer.tf
${buckets}
`;
}
