/**
 * Generate main.tf with Terraform configuration, provider, and backend
 */

import type { GCPInfraConfig } from '../../types/index.ts';

export function generateMainTf(config: GCPInfraConfig): string {
  const { stateBucket, environment } = config;

  return `# Terraform configuration
# Generated by: npx tsdevstack infra:generate

terraform {
  required_version = ">= 1.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }

  backend "gcs" {
    bucket = "${stateBucket}"
    prefix = "${environment}"
  }
}

provider "google" {
  project = var.gcp_project_id
  region  = var.gcp_region
}
`;
}
