import { describe, it, expect } from '@rstest/core';
import { generateOutputsTf } from './generate-outputs-tf';

describe('generateOutputsTf', () => {
  describe('VPC outputs', () => {
    it('should output vpc_name', () => {
      const result = generateOutputsTf();
      expect(result).toContain('output "vpc_name"');
      expect(result).toContain('value       = google_compute_network.vpc.name');
    });

    it('should output vpc_id', () => {
      const result = generateOutputsTf();
      expect(result).toContain('output "vpc_id"');
      expect(result).toContain('value       = google_compute_network.vpc.id');
    });
  });

  describe('subnet outputs', () => {
    it('should output subnet_name', () => {
      const result = generateOutputsTf();
      expect(result).toContain('output "subnet_name"');
      expect(result).toContain(
        'value       = google_compute_subnetwork.subnet.name',
      );
    });

    it('should output subnet_id', () => {
      const result = generateOutputsTf();
      expect(result).toContain('output "subnet_id"');
      expect(result).toContain(
        'value       = google_compute_subnetwork.subnet.id',
      );
    });
  });

  describe('private service connection outputs', () => {
    it('should output peering name', () => {
      const result = generateOutputsTf();
      expect(result).toContain('output "private_service_connection_peering"');
      expect(result).toContain(
        'google_service_networking_connection.private_service_connection.peering',
      );
    });
  });

  describe('database outputs', () => {
    it('should output database_instance_name', () => {
      const result = generateOutputsTf();
      expect(result).toContain('output "database_instance_name"');
      expect(result).toContain('google_sql_database_instance.postgres.name');
    });

    it('should output database_connection_name', () => {
      const result = generateOutputsTf();
      expect(result).toContain('output "database_connection_name"');
      expect(result).toContain(
        'google_sql_database_instance.postgres.connection_name',
      );
    });

    it('should output database_private_ip', () => {
      const result = generateOutputsTf();
      expect(result).toContain('output "database_private_ip"');
      expect(result).toContain(
        'google_sql_database_instance.postgres.private_ip_address',
      );
    });
  });

  describe('redis outputs', () => {
    it('should output redis_host', () => {
      const result = generateOutputsTf();
      expect(result).toContain('output "redis_host"');
      expect(result).toContain('google_redis_instance.redis.host');
    });

    it('should output redis_port', () => {
      const result = generateOutputsTf();
      expect(result).toContain('output "redis_port"');
      expect(result).toContain('google_redis_instance.redis.port');
    });

    it('should output redis_current_location_id', () => {
      const result = generateOutputsTf();
      expect(result).toContain('output "redis_current_location_id"');
      expect(result).toContain(
        'google_redis_instance.redis.current_location_id',
      );
    });

    it('should output redis_auth_string as sensitive', () => {
      const result = generateOutputsTf();
      expect(result).toContain('output "redis_auth_string"');
      expect(result).toContain('google_redis_instance.redis.auth_string');
      expect(result).toContain('sensitive   = true');
    });
  });

  describe('output descriptions', () => {
    it('should include descriptions for all outputs', () => {
      const result = generateOutputsTf();
      // Count occurrences of 'description'
      const descriptionCount = (result.match(/description\s*=/g) || []).length;
      // Should have at least 10 outputs (VPC, subnet, service accounts, database, redis, artifact registry)
      expect(descriptionCount).toBeGreaterThanOrEqual(10);
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateOutputsTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateOutputsTf();
      expect(result).toMatchSnapshot();
    });
  });
});
