/**
 * Generate storage.tf with GCS buckets for object storage
 *
 * Creates:
 * - GCS buckets with for_each over configured bucket names
 * - Uniform bucket-level access (no ACLs)
 * - CORS configuration (allow all origins — presigned URLs control access)
 * - Soft delete policy with 7-day retention
 * - IAM: roles/storage.objectUser for all service accounts
 * - IAM: roles/iam.serviceAccountTokenCreator for presigned URL signing
 *
 * force_destroy = true allows Terraform to delete non-empty buckets.
 * WARNING: This is permanent — NOT recoverable.
 */

import type { GCPInfraConfig } from '../../types/config.ts';

export function generateGcsStorageTf(config: GCPInfraConfig): string {
  if (config.storageBuckets.length === 0) {
    return '';
  }

  const bucketMap = config.storageBuckets
    .map(
      (b) => `    "${b}" = "${config.projectName}-${b}-${config.environment}"`,
    )
    .join('\n');

  return `# GCS Object Storage Buckets
# Generated by: npx tsdevstack infra:generate

locals {
  storage_buckets = {
${bucketMap}
  }
}

# =============================================================================
# GCS Buckets
# =============================================================================

resource "google_storage_bucket" "storage" {
  for_each = local.storage_buckets

  name          = each.value
  location      = var.gcp_region
  project       = var.gcp_project_id
  force_destroy = true

  uniform_bucket_level_access = true

  cors {
    origin          = ["*"]
    method          = ["GET", "PUT", "POST", "DELETE", "HEAD"]
    response_header = ["ETag", "Content-Length", "Content-Type"]
    max_age_seconds = 3600
  }

  soft_delete_policy {
    retention_duration_seconds = 604800  # 7 days
  }
}

# =============================================================================
# IAM — grant storage.objectUser to all runtime service accounts
# =============================================================================

resource "google_storage_bucket_iam_member" "storage_object_user" {
  for_each = {
    for pair in setproduct(keys(local.storage_buckets), local.services) :
    "\${pair[0]}-\${pair[1]}" => {
      bucket  = pair[0]
      service = pair[1]
    }
  }

  bucket = google_storage_bucket.storage[each.value.bucket].name
  role   = "roles/storage.objectUser"
  member = "serviceAccount:\${google_service_account.runtime[each.value.service].email}"
}

# =============================================================================
# IAM — grant serviceAccountTokenCreator for presigned URL signing
# Required for GCS presigned URL generation via Application Default Credentials
# =============================================================================

resource "google_project_iam_member" "storage_token_creator" {
  for_each = toset(local.services)

  project = var.gcp_project_id
  role    = "roles/iam.serviceAccountTokenCreator"
  member  = "serviceAccount:\${google_service_account.runtime[each.key].email}"
}

# =============================================================================
# Output
# =============================================================================

output "storage_buckets" {
  description = "Storage bucket names and metadata"
  value = {
    for key, bucket in google_storage_bucket.storage :
    key => {
      name     = bucket.name
      location = bucket.location
      url      = bucket.url
    }
  }
}
`;
}
