import { describe, it, expect } from '@rstest/core';
import { generateRedisTf } from './generate-redis-tf';

describe('generateRedisTf', () => {
  describe('Redis instance', () => {
    it('should create Memorystore Redis instance', () => {
      const result = generateRedisTf();
      expect(result).toContain('resource "google_redis_instance" "redis"');
    });

    it('should use project name variable for instance name', () => {
      const result = generateRedisTf();
      expect(result).toContain('name           = "${var.project_name}-redis"');
    });

    it('should use variable for tier', () => {
      const result = generateRedisTf();
      expect(result).toContain('tier           = var.redis_tier');
    });

    it('should use variable for memory size', () => {
      const result = generateRedisTf();
      expect(result).toContain('memory_size_gb = var.redis_memory_gb');
    });

    it('should use variable for region', () => {
      const result = generateRedisTf();
      expect(result).toContain('region         = var.gcp_region');
    });
  });

  describe('network configuration', () => {
    it('should connect to VPC network', () => {
      const result = generateRedisTf();
      expect(result).toContain(
        'authorized_network = google_compute_network.vpc.id',
      );
    });

    it('should use private service access', () => {
      const result = generateRedisTf();
      expect(result).toContain('connect_mode       = "PRIVATE_SERVICE_ACCESS"');
    });
  });

  describe('Redis version', () => {
    it('should use Redis 7.0', () => {
      const result = generateRedisTf();
      expect(result).toContain('redis_version = "REDIS_7_0"');
    });
  });

  describe('auth configuration', () => {
    it('should enable AUTH', () => {
      const result = generateRedisTf();
      expect(result).toContain('auth_enabled = true');
    });

    it('should NOT set auth_string (GCP auto-generates it)', () => {
      const result = generateRedisTf();
      expect(result).not.toContain('auth_string  = var.');
    });
  });

  describe('eviction policy', () => {
    it('should set noeviction policy for BullMQ compatibility', () => {
      const result = generateRedisTf();
      expect(result).toContain('redis_configs = {');
      expect(result).toContain('"maxmemory-policy" = "noeviction"');
    });
  });

  describe('maintenance policy', () => {
    it('should configure maintenance window', () => {
      const result = generateRedisTf();
      expect(result).toContain('maintenance_policy');
      expect(result).toContain('weekly_maintenance_window');
    });

    it('should schedule maintenance on Sunday', () => {
      const result = generateRedisTf();
      expect(result).toContain('day = "SUNDAY"');
    });

    it('should schedule maintenance at 4 AM', () => {
      const result = generateRedisTf();
      expect(result).toContain('hours   = 4');
    });
  });

  describe('dependencies', () => {
    it('should depend on private service connection', () => {
      const result = generateRedisTf();
      expect(result).toContain(
        'depends_on = [google_service_networking_connection.private_service_connection]',
      );
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateRedisTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateRedisTf();
      expect(result).toMatchSnapshot();
    });
  });
});
