import { describe, it, expect } from '@rstest/core';
import { generateMainTf } from './generate-main-tf';
import type { GCPInfraConfig } from '../../types/index.ts';

describe('generateMainTf', () => {
  const baseConfig: GCPInfraConfig = {
    provider: 'gcp',
    projectName: 'my-app',
    environment: 'dev',
    gcpProjectId: 'gcp-project-123',
    region: 'us-central1',
    stateBucket: 'my-app-tf-state',
    baseDomain: 'example.com',
    database: {
      tier: 'db-f1-micro',
      storageSizeGb: 10,
      deletionProtection: true,
      ha: false,
      backup: false,
    },
    redis: { tier: 'BASIC', memoryGb: 1 },
    servicesWithDatabase: [],
    services: {},
    frontends: {},
    spas: {},
    workers: {},
    scheduledJobs: {},
    allDeployables: {},
  };

  describe('terraform block', () => {
    it('should include required terraform version', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('required_version = ">= 1.0"');
    });

    it('should include google provider source', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('source  = "hashicorp/google"');
    });

    it('should include google provider version', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('version = "~> 5.0"');
    });
  });

  describe('backend configuration', () => {
    it('should configure GCS backend with state bucket', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('backend "gcs"');
      expect(result).toContain('bucket = "my-app-tf-state"');
    });

    it('should use environment as prefix', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('prefix = "dev"');
    });

    it('should use different prefix for different environments', () => {
      const prodConfig = { ...baseConfig, environment: 'prod' };
      const result = generateMainTf(prodConfig);
      expect(result).toContain('prefix = "prod"');
    });
  });

  describe('provider configuration', () => {
    it('should configure google provider with project variable', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('provider "google"');
      expect(result).toContain('project = var.gcp_project_id');
    });

    it('should configure google provider with region variable', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('region  = var.gcp_region');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot for dev environment', () => {
      const result = generateMainTf(baseConfig);
      expect(result).toMatchSnapshot();
    });

    it('should match snapshot for prod environment', () => {
      const prodConfig: GCPInfraConfig = {
        ...baseConfig,
        environment: 'prod',
        stateBucket: 'production-app-tf-state',
      };
      const result = generateMainTf(prodConfig);
      expect(result).toMatchSnapshot();
    });
  });
});
