/**
 * Generate cloud-scheduler.tf with Cloud Scheduler jobs
 *
 * Creates scheduled HTTP jobs that call service endpoints with OIDC authentication.
 * Combined with @ApiExcludeController() and SchedulerGuard, provides secure scheduled tasks.
 */

import type { ScheduledJobConfig } from '../../types/index.ts';
import { toTerraformId } from '../../utils/terraform/to-terraform-id.ts';

/**
 * Generate cloud-scheduler.tf content
 *
 * Creates:
 * - Service account for Cloud Scheduler
 * - IAM binding for run.invoker role per target service
 * - Cloud Scheduler job per scheduled task with OIDC authentication
 */
export function generateCloudSchedulerTf(jobs: ScheduledJobConfig[]): string {
  if (jobs.length === 0) {
    return `# No scheduled jobs configured
# Add scheduledJobs in infrastructure.json to generate Cloud Scheduler resources
`;
  }

  // Get unique target services
  const targetServices = Array.from(new Set(jobs.map((j) => j.targetService)));

  // Generate data sources to reference existing Cloud Run services
  // Services are deployed via gcloud, not Terraform, so we use data sources
  const dataSources = targetServices
    .map((service) => {
      const tfId = toTerraformId(service);
      return `
# Data source for existing ${service} Cloud Run service
data "google_cloud_run_v2_service" "${tfId}" {
  name     = "${service}"
  location = var.gcp_region
}`;
    })
    .join('\n');

  // Generate IAM bindings for each target service
  const iamBindings = targetServices
    .map((service) => {
      const tfId = toTerraformId(service);
      return `
# Allow scheduler to invoke ${service}
resource "google_cloud_run_v2_service_iam_member" "scheduler_${tfId}" {
  name     = data.google_cloud_run_v2_service.${tfId}.name
  location = var.gcp_region
  role     = "roles/run.invoker"
  member   = "serviceAccount:\${google_service_account.scheduler.email}"
}`;
    })
    .join('\n');

  // Generate scheduler jobs
  const schedulerJobs = jobs
    .map((job) => {
      const tfId = toTerraformId(job.name);
      const serviceTfId = toTerraformId(job.targetService);
      const method = job.method || 'POST';
      const timeout = job.httpTimeout || 300;
      const timezone = job.timezone || 'UTC';

      return `
# Scheduled job: ${job.name}
resource "google_cloud_scheduler_job" "${tfId}" {
  name     = "${job.name}"
  schedule = "${job.schedule}"
  time_zone = "${timezone}"

  http_target {
    uri         = "\${data.google_cloud_run_v2_service.${serviceTfId}.uri}${job.endpoint}"
    http_method = "${method}"

    oidc_token {
      service_account_email = google_service_account.scheduler.email
      audience              = data.google_cloud_run_v2_service.${serviceTfId}.uri
    }
  }

  retry_config {
    retry_count          = 3
    min_backoff_duration = "5s"
    max_backoff_duration = "3600s"
    max_doublings        = 5
  }

  attempt_deadline = "${timeout}s"

  depends_on = [google_cloud_run_v2_service_iam_member.scheduler_${serviceTfId}]
}`;
    })
    .join('\n');

  return `# Cloud Scheduler Infrastructure
# Generated by: npx tsdevstack infra:generate
#
# Scheduled jobs call service endpoints with OIDC authentication.
# Services validate tokens using SchedulerGuard from @tsdevstack/nest-common.

# ─────────────────────────────────────────
# Data Sources (reference existing Cloud Run services)
# ─────────────────────────────────────────
${dataSources}

# ─────────────────────────────────────────
# Service Account
# ─────────────────────────────────────────

# Service account for Cloud Scheduler
resource "google_service_account" "scheduler" {
  account_id   = "\${var.project_name}-scheduler"
  display_name = "Cloud Scheduler Service Account"
  description  = "Service account for Cloud Scheduler to invoke Cloud Run services"
}

# ─────────────────────────────────────────
# IAM Bindings
# ─────────────────────────────────────────
${iamBindings}

# ─────────────────────────────────────────
# Scheduled Jobs
# ─────────────────────────────────────────
${schedulerJobs}
`;
}
