import { describe, it, expect } from '@rstest/core';
import { generateNetworkTf } from './generate-network-tf';

describe('generateNetworkTf', () => {
  describe('VPC resource', () => {
    it('should create VPC network resource', () => {
      const result = generateNetworkTf();
      expect(result).toContain('resource "google_compute_network" "vpc"');
    });

    it('should disable auto-create subnetworks', () => {
      const result = generateNetworkTf();
      expect(result).toContain('auto_create_subnetworks = false');
    });

    it('should use project name variable for VPC name', () => {
      const result = generateNetworkTf();
      expect(result).toContain(
        'name                    = "${var.project_name}-vpc"',
      );
    });
  });

  describe('subnet resource', () => {
    it('should create subnet resource', () => {
      const result = generateNetworkTf();
      expect(result).toContain('resource "google_compute_subnetwork" "subnet"');
    });

    it('should enable private google access', () => {
      const result = generateNetworkTf();
      expect(result).toContain('private_ip_google_access = true');
    });

    it('should configure subnet CIDR range', () => {
      const result = generateNetworkTf();
      expect(result).toContain('ip_cidr_range            = "10.0.0.0/20"');
    });

    it('should reference VPC network', () => {
      const result = generateNetworkTf();
      expect(result).toContain(
        'network                  = google_compute_network.vpc.id',
      );
    });

    it('should mention Direct VPC Egress in description', () => {
      const result = generateNetworkTf();
      expect(result).toContain('Direct VPC Egress');
    });
  });

  describe('private service access', () => {
    it('should create global address for private IP range', () => {
      const result = generateNetworkTf();
      expect(result).toContain(
        'resource "google_compute_global_address" "private_ip_range"',
      );
    });

    it('should configure address for VPC peering', () => {
      const result = generateNetworkTf();
      expect(result).toContain('purpose       = "VPC_PEERING"');
      expect(result).toContain('address_type  = "INTERNAL"');
    });

    it('should create service networking connection', () => {
      const result = generateNetworkTf();
      expect(result).toContain(
        'resource "google_service_networking_connection" "private_service_connection"',
      );
    });

    it('should connect to servicenetworking.googleapis.com', () => {
      const result = generateNetworkTf();
      expect(result).toContain(
        'service                 = "servicenetworking.googleapis.com"',
      );
    });
  });

  describe('firewall resource', () => {
    it('should create firewall rule', () => {
      const result = generateNetworkTf();
      expect(result).toContain(
        'resource "google_compute_firewall" "allow_internal"',
      );
    });

    it('should allow TCP traffic', () => {
      const result = generateNetworkTf();
      expect(result).toContain('protocol = "tcp"');
    });

    it('should allow UDP traffic', () => {
      const result = generateNetworkTf();
      expect(result).toContain('protocol = "udp"');
    });

    it('should allow ICMP traffic', () => {
      const result = generateNetworkTf();
      expect(result).toContain('protocol = "icmp"');
    });

    it('should restrict to internal source ranges', () => {
      const result = generateNetworkTf();
      expect(result).toContain('source_ranges = ["10.0.0.0/8"]');
    });
  });

  describe('private DNS zone', () => {
    it('should create private DNS zone for run.app', () => {
      const result = generateNetworkTf();
      expect(result).toContain(
        'resource "google_dns_managed_zone" "run_app_internal"',
      );
    });

    it('should create A records for run.app', () => {
      const result = generateNetworkTf();
      expect(result).toContain('resource "google_dns_record_set" "run_app_a"');
    });

    it('should create wildcard A record for *.run.app', () => {
      const result = generateNetworkTf();
      expect(result).toContain(
        'resource "google_dns_record_set" "run_app_wildcard"',
      );
    });

    it('should point to private.googleapis.com IPs', () => {
      const result = generateNetworkTf();
      expect(result).toContain('199.36.153.8');
      expect(result).toContain('199.36.153.9');
      expect(result).toContain('199.36.153.10');
      expect(result).toContain('199.36.153.11');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateNetworkTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot', () => {
      const result = generateNetworkTf();
      expect(result).toMatchSnapshot();
    });
  });
});
