/**
 * Generate database.tf with Cloud SQL instance, databases, and users
 */

import type { GCPInfraConfig } from '../../types/index.ts';
import { toTerraformId } from '../../utils/terraform/to-terraform-id.ts';
import { toTfVarSuffix } from '../../utils/terraform/to-tf-var-suffix.ts';

/**
 * Generate database.tf content
 *
 * Creates:
 * - Cloud SQL PostgreSQL instance
 * - One database per service with hasDatabase=true
 * - One database user per service with password from Secret Manager
 */
export function generateDatabaseTf(config: GCPInfraConfig): string {
  const servicesWithDb = config.servicesWithDatabase.filter(
    (s) => s.hasDatabase,
  );

  // Generate database resources for each service
  const databaseResources = servicesWithDb
    .map(
      (service) => `
# Database for ${service.name}
resource "google_sql_database" "${toTerraformId(service.name)}" {
  name     = "${service.name}"
  instance = google_sql_database_instance.postgres.name
}`,
    )
    .join('\n');

  // Generate user resources for each service (one user per database)
  const userResources = servicesWithDb
    .map((service) => {
      const tfId = toTerraformId(service.name);
      const varSuffix = toTfVarSuffix(service.name);
      return `
# Database user for ${service.name}
resource "google_sql_user" "${tfId}_user" {
  name     = "${service.name}"
  instance = google_sql_database_instance.postgres.name
  password = var.db_${varSuffix}_password
}`;
    })
    .join('\n');

  return `# Cloud SQL Database Infrastructure
# Generated by: npx tsdevstack infra:generate

# 1. Cloud SQL PostgreSQL Instance
resource "google_sql_database_instance" "postgres" {
  name             = "\${var.project_name}-postgres"
  database_version = "POSTGRES_15"
  region           = var.gcp_region

  # Prevent accidental deletion
  deletion_protection = var.database_deletion_protection

  settings {
    tier              = var.database_tier
    availability_type = var.database_ha ? "REGIONAL" : "ZONAL"
    disk_size         = var.database_disk_size
    disk_autoresize   = true
    disk_type         = "PD_SSD"

    ip_configuration {
      ipv4_enabled    = false  # No public IP - private only
      private_network = google_compute_network.vpc.id
    }

    backup_configuration {
      enabled                        = var.database_backup
      binary_log_enabled             = false
      point_in_time_recovery_enabled = var.database_backup
      start_time                     = "03:00"  # 3 AM UTC

      backup_retention_settings {
        retained_backups = var.database_backup ? 7 : 0
      }
    }

    maintenance_window {
      day          = 7  # Sunday
      hour         = 4  # 4 AM UTC
      update_track = "stable"
    }

    insights_config {
      query_insights_enabled  = true
      query_string_length     = 1024
      record_application_tags = true
      record_client_address   = true
    }
  }

  depends_on = [google_service_networking_connection.private_service_connection]
}
${databaseResources}

# 2. Database Users (one per service)
# Passwords are passed via TF_VAR_db_{prefix}_password
# - CI: Read from environment variables (DB_AUTH_PASSWORD, etc.)
# - Local: Fetched from Secret Manager via cloud-secrets:get
${userResources}
`;
}
