/**
 * Generate Terraform IAM Configuration
 *
 * Creates per-service runtime service accounts with scoped secret access.
 * Each service can only access:
 * - {projectName}-shared-* secrets (shared across all services)
 * - {projectName}-{serviceName}-* secrets (service-specific)
 *
 * Also creates Kong Gateway service account with access to shared secrets.
 */

/**
 * Service info for IAM generation
 */
export interface ServiceIamInfo {
  name: string;
}

/**
 * Generate iam.tf with per-service runtime service accounts
 */
export function generateIamTf(services: ServiceIamInfo[]): string {
  // Build the locals block for service list
  const serviceNames = services.map((s) => `"${s.name}"`).join(', ');

  return `# Per-service runtime service accounts with scoped secret access
# Generated by: npx tsdevstack infra:generate

locals {
  services = [${serviceNames}]
}

# Get project number (required for IAM conditions - resource.name uses project number, not ID)
data "google_project" "current" {
  project_id = var.gcp_project_id
}

# Per-service runtime service accounts
# Note: account_id max 30 chars, so we use "-rt" suffix instead of "-runtime"
resource "google_service_account" "runtime" {
  for_each = toset(local.services)

  account_id   = "\${var.project_name}-\${each.key}-rt"
  display_name = "Runtime SA for \${each.key}"
  description  = "Service account used by \${each.key} Cloud Run service"
}

# Kong Gateway service account
# Separate from per-service SAs as Kong is infrastructure, not a microservice
resource "google_service_account" "kong" {
  account_id   = "\${var.project_name}-kong-rt"
  display_name = "Runtime SA for Kong Gateway"
  description  = "Service account used by Kong Gateway Cloud Run service"
}

# Grant Cloud SQL Client role to all runtime SAs
resource "google_project_iam_member" "runtime_cloudsql" {
  for_each = toset(local.services)

  project = var.gcp_project_id
  role    = "roles/cloudsql.client"
  member  = "serviceAccount:\${google_service_account.runtime[each.key].email}"
}

# Grant Secret Manager access with scoped conditions
# Each service can only access shared secrets and its own service-specific secrets
# Note: resource.name in IAM uses project NUMBER (not ID), so we use data.google_project.current.number
resource "google_project_iam_member" "runtime_secrets" {
  for_each = toset(local.services)

  project = var.gcp_project_id
  role    = "roles/secretmanager.secretAccessor"
  member  = "serviceAccount:\${google_service_account.runtime[each.key].email}"

  condition {
    title       = "\${each.key}-secrets-only"
    description = "Allow access to shared secrets and \${each.key}-specific secrets only"
    expression  = "resource.name.startsWith(\\"projects/\${data.google_project.current.number}/secrets/\${var.project_name}-shared-\\") || resource.name.startsWith(\\"projects/\${data.google_project.current.number}/secrets/\${var.project_name}-\${each.key}-\\")"
  }
}

# Kong Gateway secret access (shared secrets only: KONG_TRUST_TOKEN, REDIS_HOST, REDIS_PORT, REDIS_PASSWORD)
resource "google_project_iam_member" "kong_secrets" {
  project = var.gcp_project_id
  role    = "roles/secretmanager.secretAccessor"
  member  = "serviceAccount:\${google_service_account.kong.email}"

  condition {
    title       = "kong-shared-secrets-only"
    description = "Allow Kong to access shared secrets only"
    expression  = "resource.name.startsWith(\\"projects/\${data.google_project.current.number}/secrets/\${var.project_name}-shared-\\")"
  }
}
`;
}
