/**
 * Generate variables.tf with input variable definitions
 */

import type { ServiceDatabaseInfo } from '../../types/index.ts';
import { toTfVarSuffix } from '../../utils/terraform/to-tf-var-suffix.ts';

export function generateVariablesTf(
  servicesWithDatabase: ServiceDatabaseInfo[],
): string {
  const servicesWithDb = servicesWithDatabase.filter((s) => s.hasDatabase);

  // Generate password variables for each service with database
  // Default empty string allows targeted applies (e.g., scheduler only) to work
  // Real password must be provided via TF_VAR_* when creating/updating DB resources
  const passwordVariables = servicesWithDb
    .map((service) => {
      const suffix = toTfVarSuffix(service.name);
      return `
variable "db_${suffix}_password" {
  description = "Database password for ${service.name}"
  type        = string
  sensitive   = true
  default     = ""
}`;
    })
    .join('\n');

  return `# Input variables
# Generated by: npx tsdevstack infra:generate

variable "project_name" {
  description = "Project name used for resource naming"
  type        = string
}

variable "gcp_project_id" {
  description = "GCP project ID"
  type        = string
}

variable "gcp_region" {
  description = "GCP region for resources"
  type        = string
}

# ─────────────────────────────────────────
# Database (Cloud SQL)
# ─────────────────────────────────────────

variable "database_deletion_protection" {
  description = "Enable deletion protection on Cloud SQL instance"
  type        = bool
  default     = true
}

variable "database_tier" {
  description = "Cloud SQL instance tier (e.g., db-f1-micro, db-g1-small)"
  type        = string
  default     = "db-f1-micro"
}

variable "database_disk_size" {
  description = "Cloud SQL disk size in GB"
  type        = number
  default     = 10
}

variable "database_ha" {
  description = "Enable high availability (REGIONAL)"
  type        = bool
  default     = false
}

variable "database_backup" {
  description = "Enable automated backups"
  type        = bool
  default     = false
}
${passwordVariables}

# ─────────────────────────────────────────
# Redis (Memorystore)
# ─────────────────────────────────────────

variable "redis_tier" {
  description = "Memorystore Redis tier (BASIC or STANDARD_HA)"
  type        = string
  default     = "BASIC"
}

variable "redis_memory_gb" {
  description = "Redis memory size in GB"
  type        = number
  default     = 1
}`;
}
