import { describe, it, expect } from '@rstest/core';
import { generateArtifactRegistryTf } from './generate-artifact-registry-tf';

describe('generateArtifactRegistryTf', () => {
  it('should return a string', () => {
    const result = generateArtifactRegistryTf();
    expect(typeof result).toBe('string');
  });

  it('should contain artifact registry resource', () => {
    const result = generateArtifactRegistryTf();
    expect(result).toContain('google_artifact_registry_repository');
    expect(result).toContain(
      'resource "google_artifact_registry_repository" "services"',
    );
  });

  it('should configure Docker format', () => {
    const result = generateArtifactRegistryTf();
    expect(result).toContain('format        = "DOCKER"');
  });

  it('should use var.gcp_region for location', () => {
    const result = generateArtifactRegistryTf();
    expect(result).toContain('location      = var.gcp_region');
  });

  it('should use var.project_name for repository_id', () => {
    const result = generateArtifactRegistryTf();
    expect(result).toContain('repository_id = var.project_name');
  });

  it('should include cleanup policies', () => {
    const result = generateArtifactRegistryTf();
    expect(result).toContain('cleanup_policies');
    expect(result).toContain('keep-recent');
    expect(result).toContain('keep_count');
  });

  it('should include generator comment', () => {
    const result = generateArtifactRegistryTf();
    expect(result).toContain('Generated by');
    expect(result).toContain('npx tsdevstack infra:generate');
  });
});
