import { describe, it, expect } from '@rstest/core';
import { generateIamTf } from './generate-iam-tf';

describe('generateIamTf', () => {
  const singleService = [{ name: 'auth-service' }];
  const multipleServices = [
    { name: 'auth-service' },
    { name: 'bff-service' },
    { name: 'frontend' },
  ];

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });

    it('should describe per-service runtime accounts', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('Per-service runtime service accounts');
    });
  });

  describe('locals block', () => {
    it('should define services list with single service', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('locals {');
      expect(result).toContain('services = ["auth-service"]');
    });

    it('should define services list with multiple services', () => {
      const result = generateIamTf(multipleServices);
      expect(result).toContain(
        'services = ["auth-service", "bff-service", "frontend"]',
      );
    });
  });

  describe('google_project data source', () => {
    it('should include data source to get project number', () => {
      const result = generateIamTf(singleService);
      // Required because IAM conditions use project number, not project ID
      expect(result).toContain('data "google_project" "current"');
      expect(result).toContain('project_id = var.gcp_project_id');
    });
  });

  describe('service account resource', () => {
    it('should create google_service_account.runtime with for_each', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('resource "google_service_account" "runtime"');
      expect(result).toContain('for_each = toset(local.services)');
    });

    it('should use project_name and each.key for account_id with -rt suffix', () => {
      const result = generateIamTf(singleService);
      // Note: -rt suffix used because GCP account_id max 30 chars
      expect(result).toContain(
        'account_id   = "${var.project_name}-${each.key}-rt"',
      );
    });

    it('should set display_name using each.key', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('display_name = "Runtime SA for ${each.key}"');
    });

    it('should set description using each.key', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain(
        'description  = "Service account used by ${each.key} Cloud Run service"',
      );
    });
  });

  describe('Cloud SQL IAM binding', () => {
    it('should create google_project_iam_member.runtime_cloudsql', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain(
        'resource "google_project_iam_member" "runtime_cloudsql"',
      );
    });

    it('should use for_each for all services', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('for_each = toset(local.services)');
    });

    it('should grant cloudsql.client role', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('role    = "roles/cloudsql.client"');
    });

    it('should reference the service account email', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain(
        'member  = "serviceAccount:${google_service_account.runtime[each.key].email}"',
      );
    });
  });

  describe('Secret Manager IAM binding with conditions', () => {
    it('should create google_project_iam_member.runtime_secrets', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain(
        'resource "google_project_iam_member" "runtime_secrets"',
      );
    });

    it('should grant secretmanager.secretAccessor role', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain(
        'role    = "roles/secretmanager.secretAccessor"',
      );
    });

    it('should include condition block', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('condition {');
      expect(result).toContain('title       = "${each.key}-secrets-only"');
    });

    it('should include condition description', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain(
        'description = "Allow access to shared secrets and ${each.key}-specific secrets only"',
      );
    });

    it('should include CEL expression for shared secrets using project number', () => {
      const result = generateIamTf(singleService);
      // Uses project number (not ID) because resource.name in IAM uses project number
      expect(result).toContain(
        'resource.name.startsWith(\\"projects/${data.google_project.current.number}/secrets/${var.project_name}-shared-\\")',
      );
    });

    it('should include CEL expression for service-specific secrets using project number', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain(
        'resource.name.startsWith(\\"projects/${data.google_project.current.number}/secrets/${var.project_name}-${each.key}-\\")',
      );
    });

    it('should combine shared and service-specific access with OR', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('||');
    });
  });

  describe('Kong Gateway service account', () => {
    it('should create google_service_account.kong', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('resource "google_service_account" "kong"');
    });

    it('should use project_name for Kong account_id with -kong-rt suffix', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('account_id   = "${var.project_name}-kong-rt"');
    });

    it('should set Kong display_name', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('display_name = "Runtime SA for Kong Gateway"');
    });

    it('should create Kong secret access IAM binding', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain(
        'resource "google_project_iam_member" "kong_secrets"',
      );
    });

    it('should grant Kong secretmanager.secretAccessor role', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain(
        'member  = "serviceAccount:${google_service_account.kong.email}"',
      );
    });

    it('should include Kong condition for shared secrets only', () => {
      const result = generateIamTf(singleService);
      expect(result).toContain('title       = "kong-shared-secrets-only"');
      expect(result).toContain('Allow Kong to access shared secrets only');
    });
  });

  describe('snapshot', () => {
    it('should match snapshot for single service', () => {
      const result = generateIamTf(singleService);
      expect(result).toMatchSnapshot();
    });

    it('should match snapshot for multiple services', () => {
      const result = generateIamTf(multipleServices);
      expect(result).toMatchSnapshot();
    });
  });
});
