/**
 * Generate cloud-scheduler.tf with Cloud Scheduler jobs
 *
 * Creates scheduled HTTP jobs that call service endpoints with OIDC authentication.
 * Combined with @ApiExcludeController() and SchedulerGuard, provides secure scheduled tasks.
 *
 * Uses computed Cloud Run URLs (deterministic pattern) instead of data sources,
 * so this file can be generated without services existing yet.
 */

import type { ScheduledJobConfig } from '../../types/index.ts';
import { toTerraformId } from '../../utils/terraform/to-terraform-id.ts';

/**
 * Generate cloud-scheduler.tf content
 *
 * Creates:
 * - Locals block with computed Cloud Run service URIs
 * - Service account for Cloud Scheduler
 * - Cloud Scheduler job per scheduled task with OIDC authentication
 *
 * IAM bindings (run.invoker) are NOT included here — they require Cloud Run
 * services to exist. Instead, deploy-schedulers sets them imperatively via
 * @google-cloud/run SDK (same pattern as setServiceInvokerPolicy for Kong/services).
 */
export function generateCloudSchedulerTf(jobs: ScheduledJobConfig[]): string {
  if (jobs.length === 0) {
    return `# No scheduled jobs configured
# Add scheduledJobs in infrastructure.json to generate Cloud Scheduler resources
`;
  }

  // Get unique target services
  const targetServices = Array.from(new Set(jobs.map((j) => j.targetService)));

  // Generate locals block with computed Cloud Run service URIs
  // Cloud Run v2 URLs follow: https://{service}-{project-number}.{region}.run.app
  // Uses data.google_project.current.number (declared in iam.tf)
  const serviceUriEntries = targetServices
    .map((service) => {
      const tfId = toTerraformId(service);
      return `    ${tfId} = "https://${service}-\${data.google_project.current.number}.\${var.gcp_region}.run.app"`;
    })
    .join('\n');

  const localsBlock = `
locals {
  scheduler_service_uris = {
${serviceUriEntries}
  }
}`;

  // Generate scheduler jobs
  const schedulerJobs = jobs
    .map((job) => {
      const tfId = toTerraformId(job.name);
      const serviceTfId = toTerraformId(job.targetService);
      const method = job.method || 'POST';
      const timeout = job.httpTimeout || 300;
      const timezone = job.timezone || 'UTC';

      return `
# Scheduled job: ${job.name}
resource "google_cloud_scheduler_job" "${tfId}" {
  name     = "${job.name}"
  schedule = "${job.schedule}"
  time_zone = "${timezone}"

  http_target {
    uri         = "\${local.scheduler_service_uris.${serviceTfId}}${job.endpoint}"
    http_method = "${method}"

    oidc_token {
      service_account_email = google_service_account.scheduler.email
      audience              = local.scheduler_service_uris.${serviceTfId}
    }
  }

  retry_config {
    retry_count          = 3
    min_backoff_duration = "5s"
    max_backoff_duration = "3600s"
    max_doublings        = 5
  }

  attempt_deadline = "${timeout}s"
}`;
    })
    .join('\n');

  return `# Cloud Scheduler Infrastructure
# Generated by: npx tsdevstack infra:generate
#
# Scheduled jobs call service endpoints with OIDC authentication.
# Services validate tokens using SchedulerGuard from @tsdevstack/nest-common.
#
# Cloud Run URLs are computed from project number (no dependency on existing services).
# IAM bindings (run.invoker) are set by deploy-schedulers via SDK, not Terraform.

# ─────────────────────────────────────────
# Computed Service URIs
# ─────────────────────────────────────────
${localsBlock}

# ─────────────────────────────────────────
# Service Account
# ─────────────────────────────────────────

# Service account for Cloud Scheduler
resource "google_service_account" "scheduler" {
  account_id   = "\${var.project_name}-scheduler"
  display_name = "Cloud Scheduler Service Account"
  description  = "Service account for Cloud Scheduler to invoke Cloud Run services"
}

# ─────────────────────────────────────────
# Scheduled Jobs
# ─────────────────────────────────────────
${schedulerJobs}
`;
}
