/**
 * Generate terraform.tfvars with actual values
 */

import type { GCPInfraConfig } from '../../types/index.ts';

export function generateTfvars(config: GCPInfraConfig): string {
  const { projectName, gcpProjectId, region, database, redis } = config;

  return `# Variable values
# Generated by: npx tsdevstack infra:generate

project_name   = "${projectName}"
gcp_project_id = "${gcpProjectId}"
gcp_region     = "${region}"

# Database (Cloud SQL)
database_deletion_protection = ${database.deletionProtection}
database_tier                = "${database.tier}"
database_disk_size           = ${database.storageSizeGb}
database_ha                  = ${database.ha ?? false}
database_backup              = ${database.backup}

# Redis (Memorystore)
redis_tier      = "${redis.tier}"
redis_memory_gb = ${redis.memoryGb ?? 1}
`;
}
