/**
 * Generate artifact-registry.tf with Docker repository
 */

export function generateArtifactRegistryTf(): string {
  return `# Artifact Registry for Docker images
# Generated by: npx tsdevstack infra:generate

resource "google_artifact_registry_repository" "services" {
  location      = var.gcp_region
  repository_id = var.project_name
  description   = "Docker images for \${var.project_name} services"
  format        = "DOCKER"

  cleanup_policies {
    id     = "keep-recent"
    action = "KEEP"
    most_recent_versions {
      keep_count = 10
    }
  }
}
`;
}
