/**
 * Generate diagnostics.tf with Azure Monitor diagnostic settings
 *
 * Sends logs from PostgreSQL and App Service to the shared
 * Log Analytics workspace (created in container-apps-env.tf).
 */

import type { AzureInfraConfig } from '../../types/config.ts';
import { toTerraformId } from '../../utils/terraform/to-terraform-id.ts';

export function generateDiagnosticsTf(config: AzureInfraConfig): string {
  const nextjsEntries = Object.entries(config.frontends);

  const nextjsDiagnostics = nextjsEntries
    .map(([name]) => {
      const tfId = toTerraformId(name);
      return generateAppServiceDiagnostic(
        `nextjs_${tfId}`,
        name,
        `azurerm_linux_web_app.nextjs_${tfId}`,
      );
    })
    .join('\n');

  return `# Diagnostic Settings
# Generated by: npx tsdevstack infra:generate
#
# Sends logs to the shared Log Analytics workspace for
# Azure Security Center compliance and operational visibility.

# =============================================================================
# Front Door Diagnostic Settings
# =============================================================================

resource "azurerm_monitor_diagnostic_setting" "frontdoor" {
  name                       = "frontdoor-diagnostics"
  target_resource_id         = azurerm_cdn_frontdoor_profile.main.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.main.id

  enabled_log {
    category = "FrontDoorAccessLog"
  }

  enabled_log {
    category = "FrontDoorHealthProbeLog"
  }

  enabled_log {
    category = "FrontDoorWebApplicationFirewallLog"
  }
}

# =============================================================================
# PostgreSQL Diagnostic Settings
# =============================================================================

resource "azurerm_monitor_diagnostic_setting" "postgres" {
  name                       = "postgres-diagnostics"
  target_resource_id         = azurerm_postgresql_flexible_server.main.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.main.id

  enabled_log {
    category = "PostgreSQLLogs"
  }

  enabled_log {
    category = "PostgreSQLFlexQueryStoreRuntime"
  }
}

# =============================================================================
# Kong App Service Diagnostic Settings
# =============================================================================
${generateAppServiceDiagnostic('kong', 'kong', 'azurerm_linux_web_app.kong')}
${nextjsDiagnostics.length > 0 ? `\n# =============================================================================\n# Next.js App Service Diagnostic Settings\n# =============================================================================\n${nextjsDiagnostics}` : ''}
`;
}

/**
 * Generate diagnostic setting for a single App Service
 */
function generateAppServiceDiagnostic(
  tfId: string,
  displayName: string,
  resourceRef: string,
): string {
  return `
resource "azurerm_monitor_diagnostic_setting" "${tfId}" {
  name                       = "${displayName}-diagnostics"
  target_resource_id         = ${resourceRef}.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.main.id

  enabled_log {
    category = "AppServiceHTTPLogs"
  }

  enabled_log {
    category = "AppServiceConsoleLogs"
  }

  enabled_log {
    category = "AppServiceAuditLogs"
  }
}`;
}
