import { describe, it, expect } from '@rstest/core';
import {
  generateSpaStorageTf,
  buildSpaStorageAccountName,
} from './generate-spa-storage-tf';
import type { AzureInfraConfig } from '../../types/config.ts';

const baseConfig: AzureInfraConfig = {
  provider: 'azure',
  projectName: 'myproject',
  environment: 'dev',
  subscriptionId: 'test-sub-id',
  location: 'eastus',
  storageAccountName: 'myprojectdevtfstate',
  database: {
    tier: 'B_Standard_B1ms',
    storageSizeGb: 32,
    deletionProtection: false,
    backup: false,
  },
  redis: { tier: 'Balanced_B0' },
  servicesWithDatabase: [],
  baseDomain: '',
  services: {},
  workers: {},
  allDeployables: {},
  spas: {},
  frontends: {},
  scheduledJobs: {},
  storageBuckets: [],
  noIndex: false,
  frontdoorPremium: false,
  kongAppServiceSku: 'B1',
  nextjsAppServiceSku: 'B1',
};

describe('buildSpaStorageAccountName', () => {
  const subId = 'test-sub-id';

  it('should combine project, env, spa name with subscription suffix', () => {
    const result = buildSpaStorageAccountName(
      'myproject',
      'dev',
      'reactapp',
      subId,
    );
    expect(result).toBe('myprojectdevreacestsubid');
  });

  it('should strip non-alphanumeric characters', () => {
    const result = buildSpaStorageAccountName(
      'my-project',
      'dev',
      'react-app',
      subId,
    );
    expect(result).toBe('myprojectdevreacestsubid');
  });

  it('should truncate to 24 characters', () => {
    const result = buildSpaStorageAccountName(
      'curatedsound',
      'dev',
      'react-app',
      subId,
    );
    expect(result.length).toBeLessThanOrEqual(24);
    expect(result).toBe('curatedsounddevrestsubid');
  });

  it('should handle short names', () => {
    const result = buildSpaStorageAccountName('app', 'dev', 'ui', subId);
    expect(result).toBe('appdevuispaestsubid');
  });

  it('should always include last 8 chars of subscription ID', () => {
    const result = buildSpaStorageAccountName(
      'verylongprojectname',
      'staging',
      'admin-panel',
      '12345678-abcd-efgh-ijkl-aabbccddeeff',
    );
    expect(result.endsWith('ccddeeff')).toBe(true);
    expect(result.length).toBeLessThanOrEqual(24);
  });
});

describe('generateSpaStorageTf', () => {
  describe('no SPA services', () => {
    it('should return placeholder comment', () => {
      const result = generateSpaStorageTf(baseConfig);
      expect(result).toContain('# No SPA services configured');
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });

    it('should not contain any resource blocks', () => {
      const result = generateSpaStorageTf(baseConfig);
      expect(result).not.toContain('resource "azurerm_storage_account"');
    });
  });

  describe('single SPA service', () => {
    const config: AzureInfraConfig = {
      ...baseConfig,
      spas: { 'react-app': { domain: '' } },
    };

    it('should create storage account resource', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain(
        'resource "azurerm_storage_account" "spa_react_app"',
      );
    });

    it('should use sanitized storage account name with subscription suffix', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain(
        'name                     = "myprojectdevreacestsubid"',
      );
    });

    it('should use Standard LRS tier', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain('account_tier             = "Standard"');
      expect(result).toContain('account_replication_type = "LRS"');
    });

    it('should enforce TLS 1.2', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain('min_tls_version          = "TLS1_2"');
    });

    it('should enforce HTTPS-only traffic', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain('https_traffic_only_enabled      = true');
    });

    it('should disable nested public access', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain('allow_nested_items_to_be_public = false');
    });

    it('should create separate static website resource', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain(
        'resource "azurerm_storage_account_static_website" "spa_react_app"',
      );
      expect(result).toContain(
        'storage_account_id = azurerm_storage_account.spa_react_app.id',
      );
    });

    it('should enable static website with index.html', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain('index_document     = "index.html"');
    });

    it('should configure 404 to serve index.html for SPA routing', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain('error_404_document = "index.html"');
    });

    it('should apply tags', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain('tags = local.tags');
    });

    it('should reference resource group data source', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain(
        'resource_group_name      = data.azurerm_resource_group.main.name',
      );
      expect(result).toContain(
        'location                 = data.azurerm_resource_group.main.location',
      );
    });
  });

  describe('multiple SPA services', () => {
    const config: AzureInfraConfig = {
      ...baseConfig,
      spas: {
        'react-app': { domain: '' },
        'admin-panel': { domain: '' },
      },
    };

    it('should create storage account for each SPA', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain(
        'resource "azurerm_storage_account" "spa_react_app"',
      );
      expect(result).toContain(
        'resource "azurerm_storage_account" "spa_admin_panel"',
      );
    });

    it('should use unique storage account names with subscription suffix', () => {
      const result = generateSpaStorageTf(config);
      expect(result).toContain(
        'name                     = "myprojectdevreacestsubid"',
      );
      expect(result).toContain(
        'name                     = "myprojectdevadmiestsubid"',
      );
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const config: AzureInfraConfig = {
        ...baseConfig,
        spas: { 'react-app': { domain: '' } },
      };
      const result = generateSpaStorageTf(config);
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });
});
