/**
 * Generate spa-storage.tf with Azure Storage Accounts for SPA static website hosting
 *
 * Creates (per SPA service):
 * - Storage Account with static website hosting enabled
 * - SPA routing: 404 errors serve index.html for client-side routing
 *
 * Front Door integration (endpoints, origin groups) is in frontdoor.tf.
 * Origins and routes are added during service deployment.
 */

import type { AzureInfraConfig } from '../../types/config.ts';
import { toTerraformId } from '../../utils/terraform/to-terraform-id.ts';

/**
 * Build a valid Azure Storage Account name (3-24 chars, lowercase alphanumeric only)
 *
 * Includes last 8 hex chars of subscriptionId to ensure global uniqueness.
 */
export function buildSpaStorageAccountName(
  projectName: string,
  environment: string,
  spaName: string,
  subscriptionId: string,
): string {
  const subSuffix = subscriptionId.replace(/-/g, '').slice(-8);
  const prefix = `${projectName}${environment}${spaName}spa`.replace(
    /[^a-z0-9]/g,
    '',
  );
  const maxPrefix = 24 - subSuffix.length;
  return prefix.slice(0, maxPrefix) + subSuffix;
}

/**
 * Generate spa-storage.tf with Storage Accounts for SPA services
 */
export function generateSpaStorageTf(config: AzureInfraConfig): string {
  const spaEntries = Object.entries(config.spas);

  if (spaEntries.length === 0) {
    return `# No SPA services configured
# Generated by: npx tsdevstack infra:generate
`;
  }

  const storageAccounts = spaEntries
    .map(([name]) => {
      const tfId = toTerraformId(name);
      const accountName = buildSpaStorageAccountName(
        config.projectName,
        config.environment,
        name,
        config.subscriptionId,
      );

      return `
# Storage Account for ${name} SPA
resource "azurerm_storage_account" "spa_${tfId}" {
  name                     = "${accountName}"
  resource_group_name      = data.azurerm_resource_group.main.name
  location                 = data.azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"

  https_traffic_only_enabled      = true
  allow_nested_items_to_be_public = false

  tags = local.tags
}

# Static website hosting for ${name} SPA (SPA routing: 404 → index.html)
resource "azurerm_storage_account_static_website" "spa_${tfId}" {
  storage_account_id = azurerm_storage_account.spa_${tfId}.id
  index_document     = "index.html"
  error_404_document = "index.html"
}`;
    })
    .join('\n');

  return `# SPA Storage Accounts
# Generated by: npx tsdevstack infra:generate
#
# Static website hosting with SPA routing (404 → index.html).
# Front Door endpoints and origin groups are in frontdoor.tf.
# Origins and routes are added during service deployment.
${storageAccounts}
`;
}
