/**
 * Generate terraform.tfvars with actual values for Azure
 */

import type { AzureInfraConfig } from '../../types/config.ts';

export function generateTfvars(config: AzureInfraConfig): string {
  const {
    projectName,
    environment,
    location,
    subscriptionId,
    baseDomain,
    kongAppServiceSku,
    nextjsAppServiceSku,
    scheduledJobs,
  } = config;

  const scheduledJobsHcl = formatScheduledJobsMap(scheduledJobs);

  return `# Terraform variable values
# Generated by: npx tsdevstack infra:generate

project_name           = "${projectName}"
environment            = "${environment}"
location               = "${location}"
subscription_id        = "${subscriptionId}"
base_domain            = "${baseDomain}"
kong_app_service_sku   = "${kongAppServiceSku}"
nextjs_app_service_sku = "${nextjsAppServiceSku}"

# Scheduled Jobs
scheduled_jobs = ${scheduledJobsHcl}
`;
}

function formatScheduledJobsMap(
  scheduledJobs: AzureInfraConfig['scheduledJobs'],
): string {
  const entries = Object.entries(scheduledJobs);
  if (entries.length === 0) return '{}';

  const lines = entries.map(
    ([name, cfg]) =>
      `  "${name}" = {
    schedule     = "${cfg.schedule}"
    service_name = "${cfg.targetService}"
    path         = "${cfg.endpoint}"
  }`,
  );

  return `{
${lines.join('\n')}
}`;
}
