import { describe, it, expect } from '@rstest/core';
import { generateAcrTf } from './generate-acr-tf';

describe('generateAcrTf', () => {
  describe('container registry resource', () => {
    it('should create ACR resource', () => {
      const result = generateAcrTf();
      expect(result).toContain('resource "azurerm_container_registry" "main"');
    });

    it('should use replace to strip hyphens from name', () => {
      const result = generateAcrTf();
      expect(result).toContain('replace(var.project_name, "-", "")');
    });

    it('should use Basic SKU', () => {
      const result = generateAcrTf();
      expect(result).toContain('sku                 = "Basic"');
    });

    it('should disable admin access', () => {
      const result = generateAcrTf();
      expect(result).toContain('admin_enabled       = false');
    });

    it('should reference resource group data source', () => {
      const result = generateAcrTf();
      expect(result).toContain(
        'resource_group_name = data.azurerm_resource_group.main.name',
      );
      expect(result).toContain(
        'location            = data.azurerm_resource_group.main.location',
      );
    });

    it('should apply tags', () => {
      const result = generateAcrTf();
      expect(result).toContain('tags                = local.tags');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateAcrTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });
});
