/**
 * Generate waf.tf with Azure Front Door WAF policy and custom rules
 *
 * Standard tier: all 79 custom rules (managed rulesets require Premium).
 * Premium tier: DRS 2.1 + Bot Manager managed rulesets replace bands 500-899,
 *               keeping ~35 custom rules for rate limiting, scanners, CVEs, etc.
 */

import { generateWafCustomRules } from './generate-waf-custom-rules.ts';
import { generateAzureUserWafRules } from './generate-azure-user-waf-rules.ts';
import type { AzureInfraConfig } from '../../types/config.ts';

export function generateWafTf(config: AzureInfraConfig): string {
  const customRulesHcl = generateWafCustomRules({
    skipManagedBands: config.frontdoorPremium,
    rateLimit: config.waf?.rateLimit,
  });

  const userRulesHcl = generateAzureUserWafRules(
    config.waf?.azureCustomRules || [],
  );

  const managedRulesHcl = config.frontdoorPremium
    ? `

  managed_rule {
    type    = "Microsoft_DefaultRuleSet"
    version = "2.1"
    action  = "Block"
  }

  managed_rule {
    type    = "Microsoft_BotManagerRuleSet"
    version = "1.1"
    action  = "Block"
  }
`
    : '';

  const tierComment = config.frontdoorPremium
    ? `# Premium tier: DRS 2.1 + Bot Manager managed rulesets handle SQLi, XSS, traversal, OWASP.
# Custom rules cover: rate limiting, size restrictions, scanners, CVEs, protocol attacks.`
    : `# Standard tier: all rules are custom (managed rulesets require Premium).
# Covers: rate limiting, SQLi, XSS, path traversal, SSRF, CVEs, Node.js attacks.`;

  return `# Azure Front Door WAF Policy
# Generated by: npx tsdevstack infra:generate
#
${tierComment}

resource "azurerm_cdn_frontdoor_firewall_policy" "main" {
  name                              = "\${replace(var.project_name, "-", "")}\${var.environment}waf"
  resource_group_name               = data.azurerm_resource_group.main.name
  sku_name                          = azurerm_cdn_frontdoor_profile.main.sku_name
  mode                              = "Prevention"
  enabled                           = true
  tags                              = local.tags

${customRulesHcl}${userRulesHcl ? `\n${userRulesHcl}` : ''}${managedRulesHcl}
}
`;
}
