/**
 * Generate container-apps-env.tf with Log Analytics Workspace and Container Apps Environment
 */

export function generateContainerAppsEnvTf(): string {
  return `# Container Apps Environment
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# Log Analytics Workspace (required by Container Apps)
# =============================================================================

resource "azurerm_log_analytics_workspace" "main" {
  name                = "\${var.project_name}-\${var.environment}-logs"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  tags                = local.tags
}

# =============================================================================
# Container Apps Environment
# =============================================================================

resource "azurerm_container_app_environment" "main" {
  name                           = "\${var.project_name}-\${var.environment}-cae"
  location                       = data.azurerm_resource_group.main.location
  resource_group_name            = data.azurerm_resource_group.main.name
  infrastructure_subnet_id       = azurerm_subnet.container_apps.id
  internal_load_balancer_enabled = true
  public_network_access          = "Disabled"
  logs_destination               = "log-analytics"
  log_analytics_workspace_id     = azurerm_log_analytics_workspace.main.id
  tags                           = local.tags

  workload_profile {
    name                  = "Consumption"
    workload_profile_type = "Consumption"
  }

  lifecycle {
    ignore_changes = [infrastructure_resource_group_name]
  }
}
`;
}
