/**
 * Generate app-service.tf with App Service Plans, Web Apps, and role assignments
 *
 * Kong gets a dedicated App Service Plan.
 * Next.js apps share one App Service Plan.
 * Both have Access Restrictions (service tag + FDID header) for Front Door.
 */

import type { AzureInfraConfig } from '../../types/config.ts';
import { toTerraformId } from '../../utils/terraform/to-terraform-id.ts';

export function generateAppServiceTf(config: AzureInfraConfig): string {
  const nextjsEntries = Object.entries(config.frontends);

  const nextjsWebApps = nextjsEntries
    .map(([name]) => {
      const tfId = toTerraformId(name);
      return generateNextjsWebApp(tfId, name);
    })
    .join('\n');

  const nextjsRoleAssignments = nextjsEntries
    .map(([name]) => {
      const tfId = toTerraformId(name);
      return generateRoleAssignments(
        `nextjs_${tfId}`,
        `azurerm_linux_web_app.nextjs_${tfId}`,
      );
    })
    .join('\n');

  const nextjsPlan =
    nextjsEntries.length > 0
      ? `
resource "azurerm_service_plan" "nextjs" {
  name                = "\${var.project_name}-\${var.environment}-nextjs-plan"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  os_type             = "Linux"
  sku_name            = var.nextjs_app_service_sku
  tags                = local.tags
}
`
      : '';

  return `# App Service (Kong + Next.js)
# Generated by: npx tsdevstack infra:generate
#
# Kong and Next.js run on App Service for Access Restrictions
# (service tag + FDID header filtering).
# Backends remain on Container Apps with internal ingress.

# =============================================================================
# App Service Plans
# =============================================================================

resource "azurerm_service_plan" "kong" {
  name                = "\${var.project_name}-\${var.environment}-kong-plan"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  os_type             = "Linux"
  sku_name            = var.kong_app_service_sku
  tags                = local.tags
}
${nextjsPlan}
# =============================================================================
# Kong Web App
# =============================================================================

resource "azurerm_linux_web_app" "kong" {
  name                      = "\${var.project_name}-\${var.environment}-kong"
  location                  = data.azurerm_resource_group.main.location
  resource_group_name       = data.azurerm_resource_group.main.name
  service_plan_id           = azurerm_service_plan.kong.id
  virtual_network_subnet_id = azurerm_subnet.app_service_integration.id
  https_only                = true
  tags                      = local.tags

  site_config {
    always_on                               = true
    container_registry_use_managed_identity = true
    minimum_tls_version                     = "1.2"
    ftps_state                              = "Disabled"
    http2_enabled                           = true
    ip_restriction_default_action           = "Deny"
    scm_use_main_ip_restriction             = true

    ip_restriction {
      service_tag = "AzureFrontDoor.Backend"
      action      = "Allow"
      priority    = 100
      name        = "AllowFrontDoor"

      headers {
        x_azure_fdid     = [azurerm_cdn_frontdoor_profile.main.resource_guid]
        x_fd_health_probe = []
        x_forwarded_for   = []
        x_forwarded_host  = []
      }
    }

    application_stack {
      docker_registry_url = "https://\${azurerm_container_registry.main.login_server}"
      docker_image_name   = "kong:latest"
    }
  }

  app_settings = {
    WEBSITES_PORT                       = "8080"
    WEBSITES_CONTAINER_START_TIME_LIMIT = "600"
    KONG_DATABASE                       = "off"
    KONG_DECLARATIVE_CONFIG             = "/kong/declarative/kong.yml"
  }

  identity {
    type = "SystemAssigned"
  }

  lifecycle {
    ignore_changes = [
      app_settings,
      site_config[0].application_stack[0].docker_image_name,
    ]
  }
}
${nextjsWebApps}
# =============================================================================
# Role Assignments
# =============================================================================
${generateRoleAssignments('kong', 'azurerm_linux_web_app.kong')}
${nextjsRoleAssignments}`;
}

/**
 * Generate HCL for a single Next.js web app
 */
function generateNextjsWebApp(tfId: string, serviceName: string): string {
  return `
# =============================================================================
# Next.js Web App: ${serviceName}
# =============================================================================

resource "azurerm_linux_web_app" "nextjs_${tfId}" {
  name                      = "\${var.project_name}-\${var.environment}-${serviceName}"
  location                  = data.azurerm_resource_group.main.location
  resource_group_name       = data.azurerm_resource_group.main.name
  service_plan_id           = azurerm_service_plan.nextjs.id
  virtual_network_subnet_id = azurerm_subnet.app_service_integration.id
  https_only                = true
  tags                      = local.tags

  site_config {
    always_on                               = true
    container_registry_use_managed_identity = true
    minimum_tls_version                     = "1.2"
    ftps_state                              = "Disabled"
    http2_enabled                           = true
    ip_restriction_default_action           = "Deny"
    scm_use_main_ip_restriction             = true

    ip_restriction {
      service_tag = "AzureFrontDoor.Backend"
      action      = "Allow"
      priority    = 100
      name        = "AllowFrontDoor"

      headers {
        x_azure_fdid     = [azurerm_cdn_frontdoor_profile.main.resource_guid]
        x_fd_health_probe = []
        x_forwarded_for   = []
        x_forwarded_host  = []
      }
    }

    application_stack {
      docker_registry_url = "https://\${azurerm_container_registry.main.login_server}"
      docker_image_name   = "${serviceName}:latest"
    }
  }

  app_settings = {
    WEBSITES_PORT                       = "8080"
    WEBSITES_CONTAINER_START_TIME_LIMIT = "300"
  }

  identity {
    type = "SystemAssigned"
  }

  lifecycle {
    ignore_changes = [
      app_settings,
      site_config[0].application_stack[0].docker_image_name,
    ]
  }
}`;
}

/**
 * Generate ACR pull + Key Vault role assignments for a web app
 */
function generateRoleAssignments(prefix: string, resourceRef: string): string {
  return `
resource "azurerm_role_assignment" "${prefix}_acr_pull" {
  scope                            = azurerm_container_registry.main.id
  role_definition_name             = "AcrPull"
  principal_id                     = ${resourceRef}.identity[0].principal_id
  skip_service_principal_aad_check = true
}

resource "azurerm_role_assignment" "${prefix}_keyvault" {
  scope                            = data.azurerm_key_vault.main.id
  role_definition_name             = "Key Vault Secrets User"
  principal_id                     = ${resourceRef}.identity[0].principal_id
  skip_service_principal_aad_check = true
}`;
}
