/**
 * Generate container-apps-identity.tf with user-assigned managed identity for ACR pull
 *
 * Container Apps are created via SDK (not Terraform), so they need a
 * user-assigned identity that exists before the first Container App deploy.
 * App Service uses system-assigned identity (created by Terraform), but
 * Container Apps can't do that since they're managed externally.
 */

export function generateContainerAppsIdentityTf(): string {
  return `# Container Apps — Managed Identity for ACR Pull
# Generated by: npx tsdevstack infra:generate
#
# User-assigned identity shared by all Container Apps (services, workers, jobs).
# Enables image pulls from ACR without short-lived refresh tokens.

resource "azurerm_user_assigned_identity" "container_apps" {
  name                = "\${var.project_name}-\${var.environment}-ca-identity"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  tags                = local.tags
}

resource "azurerm_role_assignment" "container_apps_acr_pull" {
  scope                            = azurerm_container_registry.main.id
  role_definition_name             = "AcrPull"
  principal_id                     = azurerm_user_assigned_identity.container_apps.principal_id
  skip_service_principal_aad_check = true
}

resource "azurerm_role_assignment" "container_apps_keyvault_secrets" {
  scope                            = data.azurerm_key_vault.main.id
  role_definition_name             = "Key Vault Secrets User"
  principal_id                     = azurerm_user_assigned_identity.container_apps.principal_id
  skip_service_principal_aad_check = true
}
`;
}
