/**
 * Generate Scheduled Jobs Terraform (Azure)
 *
 * Generates Container App Jobs resources for scheduled (CRON) jobs.
 * Each job invokes an HTTP endpoint on a target Container App service.
 */

import type { AzureInfraConfig } from '../../types/config.ts';

/**
 * Generate scheduled-jobs.tf content
 *
 * Uses azurerm_container_app_job with schedule_trigger_config.
 * Each job runs a lightweight curl container that calls the target service.
 */
export function generateScheduledJobsTf(config: AzureInfraConfig): string {
  const { scheduledJobs } = config;

  const jobEntries = Object.entries(scheduledJobs);
  if (jobEntries.length === 0) {
    return '';
  }

  const lines: string[] = [
    '# ============================================================================',
    '# Scheduled Jobs (Container App Jobs with CRON triggers)',
    '# Generated by tsdevstack — DO NOT EDIT DIRECTLY',
    '# ============================================================================',
    '',
    '# Scheduled jobs map variable',
    'variable "scheduled_jobs" {',
    '  type = map(object({',
    '    schedule       = string',
    '    service_name   = string',
    '    path           = string',
    '    method         = optional(string, "POST")',
    '    timeout        = optional(number, 300)',
    '  }))',
    '  default = {}',
    '}',
    '',
    '# Auto-generated shared secret for job authentication',
    'resource "random_password" "job_secret" {',
    '  length  = 48',
    '  special = false',
    '}',
    '',
    'resource "azurerm_key_vault_secret" "job_secret" {',
    '  name         = "${var.project_name}-shared-JOB-SECRET"',
    '  value        = random_password.job_secret.result',
    '  key_vault_id = data.azurerm_key_vault.main.id',
    '}',
    '',
    '# Container App Jobs for scheduled tasks',
    'resource "azurerm_container_app_job" "scheduled_jobs" {',
    '  for_each = var.scheduled_jobs',
    '',
    `  name                         = "\${var.project_name}-\${each.key}"`,
    '  resource_group_name          = data.azurerm_resource_group.main.name',
    '  location                     = var.location',
    '  container_app_environment_id = azurerm_container_app_environment.main.id',
    '',
    '  workload_profile_name      = "Consumption"',
    '',
    '  replica_timeout_in_seconds = each.value.timeout',
    '  replica_retry_limit        = 0',
    '',
    '  schedule_trigger_config {',
    '    cron_expression          = each.value.schedule',
    '    parallelism              = 1',
    '    replica_completion_count = 1',
    '  }',
    '',
    '  template {',
    '    container {',
    '      name   = "job-invoker"',
    '      image  = "curlimages/curl:latest"',
    '      cpu    = 0.25',
    '      memory = "0.5Gi"',
    '',
    '      command = [',
    '        "/bin/sh", "-c",',
    `        "curl -sfL --retry 3 --retry-delay 15 --retry-all-errors -X \${each.value.method} -H 'Content-Type: application/json' -H 'X-Job-Secret: $(JOB_SECRET)' --max-time \${each.value.timeout} https://\${var.project_name}-\${each.value.service_name}.\${azurerm_container_app_environment.main.default_domain}\${each.value.path}"`,
    '      ]',
    '',
    '      env {',
    '        name        = "JOB_SECRET"',
    `        secret_name = "job-secret"`,
    '      }',
    '    }',
    '  }',
    '',
    '  secret {',
    '    name  = "job-secret"',
    '    value = random_password.job_secret.result',
    '  }',
    '',
    '  tags = local.tags',
    '}',
    '',
  ];

  return lines.join('\n');
}
