/**
 * Generate outputs.tf with stack outputs for Azure
 */

import type { AzureInfraConfig } from '../../types/config.ts';
import { toTerraformId } from '../../utils/terraform/to-terraform-id.ts';

export function generateOutputsTf(config: AzureInfraConfig): string {
  const spaEntries = Object.entries(config.spas);

  const spaOutputs = spaEntries
    .map(([name]) => {
      const tfId = toTerraformId(name);
      return `
output "spa_${tfId}_storage_account" {
  description = "Storage account name for ${name} SPA"
  value       = azurerm_storage_account.spa_${tfId}.name
}

output "spa_${tfId}_web_host" {
  description = "Primary web host for ${name} SPA"
  value       = azurerm_storage_account.spa_${tfId}.primary_web_host
}

output "spa_${tfId}_endpoint_hostname" {
  description = "Front Door endpoint hostname for ${name} SPA"
  value       = azurerm_cdn_frontdoor_endpoint.spa_${tfId}.host_name
}`;
    })
    .join('\n');

  const spaSection =
    spaEntries.length > 0
      ? `

# =============================================================================
# SPA Hosting
# =============================================================================
${spaOutputs}
`
      : '';

  // App Service outputs
  const nextjsEntries = Object.entries(config.frontends);
  const nextjsAppServiceOutputs = nextjsEntries
    .map(([name]) => {
      const tfId = toTerraformId(name);
      return `
output "nextjs_${tfId}_app_service_name" {
  description = "App Service name for ${name}"
  value       = azurerm_linux_web_app.nextjs_${tfId}.name
}`;
    })
    .join('\n');

  const appServiceSection = `

# =============================================================================
# App Service
# =============================================================================

output "kong_app_service_name" {
  description = "App Service name for Kong"
  value       = azurerm_linux_web_app.kong.name
}
${nextjsAppServiceOutputs}`;

  return `# Stack outputs
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# Core Info
# =============================================================================

output "location" {
  description = "Azure region"
  value       = var.location
}

output "subscription_id" {
  description = "Azure subscription ID"
  value       = var.subscription_id
}

output "project_name" {
  description = "Project name"
  value       = var.project_name
}

output "environment" {
  description = "Environment"
  value       = var.environment
}

output "resource_group_name" {
  description = "Resource group name"
  value       = data.azurerm_resource_group.main.name
}

# =============================================================================
# Front Door
# =============================================================================

output "front_door_id" {
  description = "Azure Front Door profile ID"
  value       = azurerm_cdn_frontdoor_profile.main.id
}

output "front_door_resource_guid" {
  description = "Azure Front Door resource GUID (FDID for origin verification)"
  value       = azurerm_cdn_frontdoor_profile.main.resource_guid
}

# =============================================================================
# API URL (for SPA builds and Next.js)
# =============================================================================

output "api_url" {
  description = "API URL (custom domain if set, otherwise Front Door endpoint)"
  value       = var.base_domain != "" ? "https://api.\${var.base_domain}" : "https://\${azurerm_cdn_frontdoor_endpoint.api.host_name}"
}

# =============================================================================
# Container Registry
# =============================================================================

output "acr_login_server" {
  description = "ACR login server URL"
  value       = azurerm_container_registry.main.login_server
}

# =============================================================================
# Container Apps Environment
# =============================================================================

output "container_apps_env_id" {
  description = "Container Apps Environment ID"
  value       = azurerm_container_app_environment.main.id
}

output "container_apps_env_default_domain" {
  description = "Container Apps Environment default domain"
  value       = azurerm_container_app_environment.main.default_domain
}

output "container_apps_acr_identity_id" {
  description = "User-assigned managed identity for Container Apps ACR pull"
  value       = azurerm_user_assigned_identity.container_apps.id
}

output "container_apps_acr_identity_client_id" {
  description = "Client ID of the Container Apps managed identity (used as AZURE_CLIENT_ID)"
  value       = azurerm_user_assigned_identity.container_apps.client_id
}

# =============================================================================
# Redis (Azure Managed Redis)
# =============================================================================

output "redis_host" {
  description = "Redis hostname"
  value       = azurerm_managed_redis.main.hostname
}

output "redis_port" {
  description = "Redis port"
  value       = tostring(azurerm_managed_redis.main.default_database[0].port)
}

output "redis_password" {
  description = "Redis primary access key"
  value       = azurerm_managed_redis.main.default_database[0].primary_access_key
  sensitive   = true
}

# =============================================================================
# Database (PostgreSQL Flexible Server)
# =============================================================================

output "database_host" {
  description = "PostgreSQL server FQDN"
  value       = azurerm_postgresql_flexible_server.main.fqdn
}

output "database_admin_password" {
  description = "PostgreSQL admin password (auto-generated)"
  value       = random_password.db_admin.result
  sensitive   = true
}
${spaSection}${appServiceSection}`;
}
