import { describe, it, expect } from '@rstest/core';
import { generateDnsTf } from './generate-dns-tf';
import type { AzureInfraConfig } from '../../types/config.ts';

const baseConfig: AzureInfraConfig = {
  provider: 'azure',
  projectName: 'myproject',
  environment: 'dev',
  subscriptionId: 'test-sub-id',
  location: 'eastus',
  storageAccountName: 'myprojectdevtfstate',
  database: {
    tier: 'B_Standard_B1ms',
    storageSizeGb: 32,
    deletionProtection: false,
    backup: false,
  },
  redis: { tier: 'Balanced_B0' },
  servicesWithDatabase: [],
  baseDomain: '',
  services: {},
  workers: {},
  allDeployables: {},
  spas: {},
  frontends: {},
  scheduledJobs: {},
  noIndex: false,
  frontdoorPremium: false,
  kongAppServiceSku: 'B1',
  nextjsAppServiceSku: 'B1',
};

describe('generateDnsTf', () => {
  describe('No domain configured', () => {
    it('should return placeholder comment when baseDomain is empty', () => {
      const result = generateDnsTf(baseConfig);
      expect(result).toContain('No custom domain configured');
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });

    it('should not contain any resource blocks when baseDomain is empty', () => {
      const result = generateDnsTf(baseConfig);
      expect(result).not.toContain('resource "');
    });
  });

  describe('DNS zone', () => {
    it('should create DNS zone when baseDomain is set', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
      });
      expect(result).toContain('resource "azurerm_dns_zone" "main"');
      expect(result).toContain('name                = var.base_domain');
      expect(result).toContain(
        'resource_group_name = data.azurerm_resource_group.main.name',
      );
    });

    it('should include tags on DNS zone', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
      });
      expect(result).toContain('tags                = local.tags');
    });
  });

  describe('API custom domain', () => {
    const configWithDomain: AzureInfraConfig = {
      ...baseConfig,
      baseDomain: 'example.com',
    };

    it('should create API custom domain', () => {
      const result = generateDnsTf(configWithDomain);
      expect(result).toContain(
        'resource "azurerm_cdn_frontdoor_custom_domain" "api"',
      );
      expect(result).toContain('host_name                = "api.example.com"');
    });

    it('should use managed TLS certificate', () => {
      const result = generateDnsTf(configWithDomain);
      expect(result).toContain('certificate_type = "ManagedCertificate"');
      expect(result).not.toContain('minimum_tls_version');
    });

    it('should reference Front Door profile and DNS zone', () => {
      const result = generateDnsTf(configWithDomain);
      expect(result).toContain(
        'cdn_frontdoor_profile_id = azurerm_cdn_frontdoor_profile.main.id',
      );
      expect(result).toContain(
        'dns_zone_id              = azurerm_dns_zone.main.id',
      );
    });

    it('should create API TXT validation record', () => {
      const result = generateDnsTf(configWithDomain);
      expect(result).toContain(
        'resource "azurerm_dns_txt_record" "api_validation"',
      );
      expect(result).toContain('name                = "_dnsauth.api"');
      expect(result).toContain(
        'azurerm_cdn_frontdoor_custom_domain.api.validation_token',
      );
    });

    it('should create API CNAME record', () => {
      const result = generateDnsTf(configWithDomain);
      expect(result).toContain('resource "azurerm_dns_cname_record" "api"');
      expect(result).toContain('name                = "api"');
      expect(result).toContain(
        'record              = azurerm_cdn_frontdoor_endpoint.api.host_name',
      );
    });

    it('should use TTL 3600 for DNS records', () => {
      const result = generateDnsTf(configWithDomain);
      expect(result).toContain('ttl                 = 3600');
    });

    it('should set Azure resource name with project and environment', () => {
      const result = generateDnsTf(configWithDomain);
      expect(result).toContain(
        'name                     = "${var.project_name}-${var.environment}-api"',
      );
    });
  });

  describe('Next.js custom domains', () => {
    it('should not create nextjs custom domain when no Next.js services', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
      });
      expect(result).not.toContain(
        'resource "azurerm_cdn_frontdoor_custom_domain" "nextjs_frontend"',
      );
      expect(result).not.toContain(
        'resource "azurerm_dns_cname_record" "nextjs_frontend"',
      );
    });

    it('should create nextjs custom domain when Next.js services exist', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        frontends: {
          frontend: {
            domain: 'frontend.example.com',
            cpu: 0.5,
            memory: '1Gi',
            minInstances: 1,
            maxInstances: 5,
          },
        },
      });
      expect(result).toContain(
        'resource "azurerm_cdn_frontdoor_custom_domain" "nextjs_frontend"',
      );
      expect(result).toContain(
        'host_name                = "frontend.example.com"',
      );
    });

    it('should create nextjs CNAME with subdomain derived from domain', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        frontends: {
          frontend: {
            domain: 'frontend.example.com',
            cpu: 0.5,
            memory: '1Gi',
            minInstances: 1,
            maxInstances: 5,
          },
        },
      });
      expect(result).toContain(
        'resource "azurerm_dns_cname_record" "nextjs_frontend"',
      );
      expect(result).toContain('name                = "frontend"');
      expect(result).toContain(
        'record              = azurerm_cdn_frontdoor_endpoint.nextjs_frontend.host_name',
      );
    });

    it('should create alias A record when domain is apex (root domain)', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        frontends: {
          frontend: {
            domain: 'example.com',
            cpu: 0.5,
            memory: '1Gi',
            minInstances: 1,
            maxInstances: 5,
          },
        },
      });
      expect(result).toContain(
        'resource "azurerm_dns_a_record" "nextjs_frontend"',
      );
      expect(result).toContain('name                = "@"');
      expect(result).toContain(
        'target_resource_id = azurerm_cdn_frontdoor_endpoint.nextjs_frontend.id',
      );
      expect(result).not.toContain(
        'resource "azurerm_dns_cname_record" "nextjs_frontend"',
      );
    });

    it('should use _dnsauth without subdomain for apex domain validation', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        frontends: {
          frontend: {
            domain: 'example.com',
            cpu: 0.5,
            memory: '1Gi',
            minInstances: 1,
            maxInstances: 5,
          },
        },
      });
      expect(result).toContain('name                = "_dnsauth"');
    });

    it('should create nextjs TXT validation record', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        frontends: {
          frontend: {
            domain: 'frontend.example.com',
            cpu: 0.5,
            memory: '1Gi',
            minInstances: 1,
            maxInstances: 5,
          },
        },
      });
      expect(result).toContain(
        'resource "azurerm_dns_txt_record" "nextjs_frontend_validation"',
      );
      expect(result).toContain('name                = "_dnsauth.frontend"');
    });

    it('should set Azure resource name with nextjs prefix', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        frontends: {
          frontend: {
            domain: 'frontend.example.com',
            cpu: 0.5,
            memory: '1Gi',
            minInstances: 1,
            maxInstances: 5,
          },
        },
      });
      expect(result).toContain(
        'name                     = "${var.project_name}-${var.environment}-nextjs-frontend"',
      );
    });

    it('should handle multiple Next.js services', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        frontends: {
          frontend: {
            domain: 'frontend.example.com',
            cpu: 0.5,
            memory: '1Gi',
            minInstances: 1,
            maxInstances: 5,
          },
          dashboard: {
            domain: 'dashboard.example.com',
            cpu: 0.5,
            memory: '1Gi',
            minInstances: 0,
            maxInstances: 3,
          },
        },
      });
      expect(result).toContain(
        'resource "azurerm_cdn_frontdoor_custom_domain" "nextjs_frontend"',
      );
      expect(result).toContain(
        'resource "azurerm_cdn_frontdoor_custom_domain" "nextjs_dashboard"',
      );
      expect(result).toContain(
        'resource "azurerm_dns_cname_record" "nextjs_frontend"',
      );
      expect(result).toContain(
        'resource "azurerm_dns_cname_record" "nextjs_dashboard"',
      );
      expect(result).toContain(
        'host_name                = "frontend.example.com"',
      );
      expect(result).toContain(
        'host_name                = "dashboard.example.com"',
      );
    });
  });

  describe('SPA custom domains', () => {
    it('should create SPA custom domain per SPA service', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        spas: {
          'react-app': { domain: 'react-app.example.com' },
        },
      });
      expect(result).toContain(
        'resource "azurerm_cdn_frontdoor_custom_domain" "spa_react_app"',
      );
      expect(result).toContain(
        'host_name                = "react-app.example.com"',
      );
    });

    it('should create SPA CNAME pointing to SPA endpoint', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        spas: {
          'react-app': { domain: 'react-app.example.com' },
        },
      });
      expect(result).toContain(
        'resource "azurerm_dns_cname_record" "spa_react_app"',
      );
      expect(result).toContain('name                = "react-app"');
      expect(result).toContain(
        'record              = azurerm_cdn_frontdoor_endpoint.spa_react_app.host_name',
      );
    });

    it('should create SPA TXT validation record', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        spas: {
          'react-app': { domain: 'react-app.example.com' },
        },
      });
      expect(result).toContain(
        'resource "azurerm_dns_txt_record" "spa_react_app_validation"',
      );
      expect(result).toContain('name                = "_dnsauth.react-app"');
    });

    it('should set Azure resource name for SPA custom domain', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        spas: {
          'react-app': { domain: 'react-app.example.com' },
        },
      });
      expect(result).toContain(
        'name                     = "${var.project_name}-${var.environment}-spa-react-app"',
      );
    });

    it('should handle multiple SPAs', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        spas: {
          'react-app': { domain: 'react-app.example.com' },
          'admin-panel': { domain: 'admin-panel.example.com' },
        },
      });
      expect(result).toContain(
        'resource "azurerm_cdn_frontdoor_custom_domain" "spa_react_app"',
      );
      expect(result).toContain(
        'resource "azurerm_cdn_frontdoor_custom_domain" "spa_admin_panel"',
      );
      expect(result).toContain(
        'resource "azurerm_dns_cname_record" "spa_react_app"',
      );
      expect(result).toContain(
        'resource "azurerm_dns_cname_record" "spa_admin_panel"',
      );
    });
  });

  describe('Combined services', () => {
    it('should generate all custom domains when all service types present', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
        frontends: {
          frontend: {
            domain: 'frontend.example.com',
            cpu: 0.5,
            memory: '1Gi',
            minInstances: 1,
            maxInstances: 5,
          },
        },
        spas: {
          'react-app': { domain: 'react-app.example.com' },
        },
      });
      // API
      expect(result).toContain(
        'resource "azurerm_cdn_frontdoor_custom_domain" "api"',
      );
      // Next.js
      expect(result).toContain(
        'resource "azurerm_cdn_frontdoor_custom_domain" "nextjs_frontend"',
      );
      // SPA
      expect(result).toContain(
        'resource "azurerm_cdn_frontdoor_custom_domain" "spa_react_app"',
      );
    });
  });

  describe('Outputs', () => {
    it('should include dns_name_servers output', () => {
      const result = generateDnsTf({
        ...baseConfig,
        baseDomain: 'example.com',
      });
      expect(result).toContain('output "dns_name_servers"');
      expect(result).toContain('azurerm_dns_zone.main.name_servers');
    });

    it('should not include outputs when baseDomain is empty', () => {
      const result = generateDnsTf(baseConfig);
      expect(result).not.toContain('output "');
    });
  });
});
