import { describe, it, expect } from '@rstest/core';
import { generateRedisTf } from './generate-redis-tf';
import type { AzureInfraConfig } from '../../types/config.ts';

const baseConfig: AzureInfraConfig = {
  provider: 'azure',
  projectName: 'myproject',
  environment: 'dev',
  subscriptionId: 'test-sub-id',
  location: 'eastus',
  storageAccountName: 'myprojectdevtfstate',
  database: {
    tier: 'B_Standard_B1ms',
    storageSizeGb: 32,
    deletionProtection: false,
    backup: false,
  },
  redis: { tier: 'Balanced_B0' },
  servicesWithDatabase: [],
  baseDomain: '',
  services: {},
  workers: {},
  allDeployables: {},
  spas: {},
  frontends: {},
  scheduledJobs: {},
  storageBuckets: [],
  noIndex: false,
  frontdoorPremium: false,
  kongAppServiceSku: 'B1',
  nextjsAppServiceSku: 'B1',
};

describe('generateRedisTf', () => {
  describe('Azure Managed Redis', () => {
    it('should create Managed Redis resource', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain('resource "azurerm_managed_redis" "main"');
    });

    it('should use configured SKU', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain('sku_name            = "Balanced_B0"');
    });

    it('should reference resource group data source', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain(
        'resource_group_name = data.azurerm_resource_group.main.name',
      );
    });

    it('should apply tags', () => {
      const result = generateRedisTf(baseConfig);
      const redisBlock = result.slice(
        result.indexOf('resource "azurerm_managed_redis" "main"'),
        result.indexOf('resource "azurerm_private_endpoint" "redis"'),
      );
      expect(redisBlock).toContain('tags                = local.tags');
    });

    it('should include default_database block with access keys enabled', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain('default_database {');
      expect(result).toContain('access_keys_authentication_enabled = true');
    });

    it('should use EnterpriseCluster policy for standard ioredis compatibility', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain(
        'clustering_policy                  = "EnterpriseCluster"',
      );
    });

    it('should set NoEviction policy for BullMQ compatibility', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain(
        'eviction_policy                    = "NoEviction"',
      );
    });
  });

  describe('Private Endpoint', () => {
    it('should create private endpoint resource', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain('resource "azurerm_private_endpoint" "redis"');
    });

    it('should use private endpoints subnet', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain(
        'subnet_id           = azurerm_subnet.private_endpoints.id',
      );
    });

    it('should connect to Managed Redis', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain(
        'private_connection_resource_id = azurerm_managed_redis.main.id',
      );
    });

    it('should use redisEnterprise subresource', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain(
        'subresource_names              = ["redisEnterprise"]',
      );
    });

    it('should not be manual connection', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain('is_manual_connection           = false');
    });

    it('should link to Redis DNS zone', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain(
        'private_dns_zone_ids = [azurerm_private_dns_zone.redis.id]',
      );
    });

    it('should apply tags to private endpoint', () => {
      const result = generateRedisTf(baseConfig);
      const peBlock = result.slice(
        result.indexOf('resource "azurerm_private_endpoint" "redis"'),
      );
      expect(peBlock).toContain('tags                = local.tags');
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateRedisTf(baseConfig);
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });
});
