/**
 * Generate variables.tf with input variable definitions for Azure
 */

import type { AzureInfraConfig } from '../../types/config.ts';

export function generateVariablesTf(config: AzureInfraConfig): string {
  const serviceImageVars = Object.keys(config.services)
    .map(
      (name) => `
variable "${name.replace(/-/g, '_')}_image" {
  description = "Docker image tag for ${name}"
  type        = string
  default     = "placeholder"
}`,
    )
    .join('\n');

  const workerImageVars = Object.keys(config.workers)
    .map(
      (name) => `
variable "${name.replace(/-/g, '_')}_image" {
  description = "Docker image tag for ${name} worker"
  type        = string
  default     = "placeholder"
}`,
    )
    .join('\n');

  return `# Input variables
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# Core
# =============================================================================

variable "project_name" {
  description = "Project name"
  type        = string
}

variable "environment" {
  description = "Environment (dev, staging, prod)"
  type        = string
}

variable "location" {
  description = "Azure region"
  type        = string
}

variable "subscription_id" {
  description = "Azure subscription ID"
  type        = string
}

# =============================================================================
# Domain
# =============================================================================

variable "base_domain" {
  description = "Base domain for the application (e.g., example.com)"
  type        = string
  default     = ""
}

# =============================================================================
# App Service
# =============================================================================

variable "kong_app_service_sku" {
  description = "SKU for Kong App Service Plan"
  type        = string
  default     = "B1"
}

variable "nextjs_app_service_sku" {
  description = "SKU for Next.js App Service Plan"
  type        = string
  default     = "B1"
}

# =============================================================================
# Service Images
# =============================================================================
${serviceImageVars}
${workerImageVars}
`;
}
