/**
 * Generate acr.tf with Azure Container Registry
 */

export function generateAcrTf(): string {
  return `# Azure Container Registry
# Generated by: npx tsdevstack infra:generate

resource "azurerm_container_registry" "main" {
  name                = "\${replace(var.project_name, "-", "")}\${var.environment}acr"
  resource_group_name = data.azurerm_resource_group.main.name
  location            = data.azurerm_resource_group.main.location
  sku                 = "Basic"
  admin_enabled       = false
  tags                = local.tags
}
`;
}
