/**
 * Generate main.tf with Terraform configuration, azurerm provider, and Storage backend
 */

import type { AzureInfraConfig } from '../../types/config.ts';

export function generateMainTf(config: AzureInfraConfig): string {
  const { storageAccountName, environment, projectName } = config;

  return `# Terraform configuration
# Generated by: npx tsdevstack infra:generate

terraform {
  required_version = ">= 1.5"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.50"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }

  backend "azurerm" {
    resource_group_name  = "${projectName}-${environment}-rg"
    storage_account_name = "${storageAccountName}"
    container_name       = "tfstate"
    key                  = "terraform.tfstate"
  }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
  }

  subscription_id                 = var.subscription_id
  resource_provider_registrations = "none"
}

# =============================================================================
# Data Sources
# =============================================================================

data "azurerm_client_config" "current" {}

# =============================================================================
# Resource Group (prerequisite — created by user in Azure portal)
# =============================================================================

data "azurerm_resource_group" "main" {
  name = "\${var.project_name}-\${var.environment}-rg"
}

# =============================================================================
# Key Vault (prerequisite — created by cloud:init --azure)
# =============================================================================

data "azurerm_key_vault" "main" {
  name                = "\${var.project_name}-\${var.environment}-kv"
  resource_group_name = data.azurerm_resource_group.main.name
}

# =============================================================================
# Tags
# =============================================================================

locals {
  tags = {
    Environment = var.environment
    ManagedBy   = "tsdevstack"
    Project     = var.project_name
  }
}
`;
}
