import { describe, it, expect } from '@rstest/core';
import { generateContainerAppsEnvTf } from './generate-container-apps-env-tf';

describe('generateContainerAppsEnvTf', () => {
  describe('Log Analytics Workspace', () => {
    it('should create Log Analytics Workspace resource', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain(
        'resource "azurerm_log_analytics_workspace" "main"',
      );
    });

    it('should use PerGB2018 SKU', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain('sku                 = "PerGB2018"');
    });

    it('should set 30 day retention', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain('retention_in_days   = 30');
    });

    it('should reference resource group data source', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain(
        'resource_group_name = data.azurerm_resource_group.main.name',
      );
    });

    it('should apply tags', () => {
      const result = generateContainerAppsEnvTf();
      const logBlock = result.slice(
        result.indexOf('resource "azurerm_log_analytics_workspace" "main"'),
        result.indexOf('resource "azurerm_container_app_environment" "main"'),
      );
      expect(logBlock).toContain('tags                = local.tags');
    });
  });

  describe('Container Apps Environment', () => {
    it('should create Container Apps Environment resource', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain(
        'resource "azurerm_container_app_environment" "main"',
      );
    });

    it('should integrate with Container Apps subnet', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain(
        'infrastructure_subnet_id       = azurerm_subnet.container_apps.id',
      );
    });

    it('should enable internal load balancer (VNet-only access, Kong reaches services via private DNS)', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain('internal_load_balancer_enabled = true');
    });

    it('should disable public network access (required for ILB)', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain('public_network_access          = "Disabled"');
    });

    it('should set logs destination to log-analytics', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain(
        'logs_destination               = "log-analytics"',
      );
    });

    it('should link to Log Analytics Workspace', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain(
        'log_analytics_workspace_id     = azurerm_log_analytics_workspace.main.id',
      );
    });

    it('should apply tags', () => {
      const result = generateContainerAppsEnvTf();
      const envBlock = result.slice(
        result.indexOf('resource "azurerm_container_app_environment" "main"'),
      );
      expect(envBlock).toContain('tags                           = local.tags');
    });
  });

  describe('workload profile', () => {
    it('should include Consumption workload_profile block (prevents drift from Azure auto-adding it)', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain('workload_profile {');
      expect(result).toContain('workload_profile_type = "Consumption"');
    });
  });

  describe('lifecycle', () => {
    it('should ignore changes to infrastructure_resource_group_name', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain(
        'ignore_changes = [infrastructure_resource_group_name]',
      );
    });
  });

  describe('header comment', () => {
    it('should include generation comment', () => {
      const result = generateContainerAppsEnvTf();
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });
});
