/**
 * Generate redis.tf with Azure Managed Redis and Private Endpoint
 */

import type { AzureInfraConfig } from '../../types/config.ts';

export function generateRedisTf(config: AzureInfraConfig): string {
  return `# Azure Managed Redis
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# Azure Managed Redis
# =============================================================================

resource "azurerm_managed_redis" "main" {
  name                = "\${var.project_name}-\${var.environment}-redis"
  resource_group_name = data.azurerm_resource_group.main.name
  location            = data.azurerm_resource_group.main.location
  sku_name            = "${config.redis.tier}"
  tags                = local.tags

  default_database {
    access_keys_authentication_enabled = true
    clustering_policy                  = "EnterpriseCluster"
    eviction_policy                    = "NoEviction"
  }
}

# =============================================================================
# Private Endpoint
# =============================================================================

resource "azurerm_private_endpoint" "redis" {
  name                = "\${var.project_name}-\${var.environment}-redis-pe"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  subnet_id           = azurerm_subnet.private_endpoints.id
  tags                = local.tags

  private_service_connection {
    name                           = "redis-connection"
    private_connection_resource_id = azurerm_managed_redis.main.id
    subresource_names              = ["redisEnterprise"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "redis-dns"
    private_dns_zone_ids = [azurerm_private_dns_zone.redis.id]
  }
}
`;
}
