/**
 * Generate database.tf with PostgreSQL Flexible Server and per-service databases
 */

import type { AzureInfraConfig } from '../../types/config.ts';

export function generateDatabaseTf(config: AzureInfraConfig): string {
  const serviceDatabases = config.servicesWithDatabase
    .filter((s) => s.hasDatabase)
    .map((s) => `"${s.name}"`)
    .join(', ');

  const storageMb = config.database.storageSizeGb * 1024;

  return `# PostgreSQL Flexible Server
# Generated by: npx tsdevstack infra:generate

# =============================================================================
# Admin Password
# =============================================================================

resource "random_password" "db_admin" {
  length  = 32
  special = false
}

# =============================================================================
# PostgreSQL Flexible Server
# =============================================================================

resource "azurerm_postgresql_flexible_server" "main" {
  name                          = "\${var.project_name}-\${var.environment}-postgres"
  resource_group_name           = data.azurerm_resource_group.main.name
  location                      = data.azurerm_resource_group.main.location
  version                       = "16"
  delegated_subnet_id           = azurerm_subnet.postgres.id
  private_dns_zone_id           = azurerm_private_dns_zone.postgres.id
  administrator_login           = "tsdevstack"
  administrator_password        = random_password.db_admin.result
  sku_name                      = "${config.database.tier}"
  storage_mb                    = ${storageMb}
  backup_retention_days         = ${config.database.backup ? 35 : 7}
  geo_redundant_backup_enabled  = false
  public_network_access_enabled = false
  tags                          = local.tags

  depends_on = [azurerm_private_dns_zone_virtual_network_link.postgres]

  lifecycle {
    ignore_changes = [zone, high_availability[0].standby_availability_zone]
  }
}

# =============================================================================
# Per-Service Databases
# =============================================================================

resource "azurerm_postgresql_flexible_server_database" "services" {
  for_each  = toset([${serviceDatabases}])
  name      = each.value
  server_id = azurerm_postgresql_flexible_server.main.id
  charset   = "UTF8"
  collation = "en_US.utf8"
}

# =============================================================================
# SSL Configuration
# =============================================================================

resource "azurerm_postgresql_flexible_server_configuration" "require_ssl" {
  name      = "require_secure_transport"
  server_id = azurerm_postgresql_flexible_server.main.id
  value     = "on"
}
`;
}
