/**
 * Generate storage.tf with Azure Blob Storage for object storage
 *
 * Creates:
 * - One shared storage account per project-env ({project}{env}storage)
 * - One storage container per configured bucket
 * - Role assignment: Storage Blob Data Contributor for managed identity
 * - CORS rules on the storage account
 * - Soft delete retention policy (7 days)
 *
 * Azure storage account names: alphanumeric only, max 24 chars.
 */

import type { AzureInfraConfig } from '../../types/config.ts';

export function generateBlobStorageTf(config: AzureInfraConfig): string {
  if (config.storageBuckets.length === 0) {
    return '';
  }

  // Azure storage account name: alphanumeric only, max 24 chars
  const sanitizedProject = config.projectName.replace(/[^a-z0-9]/g, '');
  const storageAccountName = `${sanitizedProject}${config.environment}storage`;

  const containerMap = config.storageBuckets
    .map(
      (b) => `    "${b}" = "${config.projectName}-${b}-${config.environment}"`,
    )
    .join('\n');

  return `# Azure Blob Object Storage
# Generated by: npx tsdevstack infra:generate

locals {
  storage_containers = {
${containerMap}
  }
  storage_account_name = "${storageAccountName}"
}

# =============================================================================
# Storage Account (shared per project-env)
# =============================================================================

resource "azurerm_storage_account" "storage" {
  name                     = local.storage_account_name
  resource_group_name      = data.azurerm_resource_group.main.name
  location                 = data.azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"
  tags                     = local.tags

  blob_properties {
    delete_retention_policy {
      days = 7
    }

    cors_rule {
      allowed_headers    = ["*"]
      allowed_methods    = ["GET", "PUT", "POST", "DELETE", "HEAD"]
      allowed_origins    = ["*"]
      exposed_headers    = ["ETag", "Content-Length", "Content-Type"]
      max_age_in_seconds = 3600
    }
  }
}

# =============================================================================
# Storage Containers (one per bucket)
# =============================================================================

resource "azurerm_storage_container" "storage" {
  for_each = local.storage_containers

  name                  = each.value
  storage_account_id    = azurerm_storage_account.storage.id
  container_access_type = "private"
}

# =============================================================================
# IAM — grant Storage Blob Data Contributor to Container Apps managed identity
# =============================================================================

resource "azurerm_role_assignment" "storage_blob_contributor" {
  scope                            = azurerm_storage_account.storage.id
  role_definition_name             = "Storage Blob Data Contributor"
  principal_id                     = azurerm_user_assigned_identity.container_apps.principal_id
  skip_service_principal_aad_check = true
}

# =============================================================================
# Output
# =============================================================================

output "storage_buckets" {
  description = "Storage container names and metadata"
  value = {
    for key, container in azurerm_storage_container.storage :
    key => {
      name                 = container.name
      storage_account_name = azurerm_storage_account.storage.name
    }
  }
}
`;
}
