/**
 * Generate dns.tf with Azure DNS zone, Front Door custom domains, and DNS records
 *
 * Creates (when baseDomain is set):
 * - Azure DNS zone (user points registrar NS to Azure nameservers)
 * - Front Door custom domains with managed TLS (per service)
 * - DNS TXT validation records (per custom domain)
 * - DNS CNAME records pointing to Front Door endpoints
 *
 * Custom domains are created for:
 * - API (always) — api.{baseDomain}
 * - App (if Next.js services exist) — {serviceName}.{baseDomain}
 * - SPAs (per SPA) — {spaName}.{baseDomain}
 */

import type { AzureInfraConfig } from '../../types/config.ts';
import { toTerraformId } from '../../utils/terraform/to-terraform-id.ts';

/**
 * Generate dns.tf with DNS zone, custom domains, and DNS records
 */
export function generateDnsTf(config: AzureInfraConfig): string {
  if (!config.baseDomain) {
    return `# No custom domain configured
# Generated by: npx tsdevstack infra:generate
`;
  }

  const nextjsEntries = Object.entries(config.frontends);
  const spaEntries = Object.entries(config.spas);

  // API custom domain (always present when baseDomain is set)
  const apiSection = buildCustomDomainSection({
    label: 'api',
    tfId: 'api',
    azureName: `\${var.project_name}-\${var.environment}-api`,
    domain: `api.${config.baseDomain}`,
    baseDomain: config.baseDomain,
    endpointRef: 'azurerm_cdn_frontdoor_endpoint.api.host_name',
  });

  // Next.js custom domains (per service)
  const nextjsSections = nextjsEntries
    .map(([name, nextjsConfig]) => {
      const tfId = toTerraformId(name);
      return buildCustomDomainSection({
        label: `nextjs ${name}`,
        tfId: `nextjs_${tfId}`,
        azureName: `\${var.project_name}-\${var.environment}-nextjs-${name}`,
        domain: nextjsConfig.domain,
        baseDomain: config.baseDomain,
        endpointRef: `azurerm_cdn_frontdoor_endpoint.nextjs_${tfId}.host_name`,
      });
    })
    .join('');

  // SPA custom domains (per SPA)
  const spaSections = spaEntries
    .map(([name, spaConfig]) => {
      const tfId = toTerraformId(name);
      return buildCustomDomainSection({
        label: `spa ${name}`,
        tfId: `spa_${tfId}`,
        azureName: `\${var.project_name}-\${var.environment}-spa-${name}`,
        domain: spaConfig.domain,
        baseDomain: config.baseDomain,
        endpointRef: `azurerm_cdn_frontdoor_endpoint.spa_${tfId}.host_name`,
      });
    })
    .join('');

  return `# DNS + Custom Domains
# Generated by: npx tsdevstack infra:generate
#
# Azure DNS zone managed by Terraform. Point registrar NS to Azure nameservers.
# Custom domains use Front Door managed TLS certificates.

# =============================================================================
# DNS Zone
# =============================================================================

resource "azurerm_dns_zone" "main" {
  name                = var.base_domain
  resource_group_name = data.azurerm_resource_group.main.name
  tags                = local.tags
}

# =============================================================================
# Custom Domains + DNS Records
# =============================================================================
${apiSection}${nextjsSections}${spaSections}
# =============================================================================
# Outputs
# =============================================================================

output "dns_name_servers" {
  description = "Azure DNS name servers (point registrar NS records to these)"
  value       = azurerm_dns_zone.main.name_servers
}
`;
}

interface CustomDomainParams {
  label: string;
  tfId: string;
  azureName: string;
  domain: string;
  baseDomain: string;
  endpointRef: string;
}

function buildCustomDomainSection(params: CustomDomainParams): string {
  const { label, tfId, azureName, domain, baseDomain, endpointRef } = params;
  const isApex = domain === baseDomain;
  const subdomain = isApex ? '' : domain.replace(`.${baseDomain}`, '');
  const dnsAuthName = isApex ? '_dnsauth' : `_dnsauth.${subdomain}`;

  const dnsRecord = isApex
    ? `
resource "azurerm_dns_a_record" "${tfId}" {
  name                = "@"
  zone_name           = azurerm_dns_zone.main.name
  resource_group_name = data.azurerm_resource_group.main.name
  ttl                 = 3600

  target_resource_id = azurerm_cdn_frontdoor_endpoint.${tfId}.id
}`
    : `
resource "azurerm_dns_cname_record" "${tfId}" {
  name                = "${subdomain}"
  zone_name           = azurerm_dns_zone.main.name
  resource_group_name = data.azurerm_resource_group.main.name
  ttl                 = 3600
  record              = ${endpointRef}
}`;

  return `
# ${label}
resource "azurerm_cdn_frontdoor_custom_domain" "${tfId}" {
  name                     = "${azureName}"
  cdn_frontdoor_profile_id = azurerm_cdn_frontdoor_profile.main.id
  dns_zone_id              = azurerm_dns_zone.main.id
  host_name                = "${domain}"

  tls {
    certificate_type = "ManagedCertificate"
  }
}

resource "azurerm_dns_txt_record" "${tfId}_validation" {
  name                = "${dnsAuthName}"
  zone_name           = azurerm_dns_zone.main.name
  resource_group_name = data.azurerm_resource_group.main.name
  ttl                 = 3600

  record {
    value = azurerm_cdn_frontdoor_custom_domain.${tfId}.validation_token
  }
}
${dnsRecord}
`;
}
