/**
 * Tests for generate-container-apps-identity-tf
 */

import { describe, it, expect } from '@rstest/core';
import { generateContainerAppsIdentityTf } from './generate-container-apps-identity-tf';

describe('generateContainerAppsIdentityTf', () => {
  const result = generateContainerAppsIdentityTf();

  describe('Generation header', () => {
    it('should include generation comment', () => {
      expect(result).toContain('Generated by: npx tsdevstack infra:generate');
    });
  });

  describe('User-assigned managed identity', () => {
    it('should create azurerm_user_assigned_identity resource', () => {
      expect(result).toContain(
        'resource "azurerm_user_assigned_identity" "container_apps"',
      );
    });

    it('should use project_name and environment in identity name', () => {
      expect(result).toContain(
        'name                = "${var.project_name}-${var.environment}-ca-identity"',
      );
    });

    it('should reference resource group location', () => {
      expect(result).toContain(
        'location            = data.azurerm_resource_group.main.location',
      );
    });

    it('should reference resource group name', () => {
      expect(result).toContain(
        'resource_group_name = data.azurerm_resource_group.main.name',
      );
    });

    it('should include tags', () => {
      expect(result).toContain('tags                = local.tags');
    });
  });

  describe('AcrPull role assignment', () => {
    it('should create azurerm_role_assignment resource', () => {
      expect(result).toContain(
        'resource "azurerm_role_assignment" "container_apps_acr_pull"',
      );
    });

    it('should scope to container registry', () => {
      expect(result).toContain(
        'scope                            = azurerm_container_registry.main.id',
      );
    });

    it('should assign AcrPull role', () => {
      expect(result).toContain('role_definition_name             = "AcrPull"');
    });

    it('should use identity principal_id', () => {
      expect(result).toContain(
        'principal_id                     = azurerm_user_assigned_identity.container_apps.principal_id',
      );
    });

    it('should skip AAD check for faster propagation', () => {
      expect(result).toContain('skip_service_principal_aad_check = true');
    });
  });

  describe('Key Vault Secrets User role assignment', () => {
    it('should create keyvault role assignment resource', () => {
      expect(result).toContain(
        'resource "azurerm_role_assignment" "container_apps_keyvault_secrets"',
      );
    });

    it('should scope to Key Vault data source', () => {
      expect(result).toContain(
        'scope                            = data.azurerm_key_vault.main.id',
      );
    });

    it('should assign Key Vault Secrets User role', () => {
      expect(result).toContain(
        'role_definition_name             = "Key Vault Secrets User"',
      );
    });

    it('should use identity principal_id', () => {
      // Both role assignments use the same identity
      const matches = result.match(
        /principal_id\s+=\s+azurerm_user_assigned_identity\.container_apps\.principal_id/g,
      );
      expect(matches).toHaveLength(2);
    });
  });
});
